config/services.yml
10 new datasets to reformat to zarr.
=> Added new preSWOT datasets to zarr reformatter

config/services.yml
Add MUR and MUR25 to UAT zarr reformatter for test ahead of production integration.
=> Add MUR and MUR25 to UAT zarr

config/services.yml
Collection Concept Id: C1234724470-POCLOUD
=> Add MODIS_A-JPL-L2P-v2019.0 to uat gdal-subsetter

app/frontends/jobs.ts, app/models/job.ts, test/helpers/jobs.ts, test/jobs/jobs-listing.ts
Removes links that were inadvertently included in jobs listing.
=> HARMMONY-482: Remove links from jobs listings (bug fix)

config/services.yml
add UMM-S for GES DISC collections to HOSS
=> S1241070355-GES_DISC

docs/Configuring a Harmony service.ipynb, docs/Harmony API introduction.ipynb, docs/Harmony Feature Examples.ipynb, docs/Harmony Zarr Reformatter.ipynb, docs/HarmonyRegression.ipynb, docs/Harmony_20.2Demo.ipynb, docs/Harmony_20.3Demo.ipynb, docs/Harmony_20.4Demo.ipynb, docs/Harmony_21.1.1Demo.ipynb, docs/notebook_helpers/requirements.txt, docs/team_demos/Harmony API.ipynb, docs/team_demos/Harmony_20.2Demo.ipynb, docs/team_demos/SWOT-TestData-19-4.ipynb, package-lock.json, package.json
Testable by starting Jupyter with a venv free of libraries other than Jupyter itself and running any notebook to verify all imports work.  During development, I started clean on each notebook and ran all cells that performed an import.
=> HARMONY-905: Update all notebooks to express their dependencies

db/migrations/20211104132112_add_has_aggrated_ouptput_to_workflow_steps.js
=> HARMONY-959: Fix db migration

tasks/service-runner/package.json
Quick fix to resolve test timeouts in CI
=> HARMONY-997: fix test timeouts in Bamboo

config/services.yml
PODAAC Concise UAT UMM-S: S1242328818-POCLOUD
This is needed as we prepare for the Thursday review.
=> Added UMM-S concept IDs for PODAAC Concise

app/backends/service-metrics.ts, app/server.ts, tasks/service-runner/app/routers/router.ts, tasks/service-runner/app/service/service-metrics.ts, tasks/service-runner/app/workers/pull-worker.ts, tasks/service-runner/config/asf-gdal-service-sidecar.yaml, tasks/service-runner/config/harmony-service-example-sidecar.yaml, tasks/service-runner/config/netcdf-to-zarr-sidecar.yaml, tasks/service-runner/config/podaac-concise-sidecar.yaml, tasks/service-runner/config/podaac-l2-subsetter-sidecar.yaml, tasks/service-runner/config/query-cmr-sidecar.yaml, tasks/service-runner/config/sds-maskfill-sidecar.yaml, tasks/service-runner/config/swot-reproject-sidecar.yaml, tasks/service-runner/config/trajectory-subsetter-sidecar.yaml, tasks/service-runner/config/var-subsetter-sidecar.yaml, tasks/service-runner/test/service-metrics.ts, test/service-metrics-backends.ts
This PR implements the metric service from `service_runner` to generate metric for prometheus.
There were very nice suggestions during tech meeting such as re-using the axios call from pull_worker, but I decided not doing that since they have different validateStatus.
Also, I have removed the image sanitizing because I decided to remove the logging from backend (otherwise the console will be overwhelmed).
=> Harmony 999

db/db.sql, db/migrations/20220202165311_add_fair_queueing_indices_to_jobs.js
Adds indices needed for efficient querying related to fair queueing.
=> Harmony 1059 fair queueing

app/models/work-item.ts, tasks/service-runner/config/service-template.yaml
Fixes an issue with the queries not working on postgres
=> HARMONY-451: Fix fair queueing queries for postgres

config/services.yml
request to add the trajectory subset service for ORNL.
=> add ornl subsetter service

.github/pull_request_template.md
This is my first pass at adding a PR template for the repo. Feel free to add comments if you want changes. This template is the boilerplate text that will appear in the comment box when you create a PR - you will edit this as necessary.
=> HARMONY-1100: Add GitHub PR template to help adding/reviewing PRs

config/services.yml
N/A
Added shape: true option to l2ss-py in prod now that 1.4.0 has been deployed to prod, which supports shapefile subsetting.
=> Added shape option to l2ss-py in prod

package-lock.json, package.json
HARMONY-1183
Update multer dependency
Run `npm audit` and verify no vulnerabilities reported.
* ~[ ] Tests added/updated (if needed) and passing~
* ~[ ] Documentation updated (if needed)~
=> HARMONY-1183: Update multer dependency.

config/services.yml
Added S2279690167-LARC_ASDC to podaac/l2-subsetter for TEMPO L2 NO2 data product
=> Added S2279690167-LARC_ASDC to podaac/l2-subsetter

app/frontends/ogc-coverages/describe-collections.ts, app/util/variables.ts
HARMONY-1206
Fixes bug introduced in 1206 related to query-cmr
Start harmony and verify that you can run a service request
=> HARMONY-1206: Refactor to fix query-cmr task issues

tasks/query-cmr/app/query.ts, tasks/query-cmr/app/routers/router.ts, tasks/query-cmr/test/query-granules.ts
HARNONY-1240
Fix bug in path for qury-cmr granule STAC item files
Do a sandbox deployment including a query-cmr image and do a long query (exceeding one page)
=> Harmony 1240 fix

config/services.yml
=> add ORNL_CLOUD HOSS service entries for UAT and Prod

app/backends/workflow-orchestration.ts, app/models/work-item.ts, tasks/service-runner/app/workers/pull-worker.ts, tasks/service-runner/test/pull-worker.ts
several
Fixes (?) some bugs causing timeouts and race conditions in retrieving and updating work items
Deploy to sandbox and run long queries
=> Harmony 1243 podaac work item timout

config/services.yml
LaRC ASDC added three TEMPO collection Ids to the L2ss in UAT for testing
=> LaRC ASDC added  TEMPO collections to L2ss in UAT

app/models/services/base-service.ts, test/helpers/data-operation.ts, test/helpers/job-status.ts, test/helpers/stub-service.ts, test/models/services.ts, test/ogc-api-coverages/get-coverage-rangeset.ts
HARMONY-1299
Adds some missing tests for conditionally creating workflow steps based on an operation for a multi-service chain and refactors service selection tests.
Only test code changes, run the tests.
=> HARMONY-1299: Add tests for conditional workflow step creation in multi-service chains

public/notebook-example.html
HARMONY-1333
Removes unused JS. 
View http://localhost:3000/notebook-example.html
Make sure you don't see anything odd, or any errors in the console.
=> HARMONY-1333: Remove unused js tags

ENV_CHANGELOG.md, docs/adapting-new-services.md
HARMONY-1284
Update documentation for batching settings.
N/A
=> HARMONY-1284: Update documentation regarding batching

test/ogc-api-coverages/get-coverage-rangeset.ts
HARMONY-293
Fix commented out test simulating database failure.
`npm run test` and verify no failures.
=> HARMONY-293: Fix commented out test simulating database failure.

package-lock.json, tasks/service-runner/package-lock.json
DAS-1745
Audit failed on recent build #830
* [N/A] Acceptance criteria met
* [N/A] Tests added/updated (if needed) and passing
* [N/A] Documentation updated (if needed)
=> Fixes Node security advisories: 1088659

package-lock.json
HARMONY-1365
Fixed latest vulnerability reported in harmony ci build.
run `npm test`, verify no vulnerability is reported.
=> HARMONY-1365: Fixed latest vulnerability reported in ci build.

app/util/cmr.ts
HARMONY-1342
Fixes a TypeScript error in deployed environments that was not showing up locally
none
=> HARMONY-1342: Add type hint to fix compile problem in deployed envs

docs/guides/develop.md, docs/testing-services.md
HARMONY-1353
I went through the wiki to make sure that it was up-to-date, covered the necessary topics and did not conflict with anything in this repository. I also made sure that there are logical links between the wiki and repo documentation.
The wiki will continue to serve as a higher level entry point for users (technical and non-technical), pointing to the technical guides in this repo as appropriate.
n/a
=> Harmony 1353 - Streamline wiki documentation

app/frontends/wms.ts, docs/Harmony API introduction.ipynb
HARMONY-1382
Fixed parameter validation error when calling WebMapService.getmap in Harmony API Introduction notebook.
Updated introduction notebook to run WMS GetMap successfully.
Change `harmony_root` to `http://localhost:3000`, verify the introduction notebook can be executed successfully against local harmony.
Colab integration can be verified once the harmony code change is deployed to UAT. Not worth the effort to test it before the code is merged.
=> HARMONY-1382: Fixed parameter validation error when calling WebMapService.getmap in Harmony API Introduction notebook.

docs/Harmony API introduction.ipynb
General
Minor change to Introduction notebook to make EDL authentication process more user friendly.
Run introduction notebook and verify a `Password:` prompt is shown during EDL authentication and things still work.
=> Minor change to make EDL authentication more user friendly in Introduction notebook

app/models/services/base-service.ts, package-lock.json, package.json, test/models/services.ts
HARMONY-1390
Fixed workflow step staging location setting to consider optional steps.
Run harmony locally,
```
http://localhost:3000/C1245618475-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=lat(30%3A60)&subset=lon(-50%3A-20)&maxResults=1
```
Then verify the result is staged in the local staging location rather than the artifact location.
Sandbox deployment: http://internal-harmony-yliu10-frontend-1773324529.us-west-2.elb.amazonaws.com/
=> HARMONY-1390: Fixed workflow step staging location setting to consider optional steps.

.nsprc, app/frontends/docs/docs.ts, tasks/service-runner/.nsprc
HARMONY-1392
Fixes broken link to bearer token generator on documentation page
1. check out this branch
2. run harmony locally
3. open the documentation page at http://localhost:3000/docs
4. verify that the 'bearer token' link in the Getting Started section points to UAT (will be prod EDL in production)
=> HARMONY-1392: Fixed broken link to bearer token generator

app/markdown/apis.md, app/markdown/endpoints.md
=> HARMONY-1378: Fix OCG typos

docs/guides/develop.md, env-defaults
HARMONY-1446
Fix urls to use proper localstack host in developer docs
none
=> Harmony 1446

README.md, docs/guides/develop.md
HARMONY-1439
Update the example requests in the READMEs to include output format so that the example won't break due to the UMM-S changes in services.yml
Run the example requests in READMEs and verify they work.
=> HARMONY-1439: Updated example requests in READMEs.

app/models/work-item.ts, app/models/workflow-steps.ts, app/util/env.ts, app/workers/work-reaper.ts, env-defaults
HARMONY-1462
Rewrite work reaper to do batching during record retrieving rather than just deletion in batches. Also changed the retrieval query to only get the field (only id) that is needed by work reaper rather than all fields.
Update the work reaper related configurations (`WORK_REAPER_BATCH_SIZE`, `WORK_REAPER_PERIOD_SEC` and `WORK_REAPER_BATCH_SIZE` to some lower values to make the work reaper job run more easily monitor-able in local dev) and verify it is cleaning up terminal work items and workflow steps as desired.
The OOM error fix verification can be done by reviewing the code change that is outlined in the Description above.
=> HARMONY-1462: Fixed work reaper OOM error in PROD.

bin/create-k8s-config-maps-and-secrets
HARMONY-1420
Fixes issue with YML file creation for k8s config map and secrets.
Look at the deployment logs for this branch https://ci.earthdata.nasa.gov/deploy/viewDeploymentResult.action?deploymentResultId=462062129
=> HARMONY-1420: Fix YML file creation for k8s config map and secrets

app/util/object-store/s3-object-store.ts, app/util/queue/sqs-queue.ts, bin/deploy-services
HARMONY-1480
Fixes harmony in a box issues with queues and signed URLs from recent changes.
Test to make sure local requests continue to work.
Then `kubectl delete ns harmony` and set up harmony in a box from this branch (make sure to run `npm run build` and change your .env file to one for harmony in a box.
Verify no errors creating queues with `bin/bootstrap-harmony`.
Verify you can successfully submit a request.
=> HARMONY-1480: Fix harmony in a box with recent changes for queues and AWS SDK 3 update.

.nsprc, kubernetes-services/work-scheduler/.nsprc, tasks/giovanni-adapter/.nsprc, tasks/query-cmr/.nsprc, tasks/service-runner/.nsprc
=> FIX-1092278: Add low vulnerability to .nsprc since we don't have a fix and don't expose it

.nsprc, kubernetes-services/work-scheduler/.nsprc, kubernetes-services/work-scheduler/package-lock.json, package-lock.json, package.json, tasks/giovanni-adapter/.nsprc, tasks/giovanni-adapter/package-lock.json, tasks/query-cmr/.nsprc, tasks/query-cmr/package-lock.json, tasks/service-runner/.nsprc, tasks/service-runner/package-lock.json
HARMONY-900
Fixes security issues (build failure) discovered upon merging in the previous harmony-900 PR.
run `npx better-npm-audit` audit for each package.json
=> HARMONY-900: Npm audit updates

env-defaults, kubernetes-services/work-scheduler/env-defaults
DAS-1885
Needed to update some vars to get harmony in a box to work with HyBIG
Pull the branch.
Bootstrap harmony.
Browse to this url
http://localhost:3000/C1256584478-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&granuleId=G1256584570-EEDTEST&format=image%2Fpng
Verify the code completed successfully
* [n/a] Acceptance criteria met
* [n/a] Tests added/updated (if needed) and passing
* [n/a] Documentation updated (if needed)
=> DAS-1885 Adds HYBIG_SERVICE_QUEUE_URLS environment for harmony in a box

.nsprc, bin/create-k8s-config-maps-and-secrets, bin/delete-prometheus, bin/deploy-hpa, bin/deploy-prometheus, bin/deploy-services, bin/restart-services, kubernetes-services/work-scheduler/.nsprc, package-lock.json, tasks/service-runner/.nsprc
HARMONY-1536
Cleaned up logging during deployment. Addressed audit failures causing build to fail.
Run the modified scripts in the bin directory and verify no regressions.
Run `better-npm-audit audit` in all of the directories and verify no issues.
=> HARMONY-1536: Reduce irrelevant logging during deployment

config/services.yml
HARMONY-1548
Update Harmony service.yml gesdisc/giovanni service configuration to match Giovanni created UMM-S records
Run `npm run compare-services` and verify no discrepancies are reported.
=> HARMONY-1548: Update Harmony service.yml gesdisc/giovanni service configuration to match Giovanni created UMM-S records

app/backends/workflow-orchestration/work-item-updates.ts, app/util/log-execution.ts
HARMONY-1550
Added performance logging for work item update for the performance enhancement tickets coming up. I have decided not to use decorator for the class method logging because I don't see a clear way to set up logger for class methods and it is too much hassle for this particular ticket at this time. We probably want to write a ticket to come up with better ways of performance logging than what is done in this ticket later.
Run harmony request and verify that work item update related timing info is logged under: `timing.HWIUWJI*end`
=> HARMONY-1550: Added performance logging for work item update

kubernetes-services/work-scheduler/tsconfig.build.json, kubernetes-services/work-updater/tsconfig.build.json
=> HARMONY-1509: HARMONY-1509: Add tsoncifg.build.json for scheduler and updater to fix build

lib/util/tsconfig.build.json
HARMONY-1509
Forgot to add tsconfig.build.json file for lib/util
N/A
=> HARMONY-1509: Add missing tsconfig.build.json file

.nsprc, kubernetes-services/work-failer/package-lock.json, kubernetes-services/work-failer/package.json, kubernetes-services/work-reaper/package-lock.json, kubernetes-services/work-reaper/package.json, kubernetes-services/work-scheduler/.nsprc, kubernetes-services/work-scheduler/package-lock.json, kubernetes-services/work-scheduler/package.json, kubernetes-services/work-updater/package-lock.json, kubernetes-services/work-updater/package.json, lerna.json, lib/util/package-lock.json, lib/util/package.json, package-lock.json, package.json, tasks/giovanni-adapter/.nsprc, tasks/giovanni-adapter/package-lock.json, tasks/giovanni-adapter/package.json, tasks/query-cmr/package-lock.json, tasks/query-cmr/package.json, tasks/service-runner/.nsprc, tasks/service-runner/package-lock.json, tasks/service-runner/package.json
HARMONY-1595
Fixes the build and adds new npm script to run better-npm-audit at the top level and using lerna in all the subprojects
npm run better-audit
lerna run better-audit
=> HARMONY-1595: Fix build and add better-audit npm script

app/markdown/apis.md, app/markdown/docs.md, app/markdown/endpoints.md, app/markdown/jobs.md, app/markdown/overview.md, app/markdown/stac.md, kubernetes-services/work-scheduler/package-lock.json, lib/util/package-lock.json, package-lock.json, tasks/giovanni-adapter/package-lock.json, tasks/query-cmr/package-lock.json, tasks/service-runner/package-lock.json, test/documentation-page.ts
HARMONY-1578
Added api doc for /stac endpoints.
Go to http://localhost:3000/docs, verify harmony api doc has been re-organized, the /stac endpoints api doc has been added and accessible from the link in the endpoints summary table.
=> HARMONY-1578: Added api doc for /stac endpoints.

services/harmony/app/markdown/capabilities.md, services/harmony/app/markdown/docs.md, services/harmony/app/markdown/endpoints.md, services/harmony/app/markdown/jobs.md, services/harmony/app/markdown/overview.md, services/harmony/app/markdown/stac.md, services/harmony/test/documentation-page.ts, services/service-runner/test/pull-worker.ts
HARMONY-1575
Added api doc for /capabilities endpoint and some other updates to the api doc.
Go to http://localhost:3000/docs, verify harmony api doc has been re-organized and modified properly, the /capabilities endpoints api doc has been added and accessible from the link in the endpoints summary table.
=> HARMONY-1575: Added api doc for /capabilities endpoint.

bin/create-k8s-config-maps-and-secrets
HARMONY-1597
Fixes an issue with the configmap creation failing due to comments in env files.
Verified with a sandbox deployment from Bamboo as well as a deployment to my own sandbox from my laptop.
=> HARMONY-1597: Fix deployment issue creating configmap

docs/guides/develop.md
HARMONY-1427
Cleaning up a couple of outdated references.
Run nvm use and verify the output matches the documentation.
=> HARMONY-1427: Update references to Node 16 to Node 18 in developer docs.

services/harmony/app/markdown/capabilities.md, services/harmony/app/markdown/jobs.md, services/harmony/app/markdown/stac.md
HARMONY-1577
Added api doc for jobs endpoints.
http://localhost:3000/docs#monitoring-jobs-with-the-jobs-api-and-the-workflow-ui
Verify adequate api doc is added for the jobs endpoints.
=> HARMONY-1577: As a user, I would like to view documentation for the /jobs endpoints.

services/harmony/app/markdown/endpoints.md
HARMONY-1579
The staging bucket policy documentation was already present and looks good - I just added a hyperlink to it in the available endpoints table.
Verify the staging bucket policy documentation looks appropriate and the link in the "Summary of available endpoints" table takes you to the correct documentation.
=> HARMONY-1579: Staging bucket policy documentation

db/migrations/20231211182816_add_is_complete_to_worklow_steps.js
HARMONY-1652
Add a migration to add is_complete to workflow_steps
Run the migration
=> HARMONY-1652: Add migration to add is_complete to workflow_steps

.nsprc, package.json, services/harmony/.nsprc
HARMONY-1573
This properly document the new vulnerability and fix the ci build.
npm run better-audit
=> HARMONY-1573: Properly document the new vulnerability.

package-lock.json, package.json, services/harmony/app/util/url.ts, services/service-runner/app/service/service-metrics.ts, services/service-runner/app/util/env.ts, services/service-runner/app/workers/pull-worker.ts
HARMONY-1671
Changes to assume internal load balancers use https instead of http.
Test along with the ci-cd branch in sandbox. See instructions in ci-cd PR.
Sanity check no issues with local harmony which should be unaffected by the change.
=> HARMONY-1671: Use https for load balancers

.nsprc, package.json
HARMONY-1705
Fixes the broken build due to audit issues that were not being caught during testing.
`npm run test` should now run `better-npm-audit` at the top level and then the tests (the tests already cover running `better-npm-audit` in the subdirectories).
Verify `npm run test` completes successfully.
=> HARMONY-1705: Fix tests command to run audit in the top level directory

services/harmony/app/backends/workflow-orchestration/work-item-updates.ts, services/harmony/test/aggregation-workflows.ts
HARMONY-1706
This PR changes the logic that creates a work item for the next step so that even if the current work-item fails we might 
create a work item for the next step if it is an aggregating step. Previously we only did this if the step used batching. This
prevented Batchee (which is not batched,  but does aggregate) from running if a work-item fails. This change allows any
aggregating step to proceed.
Since we don't have a reliable way to reproduce the original Batchee chain failures (the problem is transient), the best
we can do is make sure our other queries still work as expected. I am running the following query in the sandbox to make
sure it completes even though it always has a few failures:
```
https://internal-harmony-jn-1682-frontend-1034601994.us-west-2.elb.amazonaws.com/C …
```
=> HARMONY-1706: Allow all aggregating steps to proeceed when a work-item fails, not just batched steps.

.nsprc, package-lock.json, services/harmony/.nsprc, services/harmony/package-lock.json, services/service-runner/.nsprc, services/service-runner/package-lock.json, services/work-scheduler/.nsprc, services/work-scheduler/package-lock.json
HARMONY-1716
Update dependencies for vulnerabilities.
Run npm test and verify everything completes successfully.
=> HARMONY-1716: Update dependencies

package-lock.json, services/harmony/.nsprc, services/harmony/package-lock.json, services/service-runner/.nsprc, services/service-runner/package-lock.json, services/work-scheduler/.nsprc, services/work-scheduler/package-lock.json
HARMONY-1768
Fixed vulnerability: https://github.com/advisories/GHSA-ghr5-ch3p-vcr6
`npm run test` and verify test passes
=> HARMONY-1768: Fixed new vulnerability.

.nsprc, services/harmony/.nsprc
HARMONY-1787
Adds entries to .nsprc for  new (bogus) vulnerabilities
None
=> HARMONY-1787: Add entry .nsprc for vulnerability

.nsprc, package-lock.json, packages/util/package-lock.json, packages/util/package.json, services/giovanni-adapter/package-lock.json, services/giovanni-adapter/package.json, services/harmony/.nsprc, services/harmony/package-lock.json, services/harmony/package.json, services/query-cmr/package-lock.json, services/query-cmr/package.json, services/service-runner/package-lock.json, services/service-runner/package.json, services/work-failer/package-lock.json, services/work-failer/package.json, services/work-reaper/package-lock.json, services/work-reaper/package.json, services/work-scheduler/package-lock.json, services/work-scheduler/package.json, services/work-updater/package-lock.json, services/work-updater/package.json
HARMONY-1792
Fix for current audit issues pulled in from the commit on the harmony-1770 branch.
Run npm test and verify everything passes.
=> HARMONY-1792: Update dependencies

services/harmony/app/backends/workflow-orchestration/work-item-updates.ts, services/work-updater/app/workers/updater.ts
HARMONY-1826
Change work item updater performance logging to info level.
Verify work item updater performance logging is logged at info level.
=> HARMONY-1826: Change work item updater performance logging to info level.

package-lock.json, packages/util/package-lock.json, services/giovanni-adapter/package-lock.json, services/harmony/package-lock.json, services/query-cmr/package-lock.json
HARMONY-1849
Fix micromatch vulnerability.
Run `npm test` and verify that everything passes
=> HARMONY-1849: Update micromatch

services/harmony/.nsprc, services/harmony/app/middleware/earthdata-login-oauth-authorizer.ts, services/harmony/app/routers/router.ts, services/harmony/package-lock.json, services/harmony/package.json, services/harmony/test/earthdata-login.ts
HARMONY-1853
Fix Bearer tokens not working with /service-deployments-state route.
Tests (the least) to run:
1) Valid EDL bearer token is able to get and put /service-deployments-state
2) Valid Cookie Secret is able to get and put /service-deployments-state
3) Invalid EDL bearer token is unable to get or put /service-deployments-state
4) Invalid Cookie Secret is unable to get or put /service-deployments-state
5) Valid Cookie Secret is unable to get or put on routes other than /service-deployments-state, e.g. /service-deployment
=> HARMONY-1853: Fix Bearer tokens not working with /service-deployments-state route.

services/harmony/app/backends/service-metrics.ts, services/harmony/app/frontends/jobs.ts, services/harmony/app/middleware/label.ts, services/harmony/app/models/job.ts, services/harmony/app/models/label.ts, services/harmony/app/routers/router.ts, services/harmony/package-lock.json, services/harmony/package.json, services/harmony/test/jobs/jobs-listing.ts, services/harmony/test/jobs/jobs-status.ts, services/harmony/test/models/label.ts, services/harmony/test/parameters/label.ts
HARMONY-1895
Adds labels to jobs listings and status pages
* run a job and pass in labels using the `label` paramater
* load the jobs listing page (may not show any jobs on localhost due to a bug Chris discovered) and verify that labels are given for the jobs
http://localhost:3000/jobs
* load the admin jobs listing page and verify labels are shown
http://localhost:3000/admin/jobs
* load the job status page and verify labels are shown
http://localhost:3000/jobs/<job ID>
* load the admin job status page and verify labels are shown
http://localhost:3000/admin/jobs<job ID>
=> HARMONY-1895: Add labels to jobs listings and status pages

services/harmony/test/jobs/jobs-listing.ts
HARMONY-1895
Small change to test input to work around issue with Bamboo not liking emojis
Run `npm run test`
=> HARMONY-1895: Change test input to work around Bamboo issue

services/harmony/.nsprc, services/query-cmr/.nsprc, services/service-runner/.nsprc, services/work-failer/.nsprc, services/work-reaper/.nsprc, services/work-scheduler/.nsprc, services/work-updater/.nsprc
HARMONY-1915
Address new cookie vulnerability caused build error. This only fixed the build.
npm run test
=> HARMONY-1915: Address new cookie vulnerability.

services/work-failer/package-lock.json, services/work-failer/package.json, services/work-reaper/package-lock.json, services/work-reaper/package.json, services/work-scheduler/package-lock.json, services/work-scheduler/package.json, services/work-updater/package-lock.json, services/work-updater/package.json
HARMONY-1934
Add missing dependencies to harmony core services.
Run harmony-in-a-box locally and verify harmony core services starts successfully and submit a request runs to success.
=> HARMONY-1934: Add missing dependencies to harmony core services.

services/harmony/.nsprc, services/service-runner/.nsprc, services/work-scheduler/.nsprc
HARMONY-1948
Extend vulnerability exemption expiration date.
npm run test
=> HARMONY-1948: Extend vulnerability exemption expiration date.

config/services.yml, services/harmony/env-defaults
DAS-2255 
Local Harmony-In-A-Box needs to have Environment Variables that match the service name.
ensure `LOCALLY_DEPLOYED_SERVICES` includes `harmony-smap-l2-gridder` in your .env file.
pull this branch, bootstrap Harmony-In-A-Box and make sure the harmony-smap-l2-gridder containers are running.
* [n/a] Acceptance criteria met
* [n/a] Tests added/updated (if needed) and passing
* [n/a] Documentation updated (if needed)
=> DAS-2255: Make the environment variables match the service name.

services/harmony/.nsprc, services/harmony/package-lock.json, services/query-cmr/.nsprc, services/query-cmr/package-lock.json, services/service-runner/.nsprc, services/service-runner/package-lock.json, services/work-failer/.nsprc, services/work-failer/package-lock.json, services/work-reaper/.nsprc, services/work-reaper/package-lock.json, services/work-scheduler/.nsprc, services/work-scheduler/package-lock.json, services/work-updater/.nsprc, services/work-updater/package-lock.json
HARMONY-1964, HARMONY-1916
Addressed new path-to-regexp vulnerability and removed the cookie vulnerability as it becomes obsolete.
npm run test
=> HARMONY-1964, HARMONY-1916: Addressed new path-to-regexp vulnerability and obsolete cookie vulnerability.

.nsprc, package-lock.json, package.json, services/harmony/app/views/capabilities/index.mustache.html, services/harmony/app/views/footer.mustache.html, services/harmony/app/views/workflow-ui/job/index.mustache.html, services/harmony/app/views/workflow-ui/jobs/index.mustache.html, services/harmony/package-lock.json, services/harmony/package.json, services/harmony/test/workflow-ui/jobs.html
HARMONY-2006
Changes the NASA Official to Doug Newman.
Verify the footer on all pages shows Doug Newman as the NASA Official.
* http://localhost:3000
* http://localhost:3000/workflow-ui
* http://localhost:3000/admin/workflow-ui
* http://localhost:3000/docs
=> HARMONY-2006: Change NASA Official to Doug Newman

.nsprc, package-lock.json, package.json, packages/util/package-lock.json, packages/util/package.json, services/cron-service/package-lock.json, services/harmony/package-lock.json, services/service-runner/package-lock.json, services/work-failer/package-lock.json, services/work-scheduler/package-lock.json, services/work-updater/package-lock.json
HARMONY-2036
Address axios dependency issue and also added a new better-audit-output command to display the results of the better-audit command in subprojects.
Verify npm run test passes and regression test that harmony requests continue to work.
=> HARMONY-2036: Address axios dependency issue 

services/cron-service/package-lock.json, services/harmony/package-lock.json, services/service-runner/package-lock.json, services/work-failer/package-lock.json, services/work-scheduler/package-lock.json, services/work-updater/package-lock.json
HARMONY-2089
Address formidable vulnerability in Harmony.
Build all harmony images locally. Run harmony-in-a-box and verify things still work.
=> HARMONY-2089: Address formidable vulnerability in Harmony.

services/harmony/.nsprc, services/service-runner/.nsprc, services/work-scheduler/.nsprc
HARMONY-2091
Updates expirations for issues that require updating to use ES modules. Those updates will be handled with the individual tickets.
`npm run better-audit`
=> HARMONY-2091: Update nsprc expirations.

docs/guides/develop.md
Do you need a Jira Issue? I couldn't find your contributing page, but I'm guessing that if you are going to accept 3rd party pull requests, no Jira issue is needed?
I notice that when I go to https://github.com/nasa/harmony/blob/main/docs/guides/develop.md, there are helpful "copy" widgets on all the code blocks. Unfortunately, a lot of your code blocks start with `$`, which has to be deleted after pasting the code block and therefore kind of defeats the purpose of the copy widget!
This pull request just removes the `$` and also specifies the kind of code block where it hasn't already been specified. (My markdown linter complained, so I went ahead and specified where they were bash, text, etc.)
=> Small change to make copying and pasting commands easier

.nsprc, packages/util/.nsprc, services/cron-service/.nsprc, services/harmony/.nsprc, services/query-cmr/.nsprc, services/service-runner/.nsprc, services/work-failer/.nsprc, services/work-scheduler/.nsprc, services/work-updater/.nsprc
HARMONY-2117
Updated .nsprc for new vulnerability. The real patch will be tracked by HARMONY-2117 which will remain open.
npm run test
=> HARMONY-2117: Updated .nsprc for new vulnerability.

package-lock.json, services/cron-service/package-lock.json, services/harmony/package-lock.json, services/service-runner/package-lock.json, services/work-failer/package-lock.json, services/work-scheduler/package-lock.json, services/work-updater/package-lock.json
HARMONY-2182
Updates axios version.
Run `npm run better-audit` and verify it completes successfully.
=> HARMONY-2182: Update axios
