nasa/harmony

README.md
app/util/env.ts
package-lock.json
package.json

Fixes some small issues new devs were seeing:
1. The README for NVM had an inverted command (use before install) and the recommendation to re-check node version wasn't clear enough.  A dev encountered issues with an incorrect PATH setup even though NVM looked correct
2. Node version isn't enforced at all, which meant an incorrect node version could cause subtle problems
3. If GDAL_DATA is set in the environment, it's likely to cause issues with the gdal installed by our NPM module.  I added a warning when this happens along with instructions to override.
To test item 2, run `npm install` and `nvm use 12.4.0` (or any node version you have installed below v12.14.1), then run `npm test` and `npm run start-dev`  It should error out.
To see the GDAL warning behavior:
No GDAL_DATA set:
``` …
```

HARMONY-826: Clarify install, enforce node version and guard against GDAL_DATA

---

config/services.yml

Added sentinel 6 L2 collections (that contain groups) to podaac/l2-subsetter:
| Collection short name | Concept ID | 
|---|---|
|JASON_CS_S6A_L2_ALT_HR_RED_OST_NRT_F | C1238538225-POCLOUD|
|JASON_CS_S6A_L2_ALT_HR_STD_OST_NRT_F | C1238538224-POCLOUD|
|JASON_CS_S6A_L2_ALT_HR_RED_OST_STC_F | C1238538231-POCLOUD|
|JASON_CS_S6A_L2_ALT_HR_STD_OST_STC_F | C1238538230-POCLOUD|
|JASON_CS_S6A_L2_ALT_LR_RED_OST_NRT_F | C1238538233-POCLOUD|
|JASON_CS_S6A_L2_ALT_LR_STD_OST_NRT_F | C1238538232-POCLOUD|
|JASON_CS_S6A_L2_ALT_LR_RED_OST_STC_F | C1238538241-POCLOUD|

Added S6 collections to UAT l2 subsetter

---

config/services.yml

Added sentinel 6 L2 collections (that contain groups) to podaac/l2-subsetter (ops)

Added S6 collections to OPS l2 subsetter

---

app/routers/router.ts
app/views/index.mustache.html
public/analytics-tag.js
public/notebook-example.html

After talking to the main Goddard POC for google analytics and gaining access to the main dashboard, I added the analytics script to the following html pages:
- index
- documentation
- notebook example
Chrome inspector showed a 200 response (and no errors) from the request that pulls in the tracking JS. Statistics may take up to a day to show up from what I can tell, so I'll take a look at the dashboard tomorrow to see if things propagate properly.  Not sure if localhost will be tracked though(?), so we may need to deploy to SIT & UAT to validate further.

Harmony 251 - Add google analytics to public Harmony pages (documentation, landing page)

---

config/services.yml

This PR updates the collections associated with the `sds/variable-subsetter` Docker image to also include the UAT RSSMIF16D collections within the GHRC cloud provider.
Note, the Harmony OPeNDAP SubSetter (HOSS) is essentially a code branch within the `sds/variable-subsetter` Docker image. If a bounding box is included in the message parameters, it will be given the full HOSS treatment (to also perform a spatial subset). Otherwise the subsetter will perform as previously and only behave as a variable subsetter.
The different uses are separated by different UMM-S records, one of which allows a bounding box, the other does not. This prevents requests including a bounding box being made against granules from non-geographically gridded collections.

DAS-1086 - Activate HOSS for the GHRC RSSMIF16D collection.

---

app/schemas/history/0.1.0/history-v0.1.0.json

This PR updates the description for the `derived_from` attribute of the `history_json` schema (v0.1.0). This is an update to the existing schema version as it doesn't change any of the attributes of the schema itself.

DAS-1097 - Update history_json schema description for derived_from attribute

---

config/services.yml
config/workflow-templates/harmony-netcdf-to-zarr.yaml

Tested out in a sandbox environment with the following configuration:
2 c5.xlarge nodes (recommend changing from c5.large to c5.xlarge in each of our envs)
Submitted 20 requests each with 60 granules:
<sandbox_endpoint>/C1238621141-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?format=application%2Fx-zarr&maxResults=60
The requests correctly batched to 20 granules per batch. I saw 10 batches executed in parallel across the requests (never more than 2 batches at a time per workflow). The rest of the pods remained in a pending state because they could not reserve enough memory effectively queueing requests. I've seen a couple requests completing successfully so far with each batch taking no more than an hour and 15 minutes (plenty of room before the 4 hour timeout).
I'll …

HARMONY-855: Update netcdf-to-zarr batch size to 20 and set k8s request and limits for the netcdf-to-zarr service

---

app/schemas/history/0.1.0/history-v0.1.0.json

This PR makes a change to the `history_json` v0.1.0 schema to allow the parameters attribute to be a raw object (with unspecified properties) as proposed by David Auty. Because it only extends the options (and so is entirely backwards compatible) it has been proposed that the current semantic version (0.1.0) is overwritten, rather than a new version added.
I'm hopeful that this is the last change to the schema in the short term, and definitely hope it's the last update to v0.1.0.

DAS-1097 - Update history_json schema to allow parameters attribute to be an object

---

app/models/job.ts
db/db.sql
db/migrations/20210621095351_remove_json_links_from_jobs.js

Tested by deploying to a sandbox account. Verified that the database column is gone and jobs listings and jobs status calls come back the same as before. Also no problems submitting requests resulting in new jobs.

HARMONY-873: Remove _json_links column from the jobs table.

---

config/services.yml

This PR adds the UMM-S concept IDs for the services maintained by the Data Services team.
We'll use the GES DISC GPM_3IMERGHH and M2T1NXSLV (MERRA-2) collections as tests for the UMM-S/UMM-C mechanism. When that all works nicely, I'll probably submit a later PR to scrub the UMM-C entries from `services.yml` for our services that have the UMM-S/UMM-C association (which is most, if not all, of them).

DAS-1208 - Add UMM-S concept IDs for HOSS, Variable Subsetter and MaskFill

---

config/services.yml

L2 subsetter prod UMM-S: [S1962070864-POCLOUD](https://cmr.earthdata.nasa.gov/search/services.umm_json?concept_id=S1962070864-POCLOUD)
L2 subsetter uat UMM-S: [S1234899453-POCLOUD](https://cmr.uat.earthdata.nasa.gov/search/services.umm_json?concept_id=S1234899453-POCLOUD)

Added UMM-S concept IDs for PODAAC L2 subsetter

---

config/services.yml
package-lock.json
package.json

To test:
Run this and verify it calls the swotrepr + harmony-netcdf-to-zarr chain (just verify service selection and terminate, unless you have swotrepr in your local install):
http://localhost:3000/harmony_example_l2/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?format=application%2Fx-zarr&outputCrs=EPSG%3A4326
Run this and verify it calls the harmony-netcdf-to-zarr service un-chained in the argo console:
http://localhost:3000/harmony_example_l2/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?format=application%2Fx-zarr

Harmony 899: Service entry for harmony-netcdf-to-zarr + swotrepr

---

config/services.yml

In a joint effort with Joe Roberts, PODAAC is looking to deliver browse image generation using the asf gdal subsetter and needs to add the following collections to the service.
ECCO	C1239324659-POCUMULUS
ECCO	C1239379702-POCLOUD
MUR	C1238618571-POCUMULUS
MUR	C1238621141-POCLOUD
I have added these collections to the harmony/config/services.yml under the asf gdal service.

Added collections to asf gdal subsetter be used by PODAAC for browse image generation

---

workload/harmony/common.py
workload/locustfile.py
workload/requirements.txt

Here's a screenshot of the locust results with 25 concurrent users running against my sandbox with:
```
locust --exclude-tags uat-only
```
We'll plan to address auto-scaling pods based on the load of the individual services, but otherwise no issues related to turbo were observed.
Note this PR also makes it possible to track the performance of asynchronous requests by adding a manual 'async_job' metric event.

HARMONY-925: Updates to workload drivers to execute both argo and turbo requests

---

app/backends/workflow-orchestration.ts
app/models/services/base-service.ts
app/models/work-item.ts
test/workflow-orchestration.ts

This ticket has a single AC:
- When a step in a job is marked as an aggregated output job, Harmony does not invoke it until all prior steps complete
The work item that is generated for the aggregation step currently does not use all the output from the preceding step (although it does wait for all the output). That is the subject of HARMONY-961.

Harmony 960 wait for all inputs to aggregation

---

app/middleware/cmr-granule-locator.ts
test/ogc-api-coverages/get-coverage-rangeset.ts

Use argo granule locator instead of turbo for no-op service even if turbo mode is requested. This is necessary because the no-op service cannot handle the scroll-id sent by the new granule locator.

Harmony 1030

---

config/services.yml

Those concept ids were for the UAT collections. Updated to use the correct ones in ops

Use correct ops conceptids for asfgdal

---

config/services.yml

This PR adds POCLOUD collections to the uat podaac/l2-subsetter-concise service.

Add collections to uat podaac/l2-subsetter-concise

---

bin/deploy-hpa
config/hpa.yaml
config/prometheus-adapter-helm-values.yaml
env-defaults

This allows us to use the HPAs locally. (The corresponding CICD PR will be forthcoming.) To test this out locally:
- start Harmony as usual
- `bin/deploy-prometheus`
- `bin/deploy-hpa` (deploys HPA for each LOCALLY_DEPLOYED_SERVICES and query-cmr)
- try a request, e.g. http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?maxResults=100
- `kubectl describe hpa harmony-service-example -n harmony` or something similar in order to see the scaling in action
- optionally `kubectl port-forward pod/prometheus-6f8dccc575-lsqjs 9090:9090 -n monitoring` (substituting your Prometheus pod name) in order to view the graph of num_ready_work_items over time, using a PromQL query like `num_ready_work_items{name="harmony-service-example"}`
The HPAs are …

Harmony 979 - Add HPAs (horizontal pod autoscalers)

---

OPERATIONS.md
bin/delete-prometheus
bin/deploy-prometheus
config/kube-state-metrics/cluster-role-binding.yaml
config/kube-state-metrics/cluster-role.yaml
config/kube-state-metrics/deployment.yaml
config/kube-state-metrics/service-account.yaml
config/kube-state-metrics/service.yaml
config/prometheus.yaml

This PR adds the deployment of the `kube-state-metrics` service to the `deploy-prometheus` script to provide a lot of metrics convenient to monitoring the cluster/pods. An OPERATIONS.md file provides a starting point for documenting
general operating procedures not specific to our Harmony deployments. 
Specifically, this PR makes it possible to determine the number of running pods for each service (AC for HARMONY-1054).
This can be verified as follows:
1. deploy this branch to the sandbox
2. get the pod identifier for Prometheus
```
kubectl get pods -n monitoring [--kubeconfig <config file>]
```
3. forward port `9090` from the pod to your local machine
```
kubectl port-forward <Prometheus Pod ID> 9090:9090 -n monitoring [--kubeconfig <config file>]
```
4. Execute the following promQL in …

Harmony 1054 pod counts

---

config/services.yml

Links to UMM-S entries are in the comments of https://bugs.earthdata.nasa.gov/browse/GDDS-269
This should take care of enabling any new collections with the Harmony l2-subsetting service.

GDDS-269: Adding GES DISC UMM-S entries for l2-subsetter in UAT and PROD

---

tasks/service-runner/app/service/service-runner.ts
tasks/service-runner/test/fixtures/error-messages/error.json
tasks/service-runner/test/service-runner.ts

This PR follows on from work being done within HOSS to ensure error messages are well handled. In that work, we found that Harmony has a bit of an issue with logging messages that include curly braces. This is a particular issue for OPeNDAP error messages:
* OPeNDAP returns error messages that include curly braces, (e.g.: `{\n            font-size: 24px;\n            font-weight: bold;\n        }`)
* `harmony-service-lib-py` [logs all error messages to STDOUT](https://github.com/nasa/harmony-service-lib-py/blob/main/harmony/http.py#L361).
* `harmony-service-lib-py` then swallows the OPeNDAP error message, so the backend service can't access it.
* When the backend service fails, `harmony-service-lib-py` [creates `error.json` in the `WorkItem` …

DAS-1371 - Use error message from error.json in service-runner, if present.

---

app/models/job.ts
app/models/record.ts
app/models/work-item.ts
docs/fair-queueing.md
test/helpers/hooks.ts
test/helpers/jobs.ts
test/helpers/work-items.ts
test/helpers/workflow-steps.ts
test/work-items/fair-queueing.ts
test/work-items/work-backends.ts

Changes to the `getNextWorkItem` function to implement new queries that support fair queueing. Only added one test since other tests already confirm base functionality. How to test:
Test case 1 (single user):
1. Issue a long running (asynchronous) query.
2. Issue a synchronous (or at least short running) query for the same services.
The shorter job should finish first.
Test case 2 (multiuser):
1. Have user 1 issue a long running query (or multiple queries)
2. Have user 2 issue a short running query
Verify that user 2 job completes before long running jobs
Test case 3 (multiuser):
1. Have user 1 issue multiple (asynchronous) queries for a given service
2. Simultaneously have user 2 issue the same queries
Verify that both users' jobs complete about the same time.

Harmony 451 fair queueing

---

bin/deploy-prometheus
config/prometheus.yaml
env-defaults

I took a look at how quickly space was being consumed by prometheus and found that it was under 0.5MB per hour or 12MB per day. There are peaks every couple hours with the bulk of the space being used by the write ahead log which gets allocated in 128MB segments. Our defaults were to only allow 500MB of storage which resulted in the pod getting evicted (I suspect when some prometheus internal activity caused the write ahead log to allocate an additional segment).
I set the defaults to allow up to 2GB of ephemeral storage and added configuration to delete the oldest metrics when we reached 1750MB in size, which should prevent us from ever having the pod evicted due to running out of ephemeral storage.
Note I also bumped up the retention time from the current 6h to a configurable value …

HARMONY-1057: Prevent prometheus pod from being evicted due to running out of ephemeral storage.

---

db/migrations/20220301141810_add_work_item_foreign_keys.js
docs/fair-queueing.md

Tested locally with postgres and in a sandbox deployment. I also ran the following query to verify that we don't already have any work_items rows violating the new foreign key constraint in SIT/UAT/Prod.
```sql
select * from work_items w left join workflow_steps ws on "w"."jobID" = "ws"."jobID" and "w"."workflowStepIndex" = "ws"."stepIndex" where ws.id is null;
```
If you want to test this locally, check out the branch and the migration using `knex`. Then for an existing job ID try to insert a row into work_items that does not have a matching workflow_step row:
```sql
insert into work_items values(<some unused work_item_id>,<some real job id>,1000,'','foo','ready','',now(),now());
```
1000 above is just a really high workflowStepIndex that should not exist.

HARMONY-1076: Add migration to add foreign key constraint between work_items and workflow_steps

---

app/frontends/workflow-ui.ts
env-defaults
test/jobs/job-status-pagination.ts
test/jobs/jobs-listing.ts
test/stac/stac-pagination.ts

I verified manually that this doesn't break anything, but wasn't able to add a test for this because there is validation logic that prevents me from adding a job with a malformed request url.

HARMONY-1086: Fix URL formation error handling

---

app/routers/router.ts
test/routing.ts

I made the acceptable routes a bit more specific to prevent bad URLs from being processed as service requests. They now
return a 404. This can be tested with the following (missing variable):
```
curl -Ln -bj "http://localhost:3000/C1234208436-POCLOUD/ogc-api-coverages/1.0.0/collections/coverage/rangeset?forceAsync=true&subset=lat(-20:0)&subset=lon(-80:0)&maxResults=1&format=application/x-zarr"
```

HARMONY-1082: Add more specific routing to return 404s for bad URLs

---

workload/locustfile.py

While testing out autoscaling in sandbox I found one query that was not working and wanted to add one more that would cause more pods to spin up.

HARMONY-980: Update a failing workload query and add one additional query

---

app/models/job-link.ts
app/models/job.ts
app/models/work-item.ts

Worked with James and ran a few workload tests in my own sandbox and verified this fixes poor performance and timeouts I had been seeing with polling. In addition we identified deadlocks that we fixed, and identified some slow queries when trying to pull back jobs by request ID and resolved those.
I had to do some clunky things with knex because sqlite does not support skipLocked like Postgres does.

HARMONY-1089: Fix deadlocks with database queries and remove unnecessary locking

---

app/models/job.ts
app/models/work-item.ts
test/work-items/fair-queueing.ts

Do not consider a user as waiting for work on a service if the job associated with any 'ready' work items is in a terminal state. Fixes an issue when jobs are canceled, but not all work items were marked as canceled.
During our regression tests we perform a cancel, and for some reason when we cancel a request it does not always mark all of the work items for that job as canceled (separate bug). This makes sure that if a job is canceled we ignore any work items for that job regardless of their status.

HARMONY-1091: Fixes cases where fair queueing is choosing a user with a canceled job as waiting for work for a service

---

package-lock.json
tasks/giovanni-adapter/app/cli.ts
tasks/giovanni-adapter/app/stac/item.ts
tasks/giovanni-adapter/package-lock.json
tasks/giovanni-adapter/test/cli.ts
tasks/query-cmr/package-lock.json
tasks/service-runner/package-lock.json

1106
This PR fixed a minor issue in `giovanni-adapter` (adding the time properties in the stac item) which was found when testing it in sandbox.
A giovanni request (e.g. the following) should return the giovanni URL successfully.
```
curl -Ln -bj "http://localhost:3000/C1225808238-GES_DISC/ogc-api-coverages/1.0.0/collections/%2FGrid%2FIRprecipitation/coverage/rangeset?format=text%2Fcsv&point=0.76,-3.8&subset=time%28%222020-01-01T00%3A00%3A00Z%22%3A%222020-01-01T03%3A00%3A00Z%22%29&forceAsync=true"
```

Harmony 1106

---

app/backends/workflow-orchestration.ts
fixtures/cmr.uat.earthdata.nasa.gov-443/164806533329363129
package-lock.json
package.json
test/workflow-orchestration.ts

HARMONY-1096
Fixes a scenario where:
1. A work item update comes in
2. There are steps that should be queued after this one
3. But the work item update doesn't provide a catalog
we were just letting the job sit in the running state with no more work items and would never be worked.
This PR changes things to mark the job as failed with a message:
"Harmony internal failure: could not create the next work items for the request"
Note I also updated `ts-node` in this PR as I was trying to get a test plugin working correctly in VS Code.
With James' fix for HARMONY-1093 this will be difficult to reproduce. If you want to test this before James merges his PR in you can delete the query-cmr deployment in your local k8s, submit a request, wait at least 10 minutes for the scroll session to expire, …

HARMONY-1096: Fail a job if the work item update would cause an orphaned job in the running state

---

config/services.yml

[DAS-1372](https://bugs.earthdata.nasa.gov/browse/DAS-1372) (first acceptance criterion).
This PR adds the UMM-C concept IDs for EEDTEST mirror collections of ASF collections (AVNIR, Sentinel 1 Interferograms, UAVSAR) to the HGA service entry in UAT. There's currently not a UMM-S record to enable HGA for our new collections via a UMM-S to UMM-C association (either in an ASF or EEDTEST provider).
Update your Harmony local instance to use the new `service.yml` file. The run the following requests, which should be successful:
```
http://localhost:3000/C1244141281-EEDTEST/ogc-api-coverages/1.0.0/collections/Band1%2CBand2/coverage/rangeset?subset=lat(-.05:0.25)&subset=lon(-51.0:-50.75)&format=image%2Ftiff&granuleID=G1244144597-EEDTEST …
```

DAS-1372 - Add UAT EEDTEST mirrors of ASF collections to HGA.

---

app/frontends/jobs.ts
app/routers/router.ts
app/util/job.ts
test/helpers/jobs.ts
test/jobs/pause-jobs.ts
test/util/job.ts

HARMONY-1130
Adds a resume endpoint for normal users and admin users. 
* Start a long-running (async) job
* Change the state of the job to 'paused' in the database
* Connect to the job status page and verify that the job is paused
* Resume the job using the `/jobs/:jobID/resume` endpoint
* Connect to the job status page and verify that the job is running

Harmony 1130 unpause

---

app/routers/router.ts
app/routers/service-response-router.ts
package-lock.json
package.json

HARMONY-1158
I'm not entirely sure why unhandled promise rejections are now causing our node application to crash, but we've always been handling them incorrectly.
I looked at the express documentation and for asynchronous errors we need to make sure we catch them and then call the next function. Express automatically does that for synchronous code, but not for asynchronous code. We need to wrap all of routes with code that does a try catch and then call next for the error handling in order to make async code work correctly.
When reading this blog post I found there's a simple library (express-async-handler) that does that wrapping - we just need to call it for all of our routes: 
https://javascript.plainenglish.io/node-express-async-error-handling-e12aa693d84d
1. Submit a request for 50 …

HARMONY-1158: Wrap all routes to prevent crashing on asynchronous exceptions

---

.dockerignore
Dockerfile

HARMONY-1161
Harmony in a box with harmony running in k8s was broken by the Node 16 changes. This fixes that. Also I changed the way the Dockerfile was structured to build much faster.
It took 690 seconds the first time I built and every build after that was still taking hundreds of seconds. Now as long as the libraries in package.json do not change it takes 8 seconds to build. If package.json changes and an install needs to run it still completes in 2-3 minutes.
In your .env make sure to not override the defaults for LOCALSTACK_HOST, BACKEND_HOST, and CALLBACK_URL_ROOT so that you can use harmony in a box.
```
npm run build
bin/start-harmony
bin/restart-services
```
After harmony starts up submit a request and verify it is successful.
~* [ ] Tests added/updated (if needed) and passing~ …

HARMONY-1161: Fix harmony running from Docker to work with Node 16 changes

---

config/services.yml

[DAS-1463](https://bugs.earthdata.nasa.gov/browse/DAS-1463)
This PR adds an entry in the production section of `services.yml`, to enable the Trajectory Subsetter in production.  It also adds a reference to an [ORNL UMM-S record](https://cmr.earthdata.nasa.gov/search/services.umm_json?provider=ORNL_CLOUD). This should enable ORNL to activate the Trajectory Subsetter for their collections as soon as this change is deployed to production.
This change can't really be tested locally, as local Harmony uses the UAT content for `services.yml`.
~* [ ] Tests added/updated (if needed) and passing~
~* [ ] Documentation updated (if needed)~

DAS-1463 - Add production services.yml entry for the Trajectory Subsetter

---

app/backends/workflow-orchestration.ts
app/models/job.ts
app/workers/work-failer.ts
fixtures/cmr.uat.earthdata.nasa.gov-443/165099102895369026

HARMONY-1164
We've been seeing some inconsistent job status when several work items complete work for a job around the same time. Sometimes the progress percent would go down and in some instances the status would go back to running when the request should have been successful. When performing a workload run with just a single request going at a time with a random number of granules between 1 and 97 for a harmony-service-example request I would consistently see this error condition where all work items were successful, but the job was still in the running state. I'd usually see it within just a couple of requests from the start of running and never made it past 10 requests.
After this change to make sure the job is locked when updating the status after a work item completes I've been able …

HARMONY-1164: Fix inconsistent job status

---

app/frontends/wms.ts
app/models/services/base-service.ts
app/schemas/ogc-api-coverages/1.0.0/ogc-api-coverages-v1.0.0.yml
test/ogc-api-coverages/get-coverage-rangeset.ts
test/wms/get-map.ts

HARMONY-1133
Adds preliminary support for the `skipPreview` parameter
Issue a query with `skipPreview=true` and see that it doesn't return an error

HARMONY-1133: Add support for the skipPreview parameter

---

app/frontends/jobs.ts
test/helpers/jobs.ts
test/jobs/pause-jobs.ts

HARMONY-1132
Updates the job status page with a link for resuming.
Pause a running job. Navigate to the job status page and take note of the message as well as a link for resuming the job.

Harmony 1132 - job status link for unpausing

---

.eslintrc.yml
app/middleware/admin.ts
app/models/job-link.ts
app/models/job.ts
app/models/work-item.ts
app/server.ts
app/util/job.ts
tasks/giovanni-adapter/app/cli.ts
tasks/giovanni-adapter/test/helpers/cli.ts
tasks/service-runner/app/workers/pull-worker.ts
test/helpers/ogc-api-coverages.ts

HARMONY-1167
We found another instance of an unhandled promise rejection in UAT. I attempted to fix the exact issue that was encountered, but also did a couple of other things to try and prevent other cases.
1.) I turned on the linter rule for no-floating-promises which identifies places in the code where we were not correctly handling promises. It also uncovered bugs where we were not awaiting.
2.) I added code on server start up to add a listener for unhandled rejections and log an error instead of exiting the node process. I tried for awhile to add an automated test for this functionality, but I just could not get anything to work right.
I did manually test that the behavior works as expected.
I don't have a good way to reproduce the exact error encountered, but to verify that node no …

HARMONY-1167: Prevent node process from exiting when there is an unhandled promise rejection

---

docs/Harmony API introduction.ipynb

- Replaces `proj_string` with `l2proj_string` to correctly encode the query string in the l2w *Access Level 2 swath regridded data* section of the notebook. 
- fixes typo `repsonse` with `response`
- Does not reproduce the `example-notebook.html` file since the notebook can't be run to completion currently.

Use correct projection string in l2 example

---

workload/harmony/common.py

HARMONY-1143
Ensure workload requests do not get auto-paused.
Start up harmony locally.
Start up the workload driver:
```
cd workload
<activate your python environment - I use pyenv activate workload>
locust --tags demo
```
Open up the UI using the link from your terminal.
Choose to send 2 concurrent requests to http://localhost:3000
Open http://localhost:3000/jobs
Make sure that all of the requests for jobs started by the workload run include `skipPreview=true`
* ~[ ] Tests added/updated (if needed) and passing~
* ~[ ] Documentation updated (if needed)~

HARMONY-1143: Ensure workload requests do not get auto-paused.

---

config/services.yml

HARMONY-1181
The Swath Projector entry in `services.yml` (and the chained service with the Swath Projector and NetCDF-to-Zarr service) incorrectly specified several output formats that are not supported by the service. This PR removes those output formats.
The [associated UMM-S record](https://cmr.uat.earthdata.nasa.gov/search/services.umm_json?concept_id=S1237974711-EEDTEST) correctly states that the services takes a NetCDF-4 input and produces a NetCDF-4 output.
* In a local Harmony environment try to make a request for a collection that is only configured for use with the Swath Projector.
* Specify a GeoTIFF output format (`format='image/tiff'`).
* The request should just return a direct download link, because there are no services configured for that collection that can offer a …

HARMONY-1181 - Remove GeoTIFF, PNG and GIF output options from the Swath Projector.

---

config/services.yml
test/versions.ts

DAS-1451
This PR adds a chained services that combines the Harmony OPeNDAP SubSetter (HOSS) with MaskFill. This will be used to allow polygon spatial subsetting of geographically gridded data hosted in OPeNDAP. HOSS extracts a minimally encompassing bounding box, and retrieves those data from OPeNDAP. The output is then passed to MaskFill which masks pixels within the bounding box, but outside the polygon.
Another minor addition in this PR is to specify that the Trajectory Subsetter operations includes the `spatialSubset` option. The omission of this entry from the list was preventing shape file information reaching the Trajectory Subsetter.
_This might not work - I've been seeing issues with OPeNDAP hanging for RSSMIF16D requests. I think this relates to HYRAX-744._
* Configure the new …

DAS-1451 - Implement HOSS-MaskFill chained service.

---

app/frontends/ogc-coverages/util/subset-parameter-parsing.ts
test/ogc-api-coverages/subset-parameter-parsing.ts

HARMONY-1192
Adds support for non-alphanumeric characters in dimension names, e.g., '/lev' or 'my lev'.
Issue the following query and verify the result. (Not sure why this query is treated as async when it only has one granule):
```
http://localhost:3000/C1215726323-GES_DISC/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=lat%28-10%3A10%29&subset=lon%28-160%3A-75%29&subset=%2Flev%28800%3A900%29&maxResults=1
```
The job should run and the workflow step in the database should have an operation that includes
```json
"subset":{"dimensions":[{"name":"/lev","min":800,"max":900}
```

HARMONY-1192: Change regexes to support non-alpha characters in dims

---

app/workers/work-failer.ts
test/workers/work-failer.ts

HARMONY-1197
Do not fail work items and jobs that have been in the READY state for more than 4 hours. Only fail for work items that have been in the RUNNING state for more than 4 hours.
1.) Set FAILABLE_WORK_AGE_MINUTES to 1
2.) Submit a request for a service that you do not have deployed locally (so that the work item for that service stays in the READY state).
3.) Wait at least 6 minutes (watch for the job reaper to run in the logs). If in a hurry you can set WORK_FAILER_PERIOD_SEC to 30 to run every 30 seconds instead of 6 minutes.
4.) Verify the job stays in the Running state and is not failed.

HARMONY-1197: Do not fail work items and jobs that have been in the READY state for more than 4 hours.

---

app/backends/workflow-orchestration.ts
app/models/work-item.ts

HARMONY-1200
Changes to fix work requests from returning no data even when work items are available. Should still preserve fair queuing for the most part (best effort, not guaranteed).
* Deploy to sandbox and issue a long-running request
* Verify that the workers are getting work items (no long periods of 'polling for work' in the logs)
* Issue on or more additional short requests
* Verify that the new requests are worked in parallel with the long-running one

HARMONY-1200: Remove jobs table locking when getting work and updating work items

---

app/util/crs.ts
package-lock.json
package.json
test/ogc-api-coverages/get-coverage-rangeset-shapefile.ts
test/wms/get-map.ts

HARMONY-1207
We've had issues with the gdal library not being updated in the past (causing problems with security vulnerabilities and not being able to update our version of nodeJS). Also we have to custom install gdal from source on our Amazon Linux 2 EC2 instances. With the switch to `gdal-async`, which is actively maintained we should be in better shape in the future.
There is additional AXIS information passed in WKT but seems to match the spec:
https://docs.geotools.org/stable/javadocs/org/opengis/referencing/doc-files/WKT.html
```
AXIS["Latitude",NORTH],AXIS["Longitude",EAST]
```
Make sure you have SWOT reprojection built and deployed locally.
`npm install` to update your gdal library (you may have to first remove your node_modules directory)
Submit this request: …

HARMONY-1207: Switch to maintained gdal-async library.

---

app/util/job.ts

Needed to avoid EFS slowness
HARMONY-1185
Removes the code that that deletes work item STAC catalogs from EFS to avoid huge slowdowns when canceling jobs. This code is no longer needed once we move off EFS.
This change does not alter any of the existing use of transactions - that turned out to not be the problem. We probably want to revisit our use of transactions at some point.
* Check out this branch
* Set MAX_GRANULE_LIMIT=200000 in your harmony-ci-cd .env file
* Deploy the branch to the sandbox.
* Issue the following query
```
http://<your deployment redirect url>/1234724470-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?subset=lat(-45%3A45)&subset=lon(0%3A180)
```
* Open the workflow-ui page and click on the job
* Wait about 15 minutes then cancel the job
You …

HARMONY-1185: Remove code that cleans up artifacts from work items.

---

config/services.yml

N/A
POCUMULUS is a provider used by podaac internally for testing. Generally should not be used for services testing.
None

Remove POCUMULUS entries

---

app/frontends/ogc-coverages/describe-collections.ts
app/models/services/base-service.ts
app/util/variables.ts
config/services.yml
test/ogc-api-coverages/describe-collections.ts

HARMONY-1206
When a service.yml service entry has a collection and that collection lists the variables it can use, restrict the list of OGC collections (variables) to the variables in the collection entry when describing the collection. 
* Run Harmony locally then execute the following query
```
curl -Ln -bj "http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections"
```
You should see several variables listed.
* Edit `services.yml` and add the following to the  `C1233800302-EEDTEST` collection under the UAT harmony-service-example
```
variables:
- V1233801717-EEDTEST
```
* Restart Harmony to pick up the changes to services.yml
* Rerun the query above - you should see only the V1233801717-EEDTEST variable returned.

HARMONY-1206: Restrict variables returned for described collections when defined in services.yml

---

app/backends/workflow-orchestration.ts
test/ignore-errors.ts
test/jobs/jobs-status.ts
test/workflow-orchestration.ts

HARMONY-1242
Fixes an issue with the job message not displaying the error returned by a backend service when there is a failure.
In UAT this request displays a generic message for the error:
https://harmony.uat.earthdata.nasa.gov/C1244141250-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=lat(32.95%3A33.09)&subset=lon(-115.45%3A-115.15)&maxResults=1
`message: "The job failed with an unknown error"`
Build the harmony-gdal-adapter and include it in your LOCALLY_DEPLOYED_SERVICES.
Submit the request and ensure the job message includes the error message returned by the backend service:
http://localhost:3000/C1244141250-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=lat(32.95%3A33.09)&subset=lon(-115.45%3A-115.15 …

HARMONY-1242: Set job status failure message to the message returned by the backend service

---

app/frontends/workflow-ui.ts
app/models/job.ts
app/views/workflow-ui/jobs/index.mustache.html
app/views/workflow-ui/jobs/jobs-table.mustache.html
test/workflow-ui/jobs.ts

harmony-1140
Both the user and admin workflow-ui endpoints now allow sorting based on the number of input granules.
Try it out by clicking one of the arrow buttons. You can sort ascending or descending. Click the same button again to unapply the sort.

Harmony 1140 - Add buttons for sorting jobs by number of input granules

---

tasks/service-runner/app/service/service-runner.ts

harmony-1255
We were unable to parse the access token successfully in the query CMR task due to unnecessary stringification.
Rebuild query cmr and restart services. Issue a request and log the access token in query.ts. (Inspect the query cmr worker logs.)

HARMONY-1255: Don't stringify data operation for query-cmr

---

app/backends/workflow-orchestration.ts
test/work-items/work-backends.ts

HARMONY-158
Fixes bug that allowed updates to work-items when the job or work item was already in a terminal state. This could
cause problems for retried work-items if an older work-item run finished after a subsequent retry (due to say a timeout).

HARMONY-158: Reject work-item updates when job or work-item are in terminal state

---

app/util/metrics.ts
test/util/metrics.ts

HARMONY-1256
The metrics team has asked us to set the user_ip string to a blank string rather than omit the value in able to make their parsing easier.
Set TEXT_LOGGER=false in your .env and then submit a request. Verify in your logs for the request metric that you see the blank user_ip:
```
{... , "message":"Request metric for request ...", ... "user_ip":""}
```

HARMONY-1256: Always set the user_ip to a blank string in the request metrics

---

.nsprc
app/backends/workflow-orchestration.ts
app/models/work-item.ts
db/knexfile.js
db/migrations/20220819112559_fix_work_item_polling_indices.js
package-lock.json
test/work-items/fair-queueing.ts

HARMONY-1264
While testing in my sandbox environment I found several database performance issues when issuing a single request for 230K granules.
1.) We were timing out polling for work from the database at 1 second, but the query kept running in the background.
2.) We only allowed 7 concurrent connections causing blocking for requests trying to get info from the database (polling, workflow-ui, job status, etc)
3.) The fair queueing policy queries needed to be tweaked to improve performance (I was seeing them average over 70 seconds to complete).
4.) I added an index for a query on service ID and work item status because I saw the query plans doing table scans when querying on those two fields. I do not actually have evidence that this index improved the performance, but now I'm rarely …

HARMONY-1264: Fix performance bottlenecks with polling for work.

---

app/backends/service-metrics.ts
app/routers/service-response-router.ts
tasks/service-runner/app/workers/pull-worker.ts
tasks/service-runner/test/pull-worker.ts
test/service-metrics-backends.ts

HARMONY-1243
Cleans up /tmp (skipping WORKNG or TERMINATING files) before pulling new work to keep long-running pods from
running out of disk space. Also changes HPA metric to include running work items in counts.
1. build the service-runner (`npm run build` in `tasks/service-runner`) image and restart services. 
2. open a terminal on a worker or manager for a service using `kubectl` or `k9s`
3. make a query that invokes that service
4. run `ls /tmp` to see files/directories being created in `/tmp`.
5. after the job completes, run `ls /tmp` again to verify that files/directories have been deleted.
6. optionally use `df -h` to see the disk space at various times. It may take a while after the service completes to see the freed disk space show up

HARMONY-1243: Clean up worker artifacts to prevent pod disk space issues

---

app/middleware/cmr-granule-locator.ts
app/models/services/base-service.ts
config/services.yml
env-defaults
test/concatenation.ts
test/ogc-api-coverages/get-coverage-rangeset.ts

HARMONY-276
Bumps up the system granule limit to 10 million (more than the number of granules in any collection supported by harmony).
Ran into issues testing with concatenation and netcdf-to-zarr (even with as few as 20 granules), so changed all zarr service chains to not concatenate by default (though users can still request concatenation by passing in the parameter).
Based on testing we'll continue to limit Concise to no more than 350 granules. I ran a test successfully with 580 granules, but ran out of ephemeral storage space with 600 granules. We'll work on a fix for that next PI.
Try out:
http://localhost:3000/C1234724470-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?format=application%2Fnetcdf&concatenate=true and verify it limits it to 350 granules with a …

HARMONY-276: Effectively remove the system granule limit.

---

config/services.yml

Adding ORNL version of gdal-adapter service to UAT:
https://cmr.uat.earthdata.nasa.gov/search/services.umm_json?provider=ORNL_CLOUD&native-id=harmony-gdal-adapter

add ORNL harmony-gdal-adapter service to UAT

---

docs/Harmony Feature Examples.ipynb
env-defaults

HARMONY-799
I tested out all the notebooks in this repo and in harmony-py now that we've raised the granule limit. I did not run into any issues with requests attempting to retrieve a large number of granules. The only change I made was to cancel out the two requests that are left in a paused state after previewing with 176 granules each.
Also sets the CMR page size back to 2000 for best performance.
You can run the individual notebooks to verify they do not make large requests (or take a look at my requests using the admin page on the workflow-ui to verify I did not kick off any large requests as a result of my testing today).

HARMONY-799: Make sure to cancel out paused requests from notebook

---

app/backends/service-metrics.ts
app/models/work-item.ts
app/routers/service-response-router.ts
test/service-metrics-backends.ts

HARMONY-1237
Our metrics for our pod autoscalers to decide how many work items were ready for work include paused and previewing jobs meaning we were spinning up pods for work items that were not ready to be picked up (or in the case of previewing we only want one item to be worked). Remember that we always have one pod up for each service so the previewing jobs will still have a work item worked even with the metrics reporting that there are no work items available.
With indefinitely paused jobs (which we see a lot in UAT and production) this meant we always had pods running which had no work to pick up.
1. Run `bin/deploy-hpa` to deploy the HPAs to your local k8s cluster.
2. Submit a large request for > 100 granules.
3. Observe the HPA metrics show that it recognizes there are more than …

HARMONY-1237: Metrics for returning number of available work items to pick up take the job status into account.

---

app/frontends/jobs.ts
app/frontends/stac.ts
app/middleware/cmr-granule-locator.ts
app/models/job.ts
app/models/services/base-service.ts
app/models/services/no-op-service.ts
app/models/services/turbo-service.ts
app/util/links.ts
test/helpers/data-operation.ts
test/helpers/jobs.ts
test/helpers/turbo-service.ts
test/jobs/auto-pause-jobs.ts
test/jobs/cancel-jobs.ts
test/jobs/jobs-status.ts
test/jobs/message.ts
test/jobs/pause-jobs.ts
test/jobs/skip-job-preview.ts
test/models/job.ts

HARMONY-1172
When a job is paused and then resumed it should now always retain the original results limited message. 
~I am not totally in love with the ultimate solution but I wanted to avoid making a major change given that our job messages and associated logic seems like it is reaching a pretty stable point.~
Refactored the job message logic to pull from a map of messages. Made some changes to job serialization as well that hopefully simplify things.
http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?maxResults=2
Pause and resume the job. Does the message look OK (are relevant parts, e.g. results limited messaging, retained after resumption)?

Harmony 1172 - Retain original results limited message after resuming job

---

Dockerfile

-------
None
I'm not sure what changed, but the node:buster-16 image that is downloading now errors when I'm trying to build harmony.
in the docker build step I see output
=> ERROR [ 2/11] RUN apt update && apt-get install sqlite3        4.4s
and
#5 4.362 Do you want to continue? [Y/n] Abort.
You should be able to run `nvm use && npm i && npm run build` successfully

agree to installing sqlite3

---

.nsprc
app/backends/workflow-orchestration.ts
app/models/job.ts
fixtures/cmr.uat.earthdata.nasa.gov-443/166326376631952362
fixtures/cmr.uat.earthdata.nasa.gov-443/166326376654863707
tasks/service-runner/app/workers/pull-worker.ts
test/ignore-errors.ts
test/workflow-orchestration.ts

HARMONY-1266
Changes the way harmony determines the number of granules to request back from the CMR for each query-cmr task to only database queries without having to potentially read many files from S3 to determine how many granules are left to process.
Set CMR_MAX_PAGE_SIZE to a small number like 3 and submit a request that will cause multiple calls to CMR to execute. Make sure the last page size should be something other than CMR_MAX_PAGE_SIZE to verify the calculation is correct for the last item.
For example with 3 I might request 8 granules back which results in 3, 3, and 2 items for the 3 query-cmr requests. Here's an example request:
http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?subset=lat(20%3A80)&subset=lon(-140%3A0)&outputCrs …

HARMONY-1266: Reduce database locking time for query-cmr work items

---

package-lock.json
tasks/service-runner/Dockerfile
tasks/service-runner/package-lock.json

HARMONY-1259
Changes service runner Docker file to not create the `node` user. This forces things to run as `root`, which is not great,
but seems like the best solution to allow us to clean up the shared mount point at /tmp. This was failing because
the worker images often use `root` as the user, so files written out are owned by root and can't be cleaned up on the
manager by the `node` user.
1. Rebuild the service-manager (npm run build in tasks/service_manager)
2. use kubectl or k9s to connect to the manager container
3. verify that the manager is running as root
4. Execute some harmony queries to make sure they still work

HARMONY-1259: Change service runner to run as root so /tmp cleanup works

---

app/backends/service-invoker.ts
app/models/services/base-service.ts
app/models/services/no-op-service.ts
app/util/metrics.ts
test/util/metrics.ts

HARMONY-1285
Track the user IP address in request metrics
I looked at Kibana logs in SIT, UAT, and Production after hitting some harmony endpoints. I found my IP address logged in the req['headers']['x-forwarded-for'] field. That field was a string with 3 comma separated IP addresses with the first being my own in each example I looked at. Unfortunately we do not use CloudFront in sandbox or locally and so I have no real way to test this PR until it gets to SIT.

HARMONY-1285: Track the user IP address in request metrics

---

app/util/object-store.ts
tasks/giovanni-adapter/tsconfig.json
tasks/query-cmr/tsconfig.json
tasks/service-runner/tsconfig.json
tsconfig.base.json
tsconfig.json

HARMONY-1248
Handle output files with spaces in the output filename.
Test the request from the ticket:
http://localhost:3000/C1215720341-GES_DISC/ogc-api-coverages/1.0.0/collections/%2FHDFEOS%2FSWATHS%2FOMI%20Total%20Column%20Amount%20SO2%2FData%20Fields%2FCloudFraction/coverage/rangeset?forceAsync=true&subset=lat(-80%3A80)&subset=lon(-180%3A180)&maxResults=1
First test from main and verify you get a 404 when trying to retrieve the output file. Then start harmony from this branch and verify you can retrieve the output file and it opens fine in Panoply.

HARMONY-1248: Handle output files with spaces in the output filename

---

app/models/services/base-service.ts
bin/update-harmony
config/services.yml
test/versions.ts

DAS-1608
This PR makes better use of conditions for chained service steps such that DAACs need only associate against one service per collection for HOSS:
* sds/HOSS-geographic - For L3/L4 data with a geographic grid.
* sds/HOSS-projection-gridded - For L3/L4 data with a non-geographic grid.
* sds/variable-subsetter - For non-gridded collections that still want variable subsetting only.
One thing this PR does not do is remove duplicated UMM-S entries for these services. I'll contact the UMM-S record curators involved to allow them to decide what they want to do with their records.
* Build the Harmony image: `npm run build`. (There are a couple of necessary tweaks to Harmony itself, too)
* Run `./bin/bootstrap-harmony` to start a local instance of Harmony.
* Run through …

DAS-1608 - Update HOSS entries in services.yml.

---

tasks/service-runner/app/service/service-runner.ts
tasks/service-runner/app/workers/pull-worker.ts
tasks/service-runner/test/service-runner.ts
test/helpers/log.ts

HARMONY-1204
We were logging JSON service logs improperly in the service runner. This was causing the nesting of a message attribute within a message attribute, 
```json
{
"stream": "stdout",
"env_name": "harmony-unknown",
"level": "debug",
"message": {
"application": "/home/harmony_service_example/__main__.py",
"level": "INFO",
"message": "timing./home/harmony_service_example/__main__.py.start",
"requestId": "95640a9c-8fd1-413d-b9c8-b59ea322194b",
"timestamp": "2022-10-05T15:21:22.243421Z",
"user": "vinverso"
},
"timestamp": "2022-10-05T15:21:22.244Z",
"worker": true,
}
```
which was tripping up the metrics team's log parser which expects `message` to be of type `string` (not `object`). This PR fixes that by changing the way we pass a _JSON_ log to the winston logger. …

Harmony 1204 - Handle JSON service logs properly

---

app/frontends/workflow-ui.ts
app/models/job.ts
app/views/workflow-ui/job/index.mustache.html
app/views/workflow-ui/job/work-item-table-row.mustache.html
app/views/workflow-ui/job/work-items-table.mustache.html
public/js/workflow-ui/job/index.js
test/workflow-ui/work-items-table-row.ts
test/workflow-ui/work-items-table.ts

HARMONY-1304
This ensures that when a user has inadequate permissions to view the logs or retry button(s) on the workflow UI, the corresponding columns will be hidden. Previously we were just hiding the buttons, but not also the columns. This was confusing, e.g. for a user who will never see the logs button but does see a column header named "logs".
Submit a job (as an admin or non-admin, http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?maxResults=2), then login to harmony with a different non-admin user and take a look at the other user's job. Make sure that there is no "logs" and no "retry" column.

Harmony 1304 - Hide retry and logs columns when functionality is inaccessible due to permissions

---

app/backends/workflow-orchestration.ts
app/frontends/request-metrics.ts
app/models/work-item.ts
app/util/job.ts
app/util/metrics.ts
package-lock.json
test/util/metrics.ts

HARMONY-1286
Log the total output size as part of the response metric so that the metrics dashboards capture the size reduction for a request.
I tested with both Postgres and Sqlite. I set the CMR_MAX_PAGE_SIZE to 3 so that multiple query-cmr steps would be generated for my request.
Make sure TEXT_LOGGER=false.
Submit a request for more than CMR_MAX_PAGE_SIZE granules. When the request completes look for a log message for the response metric:
It should look similar to:
```
{"application":"backend","env_name":"harmony-local","http_response_code":200,"job_ids":["3dc34c5a-b52d-43a3-979a-f3529a1d872b"],"level":"info","message":"Job 3dc34c5a-b52d-43a3-979a-f3529a1d872b complete - response metric","original_size":4.20245361328125,"output_size":0.16964244842529297,"requestId":"work","requestUrl": …
```

HARMONY-1286: Log the total output size as part of the response metric

---

README.md

HARMONY-1311
Updated README with instructions for running Harmony development on M1 Macs
Follow the README on an M1 Mac for local development and verify that Harmony runs correctly

HARMONY-1311: Add instructions for doing Harmony development on M1 Macs

---

config/services.yml
test/versions.ts

GDDS-460
This PR migrates the NetCDF-to-Zarr service chains so they are at the bottom for each environment. This was because some requests were being misdirected to the NetCDF-to-Zarr service instead of HOSS (a request that only specified a temporal subset).
* Reload the updated `services.yml` file using `bin/reload-services-config` script.
* Run the requests below (they should complete successfully if you have the latest images for each service).
* Check the `/workflow-ui` endpoint to ensure that the second step in both chains matches the expected value.
```
http://localhost:3000/C1215802944-GES_DISC/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?subset=time(%222019-03-02T00%3A00%3A00%22%3A%222019-03-02T01%3A59%3A00%22)&maxResults=1 …
```

GDDS-460 - Move NetCDF-to-Zarr service chains below others.

---

app/models/work-item.ts
app/workers/work-failer.ts
test/models/work-item.ts

HARMONY-1317
For work item timeouts, this change ensures that at least 2 items complete before calculating the smart timeout threshold, otherwise it will return the default timeout threshold.
Follow steps from https://github.com/nasa/harmony/pull/266 and also log the `computeWorkItemDurationOutlierThresholdForJobService` logic to see if the computation is working as expected.

HARMONY-1317: Ensure 2 items complete before calculating smart timeout threshold

---

test/aggregation-batching.ts
test/helpers/env.ts

HARMONY-1274
Adds tests to verify that batching for aggregation services obeys configuration set in services.yml
* add `max_batch_inputs: 3` after line 613 in services.yml
* restart harmony
* Issue the following request
```
http://localhost:3000/C1234208438-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?skipPreview=true&maxResults=7&concatenate=true
```
* Verify using the workflow-ui that the job has three concise work items
* Use the following SQL query to verify that there were seven batch_items created in three batches
```sql
select * from batch_items;
```

HARMONY-1274: Add tests that batching obeys services.yml configuration

---

app/backends/workflow-orchestration.ts
app/models/batch-item.ts
app/models/workflow-steps.ts
app/util/aggregation-batch.ts
test/helpers/work-items.ts
test/ignore-errors.ts

HARMONY-1280
Updates batched aggregrations to be able to run successfully even if some items in prior steps fail or if some of the batched aggregations themselves fail when the user has requested `ignoreErrors=true`.
I've tested in the sandbox quite a bit with large requests with several failing items and verifying in the end the batched aggregations are created correctly and complete successfully.
Submit the following request which has one successful and two failing granules:
http://localhost:3000/C1234208438-POCLOUD/ogc-api-coverages/1.0.0/collections/bathymetry/coverage/rangeset?concatenate=true&subset=lon(-160%3A160)&subset=lat(-80%3A80)&maxResults=3&skipPreview=true&ignoreErrors=true&granuleId=G1234495188-POCLOUD,G1234515613-POCLOUD,G1234515574-POCLOUD,G1234516982-POCLOUD,G1234518216- …

HARMONY-1280: As a harmony user, I want my aggregation request to be able to complete even if some items fail

---

app/backends/workflow-orchestration.ts

HARMONY-1280
There was an issue with one of the changes made for a review comment that caused status to not be what was expected.
Run the same request as the original PR and verify it eventually completes with errors ending with a successful concise work item which contains one granule. You can set `WORK_ITEM_RETRY_LIMIT=0` to speed things up.
http://localhost:3000/C1234208438-POCLOUD/ogc-api-coverages/1.0.0/collections/bathymetry/coverage/rangeset?concatenate=true&subset=lon(-160%3A160)&subset=lat(-80%3A80)&maxResults=3&skipPreview=true&ignoreErrors=true&granuleId=G1234495188-POCLOUD,G1234515613-POCLOUD,G1234515574-POCLOUD,G1234516982-POCLOUD,G1234518216-POCLOUD,G1234518228-POCLOUD,G1236679413-POCLOUD

HARMONY-1280: Fix issue with inconsistent status and workItem.status.

---

app/frontends/workflow-ui.ts
app/models/harmony-request.ts
app/routers/router.ts
test/workflow-ui/jobs.ts

HARMONY-1319
We had a bug when visiting the workflow-ui page that if the URL used was workflow-ui/ the job links that were generated were all incorrect with a double workflow-ui/workflow-ui in them. This fixes the issue by redirecting from workflow-ui/ to workflow-ui and admin/workflow-ui/ to admin/workflow-ui.
Submit at least one job in your local environment.
Navigate to http://localhost:3000/workflow-ui/ and verify you are redirected to http://localhost:3000/workflow-ui.
Click on the link to open the details for your job and verify that it takes you to the work items page for that job instead of a broken 404 link.
Repeat the same for http://localhost:3000/admin/workflow-ui/

HARMONY-1319: Redirect when workflow-ui routes end in a slash

---

.gitignore

HARMONY-369
Remove serverless from .gitignore since we do not use serverless.
Check out this branch. Verify that you do not have a .serverless directory reported as untracked changes.

HARMONY-369: Remove serverless from .gitignore.

---

app/frontends/ogc-coverages/util/subset-parameter-parsing.ts
app/models/data-operation.ts
app/util/metrics.ts
test/ogc-api-coverages/subset-parameter-parsing.ts

HARMONY-611
The temporal field was constructed using strings sometimes and Dates sometimes. This PR changes it to always use strings simplifying some logic.
Set TEXT_LOGGER=false
Submit a request that has temporal subsetting and verify it completes successfully: http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/blue_var/coverage/rangeset?subset=lat(-5%3A5)&subset=lon(-10%3A10)&subset=time(%221902-07-31T00%3A00%3A00.000Z%22%3A%222020-08-31T10%3A00%3A00.000Z%22)&maxResults=2
Verify that the temporal range is logged correcting in the logs within the operation field:
```
"temporal":{"end":"2020-08-31T10:00:00.000Z","start":"1902-07-31T00:00:00.000Z"}
```

HARMONY-611: Ensure the data operation temporal field always uses strings

---

package-lock.json
package.json

HARMONY-1269
Until this fix https://github.com/kubernetes-client/javascript/pull/890 becomes available, this PR should resolve the "missing types" error we encounter in bamboo ("error TS2688: Cannot find type definition file for 'ws'"). Look at the Bamboo logs for recent harmony service builds and search for "ws" -- you will see the aforementioned error. 
Note that this was reproducible locally for me as well but not for James.
Remove `node_modules` for harmony and service-runner
`npm install` in the project root directory
`cd tasks/service-runner`
`npm run build` (should finish without issues)

HARMONY-1269: Add missing ws types

---

.gitignore
app/backends/workflow-orchestration.ts
app/util/job.ts

HARMONY-1347
I saw database deadlocks when canceling large requests that had many active pods polling for work. This PR changes things so that we query the tables in the same order when polling for work and canceling a request to prevent deadlocks.
I tested this out in my sandbox. I reproduced the problem and then deployed the code change and verified the request canceled without problem even with 50 active pods polling for work. You can regression test canceling requests locally.

HARMONY-1347: Fix deadlock issue when canceling requests

---

README.md
app/frontends/ogc-coverages/get-coverage-rangeset.ts
app/models/data-operation.ts
app/models/job.ts
app/models/services/base-service.ts
app/models/services/no-op-service.ts
app/schemas/ogc-api-coverages/1.0.0/ogc-api-coverages-v1.0.0.yml
db/db.sql
db/migrations/20230123180001_add_destination_url_to_jobs.js
package-lock.json
tasks/service-runner/package-lock.json
test/destination-url.ts

HARMONY-1214
Add destinationUrl parameter to harmony api. This is the first step of adding support of user specified s3 destination url. It only saves the provided destinationUrl in the jobs table. Followup tickets will add support for validations and staging using the destination url.
curl -Ln -bj "http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?granuleId=G1233800343-EEDTEST&destinationUrl=s3://dummy" -o ~/Downloads/output.tif
and verify the request completes successfully and the `destination_url` field in jobs table is populated with `s3://dummy` as indicated in the request parameter.

HARMONY-1214: Add destinationUrl parameter to harmony api.

---

test/destination-url.ts

HARMONY-1222
As a user, I want a file to be placed in my bucket that includes a link to the job status URL for this request, so I can track the status.
Since the code to push a file named `harmony-job-status-link` under `<destinationUrl>/<harmony-request-id>` with the jobs status link as its content has already been added as part of HARMONY-1217. This PR just adds the test to verify the content of the `harmony-job-status-link` file.
This has to be tested outside of local stack. e.g.
http://internal-harmony-yliu10-frontend-xxx.us-west-2.elb.amazonaws.com/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?granuleId=G1233800343-EEDTEST&format=image%2Fpng&destinationUrl=s3%3A%2F%2Fyliu10-harmony-sandbox-staging/public
Then verify …

HARMONY-1222: Add job status link file to user specified s3 destinationUrl location.

---

app/models/job.ts
test/destination-url.ts
test/stac/stac-item.ts

HARMONY-1221
Removes the data expirations fields from the status page and the STAC items if the destinationUrl parameter is set
1. Create a custom staging bucket in localstack
aws --endpoint-url=http://localhost:4566 s3 mb s3://my-staging-bucket
2. Check out this branch
3. Run harmony
4. Issue the following query
http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/blue_var/coverage/rangeset?format=image%2Fpng&granuleName=001_*&destinationUrl=s3%3A%2F%2Fmy-staging-bucket
5. Verify that the status page does not have the `dataExpiration` field
6. When the job is finished, refresh the status page then follow the link to the STAC catalog. Append '/0' to the url of the STAC catalog to get the first STAC item back. Verify that the timestamps do not include an 'expires' …

HARMONY-1221: Remove dataExpiration from job status and expire from STAC item when destinationUrl is set

---

app/models/services/base-service.ts
app/util/string.ts
bin/start-postgres-localstack
test/jobs/message.ts

HARMONY-1220
When a user requests an S3 destinationUrl for a request the message field in the job status indicates that the storage is external to harmony.
Add the `destinationUrl` param to a request and make sure the job message says something about the storage being external to harmony.
Note this will only be for JobStatus.RUNNING,SUCCESSFUL.

HARMONY-1220: Note that results are outside of Harmony's control

---

config/services.yml

N/A
This PR adds a reference to a new UMM-S record for HGA in production (there previously wasn't one). This will enable DAACs to associate collections with this UMM-S record, and not need to include them in `services.yml` directly.
* This cannot be directly tested outside of production prior to deployment.
* A sanity check would be to ensure there isn't a typo in the UMM-S concept ID by using the following query:
```
https://cmr.earthdata.nasa.gov/search/services.umm_json?concept_id=<concept ID copied from PR>
```
* ~~Acceptance criteria met~~
* ~~Tests added/updated (if needed) and passing~~

Add production UMM-S record for HGA.

---

app/frontends/jobs.ts
app/models/job.ts
app/models/services/base-service.ts
test/helpers/job-status.ts
test/models/services.ts

HARMONY-1357
This PR completes the normal workflow of putting OGC request results in the user specified s3 bucket.
Changes made:
1. Changed normal workflow orchestration to put intermediary results in the artifacts bucket rather than the staging bucket so that the intermediary results are not leaked to the client user. The existing naming convention of intermediary results remains the same. e.g. `s3://local-artifact-bucket/public/podaac/l2-subsetter-concise/0b6a7a69-2084-4265-bfd7-02f92f3f5cb6/315/JA1_GPS_2PeP220_111_20071231_005214_20071231_014826_bathymetry_subsetted.nc4`.
2. Changed normal workflow orchestration to put the final result in the staging bucket using a new naming convention: `<stagingLocation>/public/<jobId>/<stepId>/...`.
3. When destinationUrl is present, put the final …

HARMONY-1357: As a Harmony user I want to store my results in my own S3 bucket.

---

app/middleware/parameter-validation.ts
test/destination-url.ts

HARMONY-1219
Added detailed error message regarding s3 bucket setup and link to get the bucket policy to relevant s3 bucket validation errors.
Must be tested outside of localstack. e.g.
- No permission to get bucket location:
http://internal-harmony-yliu10-frontend-xxx.us-west-2.elb.amazonaws.com/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?granuleId=G1233800343-EEDTEST&format=image%2Fpng&destinationUrl=s3%3A%2F%2Fyliu10-no-permission%2Fabc
- No write permission to the bucket location:
http://internal-harmony-yliu10-frontend-xxx.us-west-2.elb.amazonaws.com/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?granuleId=G1233800343-EEDTEST&format=image%2Fpng&destinationUrl=s3%3A%2F%2Fyliu10-sit-no-write-permission-test%2Fabc

HARMONY-1219: Added detailed error message regarding s3 bucket setup and link to get the bucket policy.

---

app/models/job-error.ts

HARMONY-1369
This is a follow up to a bug fix that did not completely address all  of the underlying issues https://github.com/nasa/harmony/pull/336. The initial bug fix truncated the job error message before saving in order to avoid exceeding the postgres column limits. However, under these particular failure conditions, there was also another database record (`job_error`) being saved which had a `message` field that was not being truncated to adhere to its column character limits of 4096.
In [workflow-orchestration.ts#L494](https://github.com/nasa/harmony/blob/main/app/backends/workflow-orchestration.ts#L494), set this outer if statement to `true` so that it always triggers -- otherwise you might not be able to simulate the original conditions seen in production, which require …

HARMONY-1369: Truncate job-error message before saving

---

app/frontends/stac-catalog.ts
test/stac/stac.ts

HARMONY-1383
Adds a type field with a value of 'Catalog' to the STAC catalog returned in the harmony job results when a request is completed.
This fixes a bug when trying to open a catalog using Pystac client.
Start harmony locally and submit a request (must be async so that a catalog will be created in the end). For example http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/blue_var/coverage/rangeset/?subset=lat(20%3A60)&subset=lon(-140%3A-50)&granuleId=G1233800343-EEDTEST&outputCrs=EPSG%3A31975&format=image%2Fpng&forceAsync=true
Set up a python environment and then:
1. `pip install pystac_client`
2. `python`
3. `from pystac_client import Client`
4. `catalog = Client.open('http://localhost:3000/stac/<request_id>')`
5.  Verify no errors from the open command.
6. …

HARMONY-1383: Add type of Catalog to the STAC catalog generated for harmony requests

---

README.md
app/views/workflow-ui/job/index.mustache.html
test/workflow-ui/job.ts

HARMONY-1352
Updated README based on provider feedback.
Added job status link to workflow ui jobID.
Verify README file is updated with `End of Linux Only` for the section that is only Linux related.
Run Harmony locally, submit a request and verify the `(Job Status)` in the job details page is now a link to the job's status page and click on it lead the user to the job's status page.

HARMONY-1352: Added job status link to workflow ui jobID; Updated README based on provider feedback.

---

app/util/env.ts
app/util/version.ts
env-defaults

HARMONY-619
Add env var for release version to be used in web pages.
1. check out this branch
2. set RELEASE_VERION to 1.0.0 in your .env file
3. run harmony locally
4. load  http://localhost:3000
5. verify that the bottom of the page shows version 1.0.0

HARMONY-619: Add env for release_version for use in web pages

---

.nsprc
tasks/service-runner/.nsprc
tasks/service-runner/app/service/service-runner.ts
tasks/service-runner/app/workers/pull-worker.ts
tasks/service-runner/test/service-runner.ts

HARMONY-1394
Updated service termination without error message failure message to be more user friendly.
Configure local harmony to talk to CMR PROD to reproduce the error easier. 
Note: you need to re-build the service-runner image and restart local services.
To make the request fail faster, add `WORK_ITEM_RETRY_LIMIT=0` to your .env file.
Verify `http://localhost:3000/C2251464384-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&maxResults=1000000&skipPreview=true&subset=lat(-90%3A90)&subset=lon(-180%3A180)&granuleId=G2634017742-POCLOUD` will result in error like:
`WorkItem [1286] failed with error: podaac/l2ss-py:2.4.0: Service failed due to running out of memory` 
rather than 
`WorkItem [1286] failed with error: podaac/l2ss-py:2.4.0: Unexpected token ' …

HARMONY-1394: Updated service termination without error message failure message to be more user friendly.

---

app/frontends/capabilities.ts
test/collection-capabilities.ts

HARMONY-1401
Adds support for the version parameter on the collection capabilities endpoint. As we make changes to the response format, we do NOT want to break clients relying on an older version of the response.
Right now there's only a single version 1 supported. Will be more useful to compare once version 2 is added, but you can still sanity check the parameter is handled correctly:
* No version specified returns the current version: http://localhost:3000/capabilities?collectionId=C1225776654-ASF
* You can explicitly specify the version: http://localhost:3000/capabilities?collectionId=C1225776654-ASF&version=1
* If you specify a version that does not exist you get a 400 error back:  http://localhost:3000/capabilities?collectionId=C1225776654-ASF&version=bad

HARMONY-1401: Support the version parameter on the collection capabilities endpoint

---

db/knexfile.js
db/migrations/20230328193141_add_function_update_timestamp.js
db/migrations/20230328194902_add_update_trigger_to_tables.js

HARMONY-1404
Adds trigger to Postgres to set updatedAt to the current time when a row is updated. This trigger is set for all tables.
1. checkout this branch (harmony-1404-updatedAt)
2. run the migrations
3. Run harmony locally
4. Verify that harmony queries still work
5. Use dbViz to select a row from the `jobs` table
6. Use dbViz to insert a row into the `user_work` table using the `jobID` from the row in `jobs`
7. Use dbViz to select the row from `user_work` (there should be only one row in the table)
8. Use dbViz to update the row by setting `ready_count` to some value.
9. Select the row again and verify that `updatedAt` has been updated.
10. (optional) try updating rows for other tables, e.g., `jobs` and verify that `updatedAt` get set to the current time
NOTE: there are no automated …

HARMONY-1404: Add trigger to tables to set updatedAt when row is updated

---

app/backends/workflow-orchestration.ts
app/models/work-item.ts
app/util/env.ts
app/workers/work-failer.ts
env-defaults
test/workers/work-failer.ts

HARMONY-1403
This PR changed how work failer processes expired work items. Rather than retrieving all expired work items into memory at once (which caused OOM error in PROD), the new approach retrieves the expired work items in a configurable batch size and processes all the expired work items in batches. 
It eliminated the unnecessary processing summary that does nothing but asking for trouble for large payload.
It also eliminated the unnecessary retrieval of jobID step that was executed for each expired work item in the processing.
Reproduced the PROD OOM problem in Sandbox and verified the fix worked in `harmony-yliu10-cluster`(http://internal-harmony-yliu10-frontend-1281553417.us-west-2.elb.amazonaws.com).
NOTE: James's recent code change to add trigger on `updatedAt` made it …

HARMONY-1403: Work failer crashes Harmony when number of work items is too high.

---

package-lock.json
tasks/giovanni-adapter/package-lock.json
tasks/query-cmr/package-lock.json
tasks/service-runner/package-lock.json

DAS-1746 (well, it's a discovered while testing kind of thing)
@flamingbear and I have made a couple of changes to the `harmony-regression-tests` repository. Currently, testing in Bamboo is blocked because the main Harmony repository doesn't pass `npm audit`, and so the main Harmony build plan fails. This PR commits changes to the `package-lock.json` for Harmony, `query-cmr`, `service-runner` and `giovanni-adapter` to try and fix up those audit issues.
* Build Harmony locally.
* Ensure Harmony runs locally.
* ~~Acceptance criteria met~~
* ~~Documentation updated (if needed)~~

DAS-1746 - Update package-lock.json with npm audit fixes.

---

app/models/data-operation.ts
app/models/services/index.ts
config/services.yml
fixtures/cmr.uat.earthdata.nasa.gov-443/168019939864260976
test/models/data-operation.ts
test/models/services.ts

HARMONY-1413
Add the ability to specify a service supports temporal subsetting. When a request includes a temporal range first attempt to match to those services that support temporal subsetting. If no service can be found that supports everything in the request then relax the condition to not require a service that supports temporal subsetting similar to the way we handle spatial subsetting.
Verify that http://localhost:3000/C1245618475-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=time(%222020-01-01T00%3A00%3A00%22%3A%222020-01-31T23%3A59%3A59%22)&maxResults=1 goes to the HOSS service instead of the regridder service (note it looks like there's an association missing for this collection right now to the regridding service - need to get that in …

HARMONY-1413: Add temporal subsetting capability matching

---

docs/guides/develop.md
env-defaults

HARMONY-1446
Changes the defaults for the queue urls in env-defaults to work with Harmony in a box
1. Check out this branch
2. run `npm run build` to build the harmony image
3. run `./bin/start-harmony`
4. verify that harmony is running using `kubectl get pods -n harmony`
5. Execute a query using curl  or Insomnia against localhost:3000

HARMONY-1446: Change defaults for queue urls to work with Harmony in a box

---

app/frontends/stac.ts
app/models/job.ts
app/routers/router.ts
package-lock.json
test/helpers/stac.ts
test/jobs/job-sharing.ts
test/stac/stac-item.ts
test/stac/stac.ts

HARMONY-1423
As a harmony user, I want to be able to retrieve harmony STAC catalogs for requests without requiring EDL authentication.
There has to be some kind of documentation that needs to be updated, but I can't find any.
Submit a harmony request and see it run to completion successfully.
`curl "http://localhost:3000/stac/<job-id>"` and verify you can retrieve the stac catalog of the job.
`curl "http://localhost:3000/stac/<job-id>/<item-index>"` and verify you can retrieve the stac item of the job.

HARMONY-1423: As a harmony user, I want to be able to retrieve harmony STAC catalogs for requests without requiring EDL authentication.

---

config/services.yml

DAS-1841
This PR is some final clean-up for EEDTEST metadata records in `services.yml`. I spotted that the NetCDF-to-Zarr service chain also listed the UMM-S record for the combined service of NetCDF-to-Zarr and the Swath Projector. This PR removes that incorrect reference.
* Build this branch of Harmony locally with Harmony-in-a-Box.
* Run the following requests to ensure they route correctly:
```
localhost:3000/C1233860183-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&maxResults=1&format=application%2Fx-zarr&skipPreview=true
localhost:3000/C1233860183-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&maxResults=1&format=application%2Fx-zarr&outputCrs=EPSG%3A4326&skipPreview=true
```
* ~~Tests added/updated (if needed) …

DAS-1841 - Remove incorrect UMM-S record from NetCDF-to-Zarr service chain.

---

config/alert-manager.yaml
config/prometheus-adapter-helm-values.yaml
config/prometheus.yaml

HARMONY-1449
Added annotation to alertmanager and prometheus-adapter pods to allow cluster autoscaler to relocate the pods to scale down the running nodes.
Run sandbox tests of a large request (e.g. http://internal-harmony-yliu10-frontend-1388673145.us-west-2.elb.amazonaws.com/C1234724470-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?subset=lat(-45%3A45)&subset=lon(0%3A180)&maxResults=110000&skipPreview=true&ignoreErrors=true
) with a deployment of harmony-ci-cd with the cluster autoscaler branch (harmony-1449-1). Verify the alertmanager and prometheus-adapter pods have the `"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"` annotation set and after the test is run, the number of nodes are scaled back down to only 2.

HARMONY-1449: Cluster autoscaler fix for nodes not scaling down because of local storage on prometheus pods.

---

package.json
tasks/service-runner/.mocharc.yml
tasks/service-runner/app/service/service-metrics.ts
tasks/service-runner/app/service/service-runner.ts
tasks/service-runner/app/workers/pull-worker.ts
tasks/service-runner/config/service-template.yaml
tasks/service-runner/env-defaults
tasks/service-runner/test/helpers/env.ts
tasks/service-runner/test/pull-worker.ts
tasks/service-runner/test/service-metrics.ts

HARMONY-1465, HARMONY-1459, and HARMONY-1461
HARMONY-1465: Updated service runner to allow tests to use a subdirectory of /tmp - /tmp/harmony. I also updated the mocha configuration to allow a timeout of 5 seconds since some of the tests always take more than 3.5 seconds. Previously this 5 second timeout was only applied when using npm run test.
HARMONY-1461: Updated the harmony start task to allow 3GB of heap space for the node process.
HARMONY-1459: Updated the service metrics to always have one more pod than the current number of queued and in progress work items for a service
I built the image and deployed to my own sandbox environment to test.
HARMONY-1465
1. Run `mocha` in the tasks/service-runner directory and verify everything passes.
2. Build the image with `npm run build`
3. …

HARMONY-1465: Update service runner to allow tests to use a subdirectory of /tmp

---

app/models/services/index.ts
test/models/services.ts

HARMONY-1470
Fixed bug when choosing service with concatenation.
Set up local dev environment to point to PROD, submit the following request and verify that it is going to the `harmony/netcdf-to-zarr` service rather than fail with `no matching service` error.
When I test locally the request fails within the `harmony/netcdf-to-zarr` service with error:
```
2023-05-26T18:02:01.066Z [debug]: 2023-05-26 18:02:01,055 [ERROR] [harmony-service.process_items_many_to_one:119] Download failed: processes exit codes: [0, 0, 0, 0, 0, -9]
Traceback (most recent call last):
File "/opt/harmony-netcdf-to-zarr/harmony_netcdf_to_zarr/adapter.py", line 93, in process_items_many_to_one
local_file_paths = download_granules(netcdf_urls, workdir,
File "/opt/harmony-netcdf-to-zarr/harmony_netcdf_to_zarr/download_u …
```

HARMONY-1470: Fixed bug when choosing service with concatenation.

---

app/frontends/capabilities.ts
test/collection-capabilities.ts

HARMONY-1397
As a harmony user, I want collection capabilities to include a link to the CMR UMM-Var record for each variable.
Run harmony locally, 
1) verify http://localhost:3000/capabilities?collectionId=C1233800302-EEDTEST returns response with a `capabilitiesVersion` of `'2'` and variables in the format of: 
variables: [
{
name: "alpha_var",
href: "https://cmr.uat.earthdata.nasa.gov/search/concepts/V1233801717-EEDTEST"
},
{
name: "blue_var",
href: "https://cmr.uat.earthdata.nasa.gov/search/concepts/V1233801716-EEDTEST"
},
{
name: "green_var",
href: "https://cmr.uat.earthdata.nasa.gov/search/concepts/V1233801696-EEDTEST"
},
{
name: "red_var",
href: "https://cmr.uat.earthdata.nasa.gov/search/concepts/V1233801695-EEDTEST"
}
]
2) Verify …

HARMONY-1397: As a harmony user, I want collection capabilities to include a link to the CMR UMM-Var record for each variable.

---

.github/workflows/github-actions.yml
.github/workflows/publish.yml

Harmony 1479
Updated deprecated Github actions using Node12.
Any new executions of GitHub actions should no longer show any warnings.

Harmony 1479 - Update deprecated Github actions using Node12

---

docs/Harmony API introduction.ipynb

HARMONY-1464
The sample notebook we link to from our landing page had a cell that reads the services.yml file from github to get a collection/service association. We replaced that with a call to /capabilities.
- Run the modified cell
- You should see an array of services

HARMONY-1464: Use capabilities endpoint in Harmony API introduction

---

kubernetes-services/work-scheduler/Dockerfile
kubernetes-services/work-scheduler/Dockerfile.mac
kubernetes-services/work-scheduler/package.json

HARMONY-1419
Fixes Docker build in Bamboo
1. Checkout this branch
2. Verify that you can still build the scheduler image for local and sandbox deployments
```
cd kubenetes-services/work-scheduler
npm run build
npm run build-m1
```

Harmony 1419 fix docker build james

---

app/markdown/apis.md
app/schemas/ogc-api-coverages/1.0.0/ogc-api-coverages-v1.0.0.yml
app/util/variables.ts
public/notebook-example.html
test/ogc-api-coverages/get-coverage-rangeset.ts

HARMONY-1474
As a harmony user, I would like to be able to provide a list of Variable CMR concept IDs when requesting variable subsetting
Run harmony locally, then run the following requests:
http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/V1233801695-EEDTEST/coverage/rangeset?subset=lat(20:60)&subset=lon(-140:-50)&granuleId=G1233800343-EEDTEST&outputCrs=EPSG:31975&format=image/png
http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/V1233801695-EEDTEST,V1233801696-EEDTEST/coverage/rangeset?subset=lat(20:60)&subset=lon(-140:-50)&granuleId=G1233800343-EEDTEST&outputCrs=EPSG:31975&format=image/png

HARMONY-1474: As a harmony user, I would like to be able to provide a list of Variable CMR concept IDs when requesting variable subsetting

---

docs/Harmony Feature Examples.ipynb
tasks/query-cmr/app/stac/cmr-catalog.ts

HARMONY-296
According to the issue "STAC validators show our catalogs and items as invalid". I took the STAC outputs (items, catalogs) generated from our services and the STAC output generated from our STAC endpoint and ran them through one of the validators referenced in the ticket. 
There was only one issue/failure (missing datetime property) which I have attempted to fix in this PR. https://github.com/radiantearth/stac-spec/blob/v1.0.0-beta.2/item-spec/item-spec.md#properties-object
I decided to set the property to null since we don't currently use it, but if it's more appropriate to fill it with a value we could perhaps use `temporal.start` (like in our STAC endpoint) https://github.com/nasa/harmony/blob/main/app/frontends/stac-item.ts#L156.
- run any request
- run a STAC item …

Harmony 296 - STAC validators

---

package-lock.json

HARMONY-1426
I made some library updates and inadvertently updated the gdal version to a version that does not work on our EC2 instances. This moves it back to 3.5.0 which was the version that was working.

HARMONY-1426: Lock gdal-async back to 3.5.0

---

app/models/user-work.ts
fixtures/uat.urs.earthdata.nasa.gov-443/168814650246494169
fixtures/uat.urs.earthdata.nasa.gov-443/168814650626380324
fixtures/uat.urs.earthdata.nasa.gov-443/168814650828163749
fixtures/uat.urs.earthdata.nasa.gov-443/168814650843835199
fixtures/uat.urs.earthdata.nasa.gov-443/168814650857569725
test/helpers/user-work.ts
test/models/user-work.ts

HARMONY-1406
There are some cases where the counts can become out of sync when a work item and job hits a state where it ends up getting retried while another pod is actively working on it and both finish out and possibly other situations.
This doesn't address the ability of the counts to get out of sync (we do have a fix to recalculate counts when we think there are work items to pick up based on counts, but it turns out there are no work items to pick up).
What it does do is prevents negative values which were causing problems in some of the metrics calculations for how many pods should be used.
The main thing is verifying the automated tests are correct. You can try to simulate the situation by submitting a request with many work items and then updating the counts in the rows for the …

HARMONY-1406: Make sure user_work ready and running counts cannot become negative.

---

app/views/workflow-ui/job/index.mustache.html
app/views/workflow-ui/job/work-items-table.mustache.html
app/views/workflow-ui/jobs/index.mustache.html
app/views/workflow-ui/jobs/jobs-table.mustache.html
package-lock.json
public/css/workflow-ui/default.css

HARMONY-1492-scroll-table
This is an alternative version of https://github.com/nasa/harmony/pull/425. It uses scrolling in the table body only, rather than the whole page. 
https://github.com/nasa/harmony/pull/425#pullrequestreview-1514690177
Checkout branch HARMONY-1492-scroll-table
Submit a large number of job requests so that the jobs page of the workflow user interface can display lots of jobs at once. Make sure that at least one of these requests produces a lot of work items or granules so that you can also test the job details page with a large number of work item rows.
When you scroll, all important actions / links and table headers should be viewable in the jobs and work items pages.

HARMONY-1492-scroll-table: Scroll overflowing table

---

app/frontends/jobs.ts
app/models/job.ts
test/helpers/jobs.ts
test/jobs/job-sharing.ts

HARMONY-900
After discussing with Chris, we realize that the field that I added for https://github.com/nasa/harmony/pull/423 will have little future value now that we have access to a new EULA acceptance validation endpoint (EDL `verify_user_eula`) which will change how we check for shareability.
Context:
The future plan is to allow sharing based on user EULA acceptance and user data permissions rather than what we do now which is based on EULA presence and whether or not the collections are public. This should increase access to job results and sharing once the new logic is implemented. This flag will be a lot less meaningful once we implement those changes, hence the desire to remove it now before it appears in prod.
- submit a request with > 1 granule and view the job endpoint JSON
- …

HARMONY-900-2: Revert addition of shareable field to job JSON

---

kubernetes-services/work-updater/app/util/env.ts
kubernetes-services/work-updater/env-defaults

HARMONY-158
Adds env vars that support aggregation that were inadvertently left out from the work updater service.
1. Check out this branch
2. Rebuild the work updater service in the kubernestes-services/work-updater dir using `npm run build`
3. Run bin/restart-services
4. Run this query and verify that it works
http://localhost:3000/C1234410736-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?format=application%2Fx-zarr&maxResults=2&concatenate=true

HARMONY-1508: Add missing env vars needed to support aggregated output

---

kubernetes-services/work-updater/app/util/env.ts
kubernetes-services/work-updater/env-defaults

HARMONY-1508
Fix broken batching by adding missing env vars to work updater
Run this query "http://localhost:3000/C1234208438-POCLOUD/ogc-api-coverages/1.0.0/collections/bathymetry/coverage/rangeset?concatenate=true&subset=lon(-160%3A160)&subset=lat(-80%3A80)&skipPreview=true&maxResults=2&subset=time(%221981-01-02T00%3A00%3A00.000Z%22%3A%222020-01-02T01%3A00%3A00.000Z%22)"

HARMONY-1508: Add env vars needed to support batching to the work updater

---

.nsprc
app/util/job.ts
kubernetes-services/work-scheduler/.nsprc
tasks/service-runner/.nsprc
test/util/job.ts

HARMONY-1531
Cancels queued work items on job cancelation. Prior to this modification, it was possible for a job to be canceled and have work items left in the queued state. These items could then be picked up and set to the running state, which was undesirable.
To test this out, I issued a request, then paused it after it generated all of the work items. Then executed `UPDATE work_items SET status = 'queued' WHERE "jobID" = 'my-job-id';`, unpaused the job, then canceled it.

HARMONY-1531: Cancel queued work items on job cancelation

---

app/frontends/workflow-ui.ts
app/middleware/admin.ts
app/middleware/cmr-collection-reader.ts
app/middleware/earthdata-login-oauth-authorizer.ts
app/middleware/earthdata-login-token-authorizer.ts
app/util/edl-api.ts
fixtures/uat.urs.earthdata.nasa.gov-443/undefined-user-groups
test/concatenation.ts
test/earthdata-login.ts
test/helpers/servers.ts

HARMONY-1552
When the user supplies their own bearer token to authenticate with Harmony (rather than going through the OAuth flow using their EDL credentials) it can't be used to make API calls to Earthdata Login. We need to use a token that is associated with the Harmony app instead, like the Harmony client token.
This was causing some Harmony requests to fail when the EULA verification logic was executed.
- submit some requests from a browser (using EDL credentials), and from another client using a bearer token (insomnia, harmony-py, etc.)
- make sure that they function as expected
- if you have a test user that hasn't accepted any EULAs, you can also test that EULA verification still works with these collections:
```
twoEulasCollection = 'C1258836670-EEDTEST';
oneEulaCollection = …
```

Harmony 1552 - Update EDL API requests to use Harmony client token instead of user-supplied bearer token

---

app/frontends/ogc-coverages/get-coverage-rangeset.ts
app/models/data-operation.ts
app/models/services/index.ts
app/schemas/data-operation/0.18.0/data-operation-v0.18.0.json
app/schemas/data-operation/CHANGELOG.md
app/schemas/data-operation/README.md
app/util/parameter-parsers.ts
config/services.yml
docs/guides/adapting-new-services.md
example/service-operation.json
fixtures/cmr.uat.earthdata.nasa.gov-443/169290180525797114
fixtures/cmr.uat.earthdata.nasa.gov-443/169290180675467658
test/helpers/data-operation.ts
test/models/data-operation.ts
test/models/services.ts
test/ogc-api-coverages/get-coverage-rangeset.ts
test/resources/data-operation-samples/batch1-operation.json
test/resources/data-operation-samples/batch2-operation.json
test/resources/data-operation-samples/batch3-operation.json
test/resources/data-operation-samples/batch4-operation.json
test/resources/data-operation-samples/batch5-operation.json
test/resources/data-operation-samples/multiple-collections-operation.json
test/resources/data-operation-samples/valid-operation-input.json
test/resources/data-operation-samples/valid-operation-v0.18.0.json

HARMONY-1505/6
Adds extendDimensions to the DataOperation. Holding off on API documentation until we are fully operational with the first extend-capable service.
- Under `capabilities:` in services.yml, for harmony-service-example in UAT, add `extend: true`.
- Request: http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?granuleId=G1233800343-EEDTEST&format=image/tiff&extend=a,b
- Check the workflow_steps table, operation column to ensure the values `a,b` were passed via the extendDimensions property in the operation JSON

Harmony 1505/6 - Add extendDimensions parameter to DataOperation

---

kubernetes-services/work-scheduler/package-lock.json
kubernetes-services/work-scheduler/package.json
kubernetes-services/work-updater/package-lock.json
kubernetes-services/work-updater/package.json
package-lock.json
package.json
tasks/giovanni-adapter/package-lock.json
tasks/giovanni-adapter/package.json
tasks/query-cmr/package-lock.json
tasks/query-cmr/package.json
tasks/service-runner/app/util/axios-clients.ts
tasks/service-runner/app/workers/pull-worker.ts
tasks/service-runner/package-lock.json
tasks/service-runner/package.json
tasks/service-runner/test/pull-worker.ts

HARMONY-1549
Locally almost every time I run `bin/restart-services` I have some pods stuck in a state where they get restarted but just print out RECEIVED TERMINATION REQUEST forever. I changed things so that when a pod first sees the request to be terminated it cleans up that TERMINATING file allowing the restart to succeed. It will still not attempt to do any work when it sees the TERMINATING request, and the pre-stop hook will prevent a pod from being killed while it is actively WORKING on a request.
For my 50 granule request I ran `bin/restart-services` a dozen times and every granule was processed successfully and there were no retries as would happen if a pod was killed mid request.
1. Build the service-runner image (npm run build in tasks/service-runner).
2. Run …

HARMONY-1549: Fix to ensure service runner does not get stuck in an infinite loop thinking it needs to terminate

---

Dockerfile
bin/deploy-services
bin/start-harmony
bin/start-postgres-localstack

HARMONY-1572
Currently harmony in a box requires NodeJS, a successful npm install within harmony, the AWS and awslocal CLIs. This ticket makes it so that none of those are required. Instead any calls that need to be made from our scripts that use those dependencies are performed through the harmony container.
`npm run bulid` - this will take 10 minutes
`bin/stop-harmony-and-services`
Switch your .env file to one for harmony in a box.
`bin/bootstrap-harmony`
Verify from the screen that the database migrations were successfully run and the queues were created using the harmony container. You should see messages like:
"Creating harmony-service-example queue using harmony container".
Verify you can submit a successful request.
Run `bin/stop-harmony-and-services` to destroy everything and copy …

HARMONY-1572: Remove dependencies on NodeJS and AWS CLI from harmony in a box

---

app/frontends/ogc-coverages/get-coverage-rangeset.ts
app/markdown/apis.md
app/schemas/ogc-api-coverages/1.0.0/ogc-api-coverages-v1.0.0.yml
app/util/log-execution.ts
test/ignore-errors.ts
test/workflow-orchestration.ts

HARMONY-1563
Changes our default behavior from failing requests on the first work item failure to continue processing.
1. `npm run build-all-services` to make sure the work item updater task is built.
2. `bin/restart-services`
3. Submit the request: http://localhost:3000/C1234724470-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?subset=lat(-45%3A45)&subset=lon(0%3A180)&skipPreview=true&granuleId=G1236546414-POCLOUD&granuleId=G1235845770-POCLOUD&granuleId=G1236614412-POCLOUD which has 2 failing and one successful granule. Verify that it completes with a COMPLETE_WITH_ERRORS state.
4. Submit another request with ignoreErrors=true and verify the behavior is the same (COMPLETE_WITH_ERRORS).
5. Submit another request with ignoreErrors=false and verify on the first failure it …

HARMONY-1563: Default to ignoreErrors=true behavior to continue processing requests on individual failures

---

app/backends/workflow-orchestration/work-item-updates.ts
app/backends/workflow-orchestration/workflow-orchestration.ts
app/models/work-item-update.ts
kubernetes-services/work-updater/app/workers/updater.ts
kubernetes-services/work-updater/test/updater.ts

HARMONY-1510
As promised, I made the work items update even more complicated :). But hopefully more readable.
In this PR, I made the following changes to improve the work items update performance:
1. Lowered the number of db transactions from one per granule to one per batch of granules (default to 10 granules a batch).
2. Lowered the number of workflow step completion checks from one per granule to one per batch.
3. Lowered the number of workflow step retrievals from two per granule to two per batch.
Based on test in Sandbox of 110K l2-subsetter requests with 400 max pods and 40 max nodes configuration, Harmony runs ~43% faster with these changes.
Tested in Sandbox (http://internal-harmony-yliu10-frontend-1539904139.us-west-2.elb.amazonaws.com).

HARMONY-1510: Work items update performance improvement

---

bin/update-harmony

DAS-1975 (not directly part of ticket, discovered while testing)
This PR makes a quick change to fix the name of the `harmonyservices` Docker repository when pulling the `work-scheduler` image as part of the `bin/update-harmony` script.
* Pull branch.
* Run the `bin/update-harmony` script.
* All images should be pulled successfully (particularly `harmonyservices/work-scheduler`).
* ~~Acceptance criteria met~~
* ~~Tests added/updated (if needed) and passing~~
* ~~Documentation updated (if needed)~~

DAS-1975 - Fix respository for work-scheduler image.

---

package.json

HARMONY-1538
Fixes a typo in the start-dev script, changing `cd servcies` to `cd services`.
Run `harmony % npm run start-dev`

HARMONY-1538: start-dev typo fix

---

README.md
docs/guides/configuring-harmony-service.ipynb

HARMONY-1582
Small update to README linking to `envsubst` since it's needed for Harmony in a Box and added a reference to `bin/generate-new-service` script in the notebook that demonstrates adding services.
See changes to the README.md file and the docs/guides/configuring-harmony-service.ipynb notebook.

HARMONY-1582: Add notebook entry mentioning generate-new-service and reference to envsubst in README

---

bin/create-k8s-config-maps-and-secrets

HARMONY-1623
Fixes an issue with creating the k8s configmap that resulted in LOCALSTACK_HOST being overwritten
1. check out this branch
2. Set your .env for harmony-in-a-box
3. Run bin/bootstrap-harmony
4. Make sure everything works
5. Run bin/stop-harmony-and-services
6. Set your .env for local development
7. Run bin/bootstrap-harmony
8. Run bin/start-dev-services
9. Make sure everything works

HARMONY-1623: Fix LOCALSTACK_HOST value for config map

---

services/harmony/app/backends/workflow-orchestration/work-item-updates.ts
services/harmony/app/frontends/workflow-ui.ts
services/work-failer/app/workers/failer.ts
services/work-failer/env-defaults
services/work-updater/app/workers/updater.ts
services/work-updater/test/updater.ts

HARMONY-1617
This changes the work-failer and the workflow-ui to no longer put messages on the work item update queue for the work-item-updater to process retries. Instead the database updates will be directly performed by the components. This is to address an issue we were seeing in production with the message queue getting overwhelmed by retry messages.
Build the work-failer image.
Set FAILABLE_WORK_AGE_MINUTES to 0 and WORK_FAILER_PERIOD_SEC to 2 so that it constantly tries to fail work items. Verify that the retries are processed in the work-failer by looking at the logs.
Also test retry from the workflow-ui and make sure the work item is moved back to the READY state and retry count incremented.
I tested this in the sandbox and found that when submitting a large request it identified …

HARMONY-1617: Updates to work-failer to process database updates instead of using the message queue

---

scripts/service-comparison.ts
services/harmony/app/util/cmr.ts
services/harmony/test/service-comparison.ts

HARMONY-1469
Adds concatenation to UMM-S / services.yml comparison script. Errors are returned from the script output when there is a mismatch between the concatenation property of the Harmony service config and the UMM-S record.
`npm run compare-services`
In my case I also console.logged() the UMM-S record and service config when there is an error to see if the error reported is accurate.

Harmony 1469 - Add concatenation to UMM-S / services.yml comparison script

---

services/harmony/app/util/cmr.ts

HARMONY-1469
This is a follow-on pull request for this ticket which added concatenation to the service comparison script. Apparently we are on the wrong version of UMM-S currently (1.5.1 is not surfacing the concatenation information). I'm not sure how this worked before as I do remember checking things manually while developing this, so I'm pretty confused but I think we need this update nonetheless.
Compare 
https://cmr.uat.earthdata.nasa.gov/search/services.umm_json_v1_5_1?concept_id=S1240999847-EEDTEST&pretty=true
with
https://cmr.uat.earthdata.nasa.gov/search/services.umm_json_v1_5_2?concept_id=S1240999847-EEDTEST&pretty=true
The newer version should have `Concatenate`.

HARMONY-1469: Update UMM-S version to 1.5.2

---

services/harmony/Dockerfile

HARMONY-1639 (sort of - JIRA has two tickets marked as 1639 right now)
Harmony in a box is failing to create SQS queues due to a bug in the default versions available on the node18-buster image. This downgrades boto3 to allow the version of the aws cli and boto3 to successfully create SQS queues.
1. Build the harmony image.
2. Run harmony in a box.
3. Verify queues get created and you can complete a request successfully.

HARMONY-1639: Fix for harmony in a box to be able to create SQS queues after NodeJS 18 update

---

services/harmony/app/frontends/health.ts
services/harmony/app/middleware/error-handler.ts
services/harmony/app/models/job.ts
services/harmony/app/routers/router.ts
services/harmony/test/health.ts
services/harmony/test/helpers/db.ts
services/harmony/test/helpers/health.ts
services/harmony/test/jobs/jobs-listing.ts
services/harmony/test/jobs/jobs-status.ts
services/harmony/test/ogc-api-coverages/get-coverage-rangeset.ts
services/work-failer/test/helpers/db.ts
services/work-reaper/test/helpers/db.ts

HARMONY-1647
Adds a couple of endpoints /health and /admin/health that we can use in the future for health checks and uptrends. This is just the initial ticket to create the endpoints. We'll have future tickets to address adding more components to check and determining when things are degraded and eventually have uptrends use these endpoints for tracking status. We'll also write tickets to add documentation once we've nailed down the response format a little more.
Start harmony and verify that http://localhost:3000/health returns that harmony is up and the return code is 200. Also as an admin user verify the same for http://localhost:3000/admin/health. The responses are identical at the moment. In the future we will add more operations only detailed information to the admin/health …

HARMONY-1647: Add initial health and admin/health check endpoints.

---

services/work-scheduler/Dockerfile
services/work-scheduler/Dockerfile.mac
services/work-scheduler/app/util/env.ts
services/work-scheduler/app/util/k8s.ts
services/work-scheduler/app/workers/scheduler.ts
services/work-scheduler/env-defaults
services/work-scheduler/test/scheduler.ts

HARMONY-1651
Queues fewer items to resolve an issue where synchronous requests were timing out when there were other requests in the system for many granules for the same service and the processing of those granules was extremely slow.
I also sped up the docker build for the work-scheduler (we need to do this for all the images) by reordering the npm ci command so that it happens before installing the code. So when there are only code changes the build and pushing the image to sandbox take seconds due to the layer caching.
This is best tested in a sandbox environment since you'll have more than one worker pod and multiple schedulers. I tested in sandbox and saw that with 125 workers anywhere from 109 to 161 items were in the queued or running state at any point in time. That means we were …

HARMONY-1651: Queue fewer items to ensure faster processing of new requests and better fair queueing

---

Dockerfile-notebooks
services/giovanni-adapter/Dockerfile
services/giovanni-adapter/bin/prebuild
services/harmony/Dockerfile
services/query-cmr/Dockerfile
services/service-runner/Dockerfile
services/work-failer/Dockerfile
services/work-failer/Dockerfile.mac
services/work-reaper/Dockerfile
services/work-reaper/Dockerfile.mac
services/work-scheduler/Dockerfile
services/work-scheduler/Dockerfile.mac
services/work-updater/Dockerfile
services/work-updater/Dockerfile.mac

HARMONY-1618
Building all docker images takes only seconds when making a code change due to caching of layers. Previously on every code change we were running `npm ci` or `npm install` commands due to the ordering in the Dockerfile.
1. Build all the images with `npm run build`, `npm run build-notebooks-image`, `npm run build-all`, and `npm run build-all-m1` to make sure all of the images are working as expected.
2. Test out harmony in a box to verify the harmony container
3. Run `npm run run-notebooks-image` to test out the container for running notebooks
I tested a deployment to sandbox and verified everything was working.

HARMONY-1618: Speed up building all images when only a code change is being made.

---

db/db.sql
db/migrations/20231213190800_change_jobs_indices.js
services/harmony/app/backends/service-response.ts
services/harmony/app/backends/workflow-orchestration/work-item-updates.ts
services/harmony/app/frontends/jobs.ts
services/harmony/app/frontends/request-metrics.ts
services/harmony/app/frontends/stac.ts
services/harmony/app/frontends/workflow-ui.ts
services/harmony/app/models/job.ts
services/harmony/app/models/services/base-service.ts
services/harmony/app/models/services/http-service.ts
services/harmony/app/models/workflow-steps.ts
services/harmony/app/util/job.ts
services/harmony/env-defaults
services/harmony/test/aggregation-batching.ts
services/harmony/test/backend-callbacks.ts
services/harmony/test/helpers/callbacks.ts
services/harmony/test/helpers/jobs.ts
services/harmony/test/ignore-errors.ts
services/harmony/test/jobs/batch-status-change.ts
services/harmony/test/jobs/message.ts
services/harmony/test/models/job.ts
services/harmony/test/work-items/retries.ts
services/harmony/test/work-items/work-backends.ts
services/harmony/test/workflow-orchestration.ts
services/work-failer/.nsprc
services/work-failer/test/work-failer.ts

HARMONY-1654
The ticket was to fix a case where we were pulling back job links from one of the workflow-ui queries. When looking into it I found that our internal code APIs for querying for jobs were inconsistent and made it easy to pull back job links unintentionally. I refactored and tried to use common code for querying for all jobs or querying for a single job. By default links are not returned, the caller explicitly needs to request links now.
I also fixed all of the indices on the jobs table to match the queries that we execute.
1. Run the database migration and verify it succeeds.
2. Regression test the jobs listing and jobs status page. Verify listings do not include the job links and the job status does include job links. For large requests make sure the paging works correctly …

HARMONY-1654: Refactor code and update indices created on the jobs table

---

ENV_CHANGELOG.md
services/harmony/env-defaults

HARMONY-1660
Decreases the default MAX_DOWNLOAD_RETRIES from 10 to 3. There is another ticket, HARMONY-1621 ("Retrying of download failures internally in service library is wasting resources and slowing down system throughput") that is related but likely involves a lot more work.
n/a

HARMONY-1660: Decrease MAX_DOWNLOAD_RETRIES

---

ENV_CHANGELOG.md
services/harmony/env-defaults

DAS-2000
This PR increases the container memory for HOSS. HOSS has recently been failing for GHRSST MUR bounding box spatial subset requests that cross the longitudinal edge of the grid. This memory increase will also potentially help support spatial subsetting of high resolution grids when determining the minimally encompassing bounding box (e.g., ATL14 granules over the Antarctic).
* Make sure your Docker Desktop has comfortably more than 8 GB of memory available (I had 10 GB to be safe).
* Rebuild Harmony to use this branch.
* Run the following request, it should complete successfully:
```
http://localhost:3000/C1243747494-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=lat(-30.0%3A30.0)&subset=lon(-180.0%3A-120.0)&skipPreview …
```

DAS-2000 - Increase HOSS container memory.

---

config/services.yml

DAS-2088
This PR updates the UMM-S record used to identify the Trajectory Subsetter in production so that it is one maintained by the Data Services team, who develop the Trajectory Subsetter.
Compare the UMM-S records for the ORNL_CLOUD and XYZ_PROV providers using the following CMR endpoint:
```
https://cmr.earthdata.nasa.gov/search/services.umm_json?concept_id=<UMM-S concept ID>
```
The important thing is that the service options (e.g., variable/temporal/spatial subsetting) and the Harmony endpoint are consistent. I added some contact information for David and I that were not in the original record.
I will only merge this once all UMM-S to UMM-C associations that exist with the ORNL_CLOUD record are replicated for the XYZ_PROV record. I do not have permission to make those associations, …

DAS-2088 - Update the production Trajectory Subsetter UMM-S record reference.

---

.nsprc
services/harmony/.nsprc
services/harmony/app/util/object-store/file-store.ts
services/service-runner/app/service/service-runner.ts
services/service-runner/test/service-runner.ts

HARMONY-1696
This PR returns the STAC catalogs in proper numerical order rather than in string order. In other words catalog2.json
comes before catalog10.json. This is needed by Batchee to preserve the order it creates when it batches granules.
Not easy to test locally. You will need to add Batchee and Stitchee to config.yml  as well as env vars for their queue URLS to lib/util/env-defaults. OR you can look at the following screen shots. The first one is our current code and shows that the Stitchee work-items were created in order of the "string sorted" STAC catalog file names. The Second one is from this branch and shows the Stichee work items were created in the order of the STAC catalogs created by Batchee, which is what we want. Note the rows from the dB are sorted by work-item ID in …

HARMONY-1696: Ensure that STAC catalogs are returned in proper order

---

services/harmony/app/frontends/service-image-tags.ts
services/harmony/test/service-image-tags.ts

HARMONY-1701
This is the harmony part of the HARMONY-1701. It invokes the harmony-ci-cd script to deploy the specified service asynchronously on the EC2 instance and put an SNS message for harmony service to consume.
Tested in Sandbox.
1) Set up an email subscription to the SNS topic, e.g. deploy-service-status-topic-yliu10
2) submit a service-image-tag PUT request via insomnia, e.g. `{{ _.root }}/service-image-tag/giovanni-adapter` with request body: `{"tag": "yliu10"}`
3) Verify a email is sent with a successful SNS message:
{"deploy_service":"giovanni-adapter","tag":"yliu10","status":"successful","image":"266xxx.dkr.ecr.us-west-2.amazonaws.com/harmonyservices/giovanni-adapter:yliu10","service_queue_urls":"[\"266xxx.dkr.ecr.us-west-2.amazonaws.com/harmonyservices/giovanni-adapter:latest, …

HARMONY-1701: Add invocation of harmony-ci-cd script in service-image-tag endpoint.

---

.gitignore
.nsprc
services/harmony/.nsprc
services/harmony/app/routers/router.ts
services/harmony/app/server.ts
services/harmony/app/util/url.ts
services/harmony/env-defaults

HARMONY-1708
With the USE_HTTPS variable set to true both the harmony frontend and backend listeners will use TLS. We will set this to true in the deployed environments. See the ci-cd repo for instructions on how to test there.
Verify that locally everything continues to work as expected by default (and does not use TLS). Verify in the sandbox that setting USE_HTTPS to true works correctly.

HARMONY-1708: Update frontend and backend to be able to use TLS

---

package-lock.json
services/harmony/package-lock.json
services/service-runner/package-lock.json
services/work-failer/package-lock.json
services/work-reaper/package-lock.json
services/work-scheduler/app/util/env.ts
services/work-scheduler/app/workers/scheduler.ts
services/work-scheduler/env-defaults
services/work-scheduler/package-lock.json
services/work-scheduler/test/scheduler.ts
services/work-updater/package-lock.json

HARMONY-1703
Prevents scheduling work when the small work item update queue is backed up since any new work is just going to end up at the end of that queue. This prevents issues with work being retried because it has been in the running state for too long and also helps ensure that fair queueing works as expected with new small requests able to be worked off quickly instead of being stuck behind a long queue to mark the work item as completed.
It's tricky to test locally because things do not work in parallel like in an AWS environment. In sandbox I set `MAX_WORK_ITEMS_ON_UPDATE_QUEUE=10` and then ran a test with 250 concurrent pods with a 110K granule request. I saw the log message throughout the test: 
> Work item update queue is too large with 124 items, will not schedule more work` …

HARMONY-1703: Do not schedule additional work when there is a backlog on the work item update queue

---

.nsprc
services/harmony/.nsprc
services/harmony/app/frontends/stac-item.ts
services/service-runner/.nsprc
services/work-failer/.nsprc
services/work-reaper/.nsprc
services/work-scheduler/.nsprc
services/work-updater/.nsprc

HARMONY-1692
When there is no mime-type available for a job link the STAC item generation currently fails with an internal server error.
Note that the tests are not currently testing the response format for the STAC items. I've written HARMONY-1730 to fix that as well as overhaul all the STAC item tests.
NOTE: I verified type is not a required STAC item asset field: https://github.com/radiantearth/stac-spec/blob/master/item-spec/json-schema/item.json
Submit http://localhost:3000/C1205428742-ASF/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?maxResults=1
Navigate to the STAC catalog and then append /0 to the catalog to get the first item.
Verify a STAC item response is generated, and note that the 'type' field is not included in the assets.
Switch back to the main branch and …

HARMONY-1692: Fix internal server error for STAC item generation when no mime-type is available

---

package-lock.json
services/harmony/app/frontends/service-image-tags.ts
services/harmony/package-lock.json
services/harmony/test/service-image-tags.ts
services/query-cmr/package-lock.json
services/service-runner/package-lock.json
services/work-failer/package-lock.json
services/work-reaper/package-lock.json
services/work-scheduler/package-lock.json
services/work-updater/package-lock.json

HARMONY-1728
Removes the service-runner image from the service-image-tag list since it cannot be updated using the service image tag deployment endpoint. Also returns the service images in alphabetical order.
http://localhost:3000/service-image-tag
Verify the service-runner version is no longer included.
Verify the services are displayed in alphabetical order.
http://localhost:3000/service-image-tag/foo
Verify the error message returns the services in alphabetical order.

HARMONY-1728: Alphabetize service-image-tag list

---

services/harmony/app/frontends/service-image-tags.ts
services/harmony/app/util/env.ts
services/harmony/test/helpers/servers.ts
services/harmony/test/service-image-tags.ts

HARMONY-1733
Update /service-image-tag to only show deployed services in an environment. Before it was showing services that were not deployed such as podaac/ps3 and in production several services like hybig, geoloco, stitchee, and batchee are not deployed.
Bring up http://localhost:3000/service-image-tag. Verify that only the services which are defined in your LOCALLY_DEPLOYED_SERVICES are reported. Verify that it matches your k8s deployments of backend services.

HARMONY-1733: Update /service-image-tag to only show deployed services in an environment

---

db/db.sql
db/migrations/20240321202226_add_service_deployments_table.js
docs/guides/managing-existing-services.md
services/harmony/app/frontends/service-image-tags.ts
services/harmony/app/models/service-deployment.ts
services/harmony/app/routers/router.ts
services/harmony/test/service-image-tags.ts

HARMONY-1732
This PR has the following changes:
- adds service_deployments table in harmony to track all service self-deployments. 
- adds `status_link` field in service image tag update endpoint response to list the url to track service self-deployment status
- adds new route `GET <harmony-root>/service-image-tag/deployment/<deployment-id>` and support to show the deployment details including status for the given `deployment-id`.
Modify the command line in `execDeployScript` to simulate successful and failed service deployments. e.g. 
```
//const command = `./bin/exec-deploy-service ${service} ${tag}`;
const command = 'ls';
```
Verify:
1) when update a service tag, a `status_link` field is returned in the response. e.g.
curl -XPUT -H "Authorization: Bearer <token>" -H 'Content-type: …

HARMONY-1732: As a harmony user, I want to check my service self deployment status.

---

services/harmony/app/frontends/service-image-tags.ts
services/harmony/app/util/container-registry.ts
services/harmony/test/service-image-tags.ts

HARMONY-1731
Fixes the issue where we could't get the ECR describe image command to work even though we were given the appropriate permissions. We were not passing the argument that specifies the registry where the image is located.
I tested this in sandbox and so did Chris, for geoloco, and query-cmr.

Harmony 1731 - Add registry ID when describing ECR images

---

bin/update-harmony
docs/guides/managing-existing-services.md
services/harmony/app/frontends/service-image-tags.ts

HARMONY-1732
This PR drops the `id` field from service deployment status result. It is just noise (internal implementation detail) that we should not expose to the end user.
Attempt to update service image tag and then follow the status link to see everything is fine.

HARMONY-1732: Drop id from service deployment status result.

---

.nsprc
config/services.yml
services/harmony/.nsprc
services/service-runner/.nsprc
services/work-scheduler/.nsprc

DAS-2131
This PR updates the Harmony services.yml with the information for harmony prod. It mimics the initial Harmony record for [HyBIG in UAT](https://github.com/nasa/harmony/pull/397).
It points to the correct UMM-S service record. [HyBIG UMM-S Service record in production](https://mmt.earthdata.nasa.gov/services/S2697183066-XYZ_PROV)
I'm not sure what else needs to be done to enable HyBIG in Production.
¯\_(ツ)_/¯
* [N/A] Tests added/updated (if needed) and passing
* [N/A] Documentation updated (if needed)

Adds sds/HyBIG service to PROD

---

docs/guides/managing-existing-services.md
services/harmony/app/frontends/service-image-tags.ts
services/harmony/test/service-image-tags.ts

HARMONY-1755
This PR is the harmony project portion of the ticket. It adds disabling of service deployment at the beginning of a service deployment and re-enable the service deployment when the service deployment is successful. 
Run harmony locally, change the `command` in `execDeployScript` function to sleep 100 seconds.
```
// const command = `./bin/exec-deploy-service ${service} ${tag}`;
const command = 'sleep 100';
```
Then kick off a service deployment, the service deployment will run for 100 seconds and succeed.
Verify within the 100 seconds while the service deployment is running, any deployment of any service will fail with http status code `423` and message `Service deployment is disabled.`. 
Verify after 100 seconds, the first service deployment status changes from `running` to …

HARMONY-1755: As a harmony deployer, I want only one harmony deployment or service deployment running at a given time

---

.github/workflows/harmony-in-a-box.yml

HARMONY-1763
Fix for Harmony in a box test run in GitHub action
Look at the status of the Harmony in a box test at the bottom of this page

HARMONY-1763: Lock macos version to 12 for github action

---

services/harmony/app/frontends/ogc-coverages/get-coverage-rangeset.ts
services/harmony/app/frontends/ogc-coverages/util/subset-parameter-parsing.ts
services/harmony/app/util/parameter-parsers.ts
services/harmony/app/util/parameter-parsing-helpers.ts
services/harmony/test/ogc-api-coverages/subset-parameter-parsing.ts
services/harmony/test/util/parameter-parsing.ts

HARMONY-1766
Running `harmony-py~=0.4.12` I noticed that requests with `height`, `width`, `scale_size` or `scale_extent` were causing 500 errors. It looks like this is due to the new use of the POST method for requests in this version of the package onwards. Looking at Harmony itself, these parameters are either numbers or lists of numbers, but are being passed around as strings, which has cause schema validation errors within Harmony.
This PR might not be the best way to fix it (I'm kind of just wading in trying to make a fix), but maybe it's okay? Totally happy if there's a better way to fix the issue, and this PR gets throw away, though.
* Build a local Docker image of the Harmony Regridding service (it's _almost_ in open-source land, but for now, [use this …

HARMONY-1766 - Handle numerical parameters in POST requests.

---

services/query-cmr/app/stac/cmr-catalog.ts
services/query-cmr/test/cmr-to-stac.ts

HARMONY-1751
Add browse stac assets based on UMM JSON RelatedURL subtype.
Since there is no service provider test data in UAT right now, I created a testing collection in UAT for manual testing. Submit the following harmony request:
`http://localhost:3000/C1265140586-MMT_2/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?subset=lat(-45%3A45)&subset=lon(0%3A180)&maxResults=1&skipPreview=true&ignoreErrors=true`
Then in the granule stac catalog which is created as output of the query-cmr step in `s3://local-artifact-bucket/<harmony-request-id>/<work-item-id>/outputs/`, verify there is a browse asset with the following content:
```
"browse": {
"href": "https://archive.swot.podaac.earthdata.nasa.gov/podaac-swot-ops-cumulus-protected/SWOT_L2_HR_LakeSP_1.0/SWOT_L2_HR_LakeSP_Unassigned_40 …
```

HARMONY-1751: Add browse stac assets based on UMM JSON RelatedURL subtype.

---

services/harmony/app/markdown/apis.md
services/harmony/app/routers/router.ts
services/harmony/app/schemas/ogc-api-edr/1.1.0/ogc-api-edr-v1.1.0.yml
services/harmony/test/documentation-page.ts
services/harmony/test/workflow-ui/work-items-table.ts

HARMONY-1744
As a Harmony user I want to see online documentation for the Harmony OGC EDR API.
Run harmony locally, verify `http://localhost:3000/docs` shows the root api document and under `Using the Service APIs` section, there is description of OGC EDR API including supported route, request parameters and examples.
Verify `http://localhost:3000/docs/edr-api/` shows OGC EDR API.

HARMONY-1744: As a Harmony user I want to see online documentation for the Harmony OGC EDR API.

---

services/harmony/app/util/aggregation-batch.ts
services/harmony/app/util/parameter-parsing-helpers.ts
services/harmony/app/util/variables.ts
services/harmony/test/util/variables.ts

fix bug in parsing item size as an int
HARMONY-1787
Fixes a bug in the way we validate variables that was triggered when using a POST for the query with variables that have 'all' in their names.
I don't know of a collection that has 'all' in the variable names outside of production, so it is hard to do a full end-to-end test for this. There is a new unit test that passes queryVars as a string containing a variable with `all` in the name. This test fails without the changes to the variable validation code, as expected.

HARMONY-1787: Force queryVars to an array before validating and

---

services/harmony/app/routers/backend-router.ts
services/harmony/app/util/env.ts
services/harmony/env-defaults

HARMONY-1787
This is a fix for a problem we are having with work-item updates being too large for the express server on the back-end.
Run a many (4000+) variable query and observe that the query-cmr step completes successfully.
NOTE: There is a known issue with trajectory-subsetter that will keep it from running correctly with many variables.

HARMONY-1787: Increase size of allowed JSON body on back-end

---

services/service-runner/app/workers/pull-worker.ts
services/service-runner/test/pull-worker.ts

HARMONY-1787
Removes variables from operation before sending work-item update to save memory
Run some queries to make sure nothing has changed

HARMONY-1787: Remove variables from operation before sending work-item update

---

config/services.yml

LDDS-199
Added support for multiple band names.
```
$ clone this repo: https://git.earthdata.nasa.gov/projects/LDDS/repos/laads-subset_band_name-service/browse
$ conda create --name subset_band_name python=3.9 --channel conda-forge --channel defaults
$ conda activate subset_band_name
$ pip install -r ./harmony_python_interface/pip_requirements.txt
$ pip install -r ./docs/pip_requirements.txt
$ cd docs
$ jupyter notebook
```
* Open `Test_Harmony_Integration.ipynb`
* Run the `Single Granule Test` cells.
* The final Output should say
```
{'Latitude': (('10*nscans:MODIS_SWATH_Type_L1B',
'Max_EV_frames:MODIS_SWATH_Type_L1B'),
(-301531136, 1241841664),
5,
0),
'Longitude': (('10*nscans:MODIS_SWATH_Type_L1B',
'Max_EV_frames:MODIS_SWATH_Type_L1B'),
(-301531136, 1241841664),
5,
1),
'EV_500_RefSB': …
```

LAADS subset-band-name Service Multiple Band Support

---

package-lock.json
services/harmony/package-lock.json
services/service-runner/package-lock.json
services/work-reaper/env-defaults
services/work-scheduler/package-lock.json

HARMONY-1794
Changes the default to keep work items in the database for 14 days after a job completes. NSIDC asked if we could keep them for at least 7 days and I took a look and found that the number of work items from old paused jobs often dwarfs the number that would be kept by increasing the retention so it will not have a significant impact to the size of the work items table in the database. We were already keeping them around for 3 days in both UAT and prod (we override the default with a variable in Bamboo - we will want to delete that override in Bamboo after deploying this change).
There's no code change - just sanity check that with the new default value the work reaper does not throw any errors when running.

HARMONY-1794: Default to keeping work items for 14 days after job completes

---

.nsprc
db/db.sql
db/migrations/20240529202226_add_provider_ids.js
db/migrations/20240619202027_add_message_to_service_deployment.js
docs/guides/managing-existing-services.md
services/harmony/.nsprc
services/harmony/app/frontends/service-image-tags.ts
services/harmony/app/middleware/error-handler.ts
services/harmony/test/service-image-tags.ts
services/service-runner/.nsprc
services/work-scheduler/.nsprc

HARMONY-1772
As a harmony service provider, I want to know the reason service deployments are disabled when I am unable to deploy
Manually change the `execDeployScript` command in service-image-tags.ts to something like a `sleep 30` that can be executed locally, e.g.
```
// const command = `./bin/exec-deploy-service ${service} ${tag}`;
const command = 'sleep 30';
```
Then, try to enable/disable service deployment state with and without an optional message field and verify when getting the service deployment state, the result reflect the correct state and message used in the enable/disable call.
See below for a couple of the example requests:
```
curl -H "Authorization: Bearer <token>" http://localhost:3000/service-deployments-state
curl -i -XPUT -H "Authorization: Bearer <token>" -H …
```

HARMONY-1772: As a harmony service provider, I want to know the reason service deployments are disabled when I am unable to deploy

---

services/harmony/app/backends/workflow-orchestration/work-item-updates.ts

HARMONY-1806
Update error logging when handling STAC parsing exception.
Submit a harmony request that will cause STAC parsing exception (due to a bug in l2ss-py) and verify that Harmony logs the stacktrace properly in the log. e.g. 
http://localhost:3000/C1261072645-POCLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=lat(34.84931%3A35.83342)&subset=lon(-125.57812%3A-124.73438)&subset=time(%222023-11-15T18%3A00%3A00%2B00%3A00%22%3A%222023-11-18T07%3A00%3A00%2B00%3A00%22)&skipPreview=true&concatenate=true

HARMONY-1806: Update error logging when handling STAC parsing exception.

---

services/harmony/app/frontends/workflow-ui.ts
services/harmony/app/models/job.ts
services/harmony/app/views/workflow-ui/jobs/index.mustache.html
services/harmony/public/js/workflow-ui/jobs/index.js
services/harmony/public/js/workflow-ui/jobs/jobs-table.js
services/harmony/test/workflow-ui/jobs-table.ts
services/harmony/test/workflow-ui/jobs.ts

HARMONY-1791
2 updates to the previous PR https://github.com/nasa/harmony/pull/601:
Changes the provider filter from `prov: *` to `provider: *`
Populates the autocomplete filter box for existing providers (from the jobs table)
Submit some jobs, preferably with collections that have different providers. 
- http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/blue_var/coverage/rangeset?subset=lat(20%3A60)&subset=lon(-140%3A-50)&granuleId=G1233800343-EEDTEST&outputCrs=EPSG%3A31975&format=image%2Fpng
- http://localhost:3000/C1244165142-GES_DISC/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&subset=lat(-63.325%3A76.325)&subset=lon(-171.0%3A171.0)&granuleId=G1244165734-GES_DISC
Navigate to http://localhost:3000/admin/workflow-ui. Use the …

Harmony 1791 - Usability updates for provider filter in workflow ui

---

services/harmony/app/frontends/workflow-ui.ts
services/harmony/app/views/workflow-ui/job/index.mustache.html
services/harmony/app/views/workflow-ui/jobs/job-table-row.mustache.html
services/harmony/test/workflow-ui/job.ts

HARMONY-1819
Modifies the "Jobs" breadcrumb link (on the job page of the Workflow UI) so that filters are preserved when navigating back to the jobs table page.
1. navigate to http://localhost:3000/admin/workflow-ui
2. add filters (like `status: failed`) and submit
3. click a job link (to navigate to the job page)
4. click the "Jobs" breadcrumb link
5. the filters from step 2 should be preserved

Harmony 1819 - Preserve filters when navigating back to the jobs page from the job page of the Workflow UI

---

services/harmony/app/models/service-deployment.ts
services/harmony/test/service-deployment.ts

HARMONY-1796
Deployments are now returned in descending order of the creation date.
Add this code (which seeds the database with deployments) to server.ts, toward the end of the `buildFrontendServer` function, and restart Harmony:
```javascript
const failedFooDeployment = new ServiceDeployment({ deployment_id: '01f90511-109c-417c-8b17-0a5046ae562c', service: 'foo-service',
username: 'bob', tag: '1', status: ServiceDeploymentStatus.FAILED, message: 'Failed service deployment' });
const successfulFooDeployment = new ServiceDeployment({
deployment_id: 'b7a527a1-487e-4a6f-9e77-0083ac1b800b', service: 'foo-service',
username: 'eve', tag: '1', status: ServiceDeploymentStatus.SUCCESSFUL, message: 'Deployment successful',
});
const runningFooDeployment = new ServiceDeployment({
deployment_id: …
```

Harmony 1796 - Deployments returned in descending order of the creation date

---

services/harmony/app/server.ts
services/harmony/app/util/edl-api.ts
services/harmony/test/service-image-tags.ts
services/harmony/test/util/log.ts

HARMONY-1827
Add cookie-secret header support to service-deployments-state endpoint
Verify service-deployments-state can be enabled/disabled using COOKIE-SECRET:
curl -i -XPUT -H "COOKIE-SECRET: cookie secret value" -H 'Content-type: application/json' http://localhost:3000/service-deployments-state -d '{"enabled": false, "message": "Disabled using COOKIE-SECRET"}'
curl -i -XPUT -H "COOKIE-SECRET: cookie secret value" -H 'Content-type: application/json' http://localhost:3000/service-deployments-state -d '{"enabled": true, "message": "Enabled using COOKIE-SECRET"}'

HARMONY-1827: Add cookie-secret header support to service-deployments-state endpoint

---

.nsprc
services/harmony/.nsprc
services/service-runner/.nsprc
services/work-failer/.nsprc
services/work-scheduler/.nsprc

HARMONY-1832
Some of the .nsprc expiration date has expired today. Update npm audit skip expiration dates for some vulnerabilities to later date.
npm install 
npm run test

HARMONY-1832: Update npm audit skip expiration dates for some vulnerabilities

---

services/harmony/app/views/workflow-ui/job/index.mustache.html
services/harmony/app/views/workflow-ui/jobs/index.mustache.html
services/harmony/public/js/workflow-ui/job/index.js
services/harmony/public/js/workflow-ui/job/work-items-table.js
services/harmony/public/js/workflow-ui/jobs/index.js
services/harmony/public/js/workflow-ui/jobs/jobs-table.js
services/harmony/test/workflow-ui/job.ts
services/harmony/test/workflow-ui/jobs.ts

HARMONY-1613
This fixes an issue where a user applies filters in the Workflow UI and then ends up on a page with unexpected results because the page number was maintained. E.g. you may be on page 5 (with three rows of jobs), you add a filter and click the apply button, and the server returns page 5 again, but this time with no results on it. 
What should happen is that they are sent to page 1 instead. (This is the expected behavior according to @chris-durbin.)
Verify that when a user clicks the "submit" button on the Workflow UI, they should be sent to the first page.

Harmony 1613 - Ensure user is sent to page 1 whenever filters are applied

---

docs/guides/develop.md
services/harmony/app/frontends/service-image-tags.ts
services/harmony/app/routers/router.ts
services/harmony/app/util/cookie-secret.ts
services/harmony/app/util/edl-api.ts
services/harmony/test/service-image-tags.ts

HARMONY-1834
Support cookie-secret header when getting service-deployments-state.
curl -i -H "COOKIE-SECRET: xxxxxx"  http://localhost:3000/service-deployments-state

HARMONY-1834: Support cookie-secret header when getting service-deployments-state.

---

config/services.yml
packages/util/env-defaults
scripts/service-comparison.ts
services/harmony/.nsprc
services/harmony/env-defaults

HARMONY-1789
Changes the logic for SAMBAH wrt the `concatenate` flag. Also enables `shapefile` subsetting and updates the online description of the service chain.
1. Deploy this branch
2. Run a query that will access the chain, with no `concatenate` flag passed, `concatenate` set to `false`, and `concatenate` set to `true`, with or without a shapefile. You should see all three queries invoking SAMBAH, but on the last request it should run all of query-cmr/l2ss/batchee/stitchee/concise (the first two just run query-cmr and l2ss).
```
http://localhost:3000/C1261880450-LARC_CLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?subset=lat(-70%3A30)&subset=lon(-157.5%3A-10)&concatenate=true&extend=true&maxResults=4
```
3. Check that the online documentation has a multiline …

HARMONY-1789: Change SAMBAH to only concatenate when the `concatenate` flag is set to true and update the description

---

bin/port-forward
docs/guides/managing-existing-services.md
services/harmony/app/frontends/ogc-edr/get-data-for-point.ts
services/harmony/app/frontends/ogc-edr/get-data-for-trajectory.ts
services/harmony/app/util/env.ts
services/harmony/env-defaults

HARMONY-1878, HARMONY-1873
Make WKT conversion precision configurable. 
Update /service-image-tag api doc.
Verify EDR position and trajectory searches still work. 
Verify /service-image-tag API doc looks good.

HARMONY-1878: Make WKT conversion precision configurable

---

services/harmony/app/backends/workflow-orchestration/work-item-polling.ts
services/harmony/app/routers/router.ts

HARMONY-1914
Moves some log messages from debug to silly to reduce the amount of noise when polling for work as well as middleware function calls when hitting endpoints.
By default make sure no log messages are logged when no frontend endpoints are being called (ensure that backend services polling for work with nothing to do in the system does not cause any messages to be logged).
Verify when hitting endpoints like submitting a request using the coverages API or requesting /jobs that no messages saying "Invoking middleware" or "Completed middleware" are called.
Set `LOG_LEVEL=silly` in your .env file and restart harmony. Verify that the polling messages are logged again and the Invoking and Completed middleware messages are called.

HARMONY-1914: Reduce the noise in the frontend logs when setting the log level to debug

---

services/harmony/app/middleware/cmr-collection-reader.ts
services/harmony/test/service-image-tags.ts

HARMONY-1920
Fixed EDR collection shortName matching regex.
Add trajectory-subsetter as one of the locally deployed service
Run Harmony Coverage request with collection short name and verify the request runs on the correct collection.
e.g. `http://localhost:3000/harmony_example/ogc-api-coverages/1.0.0/collections/blue_var/coverage/rangeset?maxResults=1&outputCrs=EPSG%3A31975&format=image%2Fpng`
Run Harmony EDR request with collection short name and verify the request runs on the correct collection.
e.g. `http://localhost:3000/ogc-api-edr/1.1.0/collections/harmony_example/trajectory?maxResults=1&parameter-name=all&coords=LINESTRING(9.51728%209.950%2C%2016.4064%2017.40134)`
Verify `http://localhost:3000/service-image-tag/trajectory-subsetter` returns the correct image tag of the …

HARMONY-1920: Fixed EDR collection shortName matching regex.

---

services/harmony/app/frontends/workflow-ui.ts
services/harmony/app/models/job.ts
services/harmony/app/models/label.ts
services/harmony/app/util/env.ts
services/harmony/app/util/job.ts
services/harmony/app/views/workflow-ui/job/work-item-table-row.mustache.html
services/harmony/app/views/workflow-ui/job/work-items-table.mustache.html
services/harmony/app/views/workflow-ui/jobs/job-table-row.mustache.html
services/harmony/app/views/workflow-ui/request-preview.mustache.html
services/harmony/public/css/workflow-ui/default.css
services/harmony/public/js/workflow-ui/job/work-items-table.js
services/harmony/public/js/workflow-ui/jobs/jobs-table.js
services/harmony/public/js/workflow-ui/table.js
services/harmony/test/jobs/jobs-listing.ts
services/harmony/test/jobs/jobs-status.ts
services/harmony/test/models/label.ts
services/harmony/test/parameters/label.ts
services/harmony/test/workflow-ui/jobs-table.ts
services/harmony/test/workflow-ui/jobs.ts
services/harmony/test/workflow-ui/work-items-table-row.ts
services/harmony/test/workflow-ui/work-items-table.ts

HARMONY-1891
Users will now see labels for jobs on all pages of the Workflow UI.
On the jobs page, each row will contain the job's label(s) on the bottom right corner of the row.
On the individual job page, a similar view will be displayed, which will also include the request URL, which I had intended to add in HARMONY-1497. The look of this may evolve in the future but for now I'm mainly going for consistency.
1. Make a request http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?granuleId=G1233800343-EEDTEST&format=image%2Ftiff&label=hi&label=there
2. Look at the labels http://localhost:3000/workflow-ui?page=1&limit=10

Harmony 1891 - Display job labels in Workflow UI

---

config/services.yml
docs/guides/adapting-new-services.md
services/harmony/app/models/data-operation.ts
services/harmony/app/schemas/data-operation/0.20.0/data-operation-v0.20.0.json
services/harmony/app/schemas/data-operation/CHANGELOG.md
services/harmony/app/schemas/data-operation/README.md
services/harmony/example/service-operation.json
services/harmony/test/helpers/data-operation.ts
services/harmony/test/models/data-operation.ts
services/harmony/test/resources/data-operation-samples/batch1-operation.json
services/harmony/test/resources/data-operation-samples/batch2-operation.json
services/harmony/test/resources/data-operation-samples/batch3-operation.json
services/harmony/test/resources/data-operation-samples/batch4-operation.json
services/harmony/test/resources/data-operation-samples/batch5-operation.json
services/harmony/test/resources/data-operation-samples/multiple-collections-operation.json
services/harmony/test/resources/data-operation-samples/valid-operation-input.json
services/harmony/test/resources/data-operation-samples/valid-operation-v0.20.0.json

HARMONY-1912
Adds support for the average parameter which specifies the averaging method to use for averaging services. This will be for the Giovanni services to know whether the request is for 'time' or 'area' averaging.
Since no services currently support time or area averaging you will need to modify one of the services in services.yml to add to the capabilities section (I tested with harmony-service-example):
```
averaging:
time: true
average: true
```
Then submit a request:
http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/blue_var/coverage/rangeset?subset=lat(20%3A60)&subset=lon(-140%3A-50)&granuleId=G1233800343-EEDTEST&outputCrs=EPSG%3A31975&format=image%2Fpng&average=time
Check the database in the workflow_steps table to verify the data operation field …

HARMONY-1912: Pass in average to the backend services.

---

docs/guides/managing-existing-services.md
services/harmony/app/frontends/stac.ts
services/harmony/app/markdown/cloud-access.md
services/harmony/app/markdown/endpoints.md

HARMONY-1924
This PR is an attempt to fix the intermittent STAC item retrieval issue in PROD and some unrelated documentation updates.
The STAC item retrieval in PROD is broken most of the time with Internal Server Error. e.g. https://harmony.earthdata.nasa.gov/stac/a740e311-6c04-4639-8cbf-3555612eb4be/1
It appears the db transaction is taking too long to complete sometimes in PROD only. Inspection of code reveals that the paging links construction and STAC catalog creation are done inside the db transaction unnecessarily. For this ticket, we will move these operations out of the db transaction and hopefully it will resolve the issue. If we see more db performance issues, we will write new ticket to further fine tune the performance if needed.
Make sure STAC catalog and item page still …

HARMONY-1924: Move paging link construction and STAC catalog creation out of db transaction

---

config/services.yml

TRT-588
This PR updates HyBIG to allow for variable subsetting (only one variable). This is to support browse image generation for PREFIRE, which requires a custom colour map, currently specified via a UMM-Var record.
* Pull [this branch](https://github.com/nasa/harmony-regression-tests/tree/TRT-588-HyBIG-variable) for the regression tests. (Unless [this PR](https://github.com/nasa/harmony-regression-tests/pull/105) is already merged - if so `main` will work)
* Stand up a local Harmony instance with [the latest HyBIG image](https://github.com/nasa/harmony-browse-image-generator/pkgs/container/harmony-browse-image-generator) (there are no actual changes to HyBIG).
* Run the updated HyBIG regression test notebook against your local Harmony instance. It should all pass, …

TRT-588 - Add variable subsetting option to HyBIG.

---

db/db.sql
db/migrations/20241021192628_add_jobid_id_index_to_job_links_table.js

HARMONY-1932
This PR fixes STAC item request hanging by adding a composite index on job_links table so that the STAC item request db query will use the composite index instead of the expensive table scan. After adding the index, the db query becomes tens of thousands times faster. See below for the query plan before and after the introduction of index:
```
Limit  (cost=0.56..3561.64 rows=1 width=337) (actual time=428998.478..428998.480 rows=1 loops=1)
->  LockRows  (cost=0.56..11028643.47 rows=3097 width=337) (actual time=428998.476..428998.477 rows=1 loops=1)
->  Index Scan using job_links_pkey on job_links  (cost=0.56..11028612.50 rows=3097 width=337) (actual time=428997.525..428997.526 rows=1 loops=1)
Filter: ((bbox IS NOT NULL) AND ("temporalStart" IS NOT NULL) AND ("temporalEnd" IS …
```

HARMONY-1932: Fix STAC item request hanging.

---

ENV_CHANGELOG.md
services/harmony/app/frontends/labels.ts
services/harmony/app/markdown/apis.md
services/harmony/app/models/label.ts
services/harmony/app/server.ts
services/harmony/app/util/env.ts
services/harmony/env-defaults
services/harmony/package-lock.json
services/harmony/package.json
services/harmony/test/labels/label_crud.ts
services/harmony/test/models/label.ts

HARMONY-1934
Add validation of labels to forbid certain words. Includes ability to explicitly allow or forbid specific words, in addition to defaults for English, Spanish, French, German
Try to start a job or add labels to a job using some curse words. (This may be the most fun we will ever have testing Harmony). If you don't know any, ask Chris; he knows loads of them. Or you use the fake one I added to the forbidden list just for demo purposes, "this_is_a_forbidden_label".

Harmony 1934

---

db/migrations/20241024193621_convert_job_links_href_to_text.js

HARMONY-1884
Converts job_links href column from varchar(4096) to text to support long urls
1. Run a job (if you haven't already) to put some rows in the job_links table
2. Select the rows in dbViz
3. Run the db migration
4. Check the schema in dbViz and make sure that the job_links href column is now type text
5. Select the rows from job_links and make sure that the hrefs have not changed
6. (optional) manually insert a row with a very long href into the job_links table

HARMONY-1884: Convert job_links href field to text type

---

services/harmony/app/frontends/workflow-ui.ts
services/harmony/test/workflow-ui/work-items-table.ts

HARMONY-1939
A bug was introduced where paging links on the individual job page of the workflow ui were taking users to the wrong route (the route for just the work items table vs. the whole page). This should fix that.
http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?format=image%2Ftiff
Use the paging links on the work items table and verify they work as expected (takes you to the right page, with CSS applied).
(You can also reproduce the bug on the main branch if you'd like, following the same steps as above.)

HARMONY-1939: Bug fix - remove /work-items from paging links

---

config/services.yml
services/harmony/env-defaults
services/harmony/test/versions.ts

https://harmony.uat.earthdata.nasa.gov/C1259974840-ASF/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?granuleId=G1260014889-ASF&format=image/png should produce three output files:
```
0.0002746662669663458
0.0
0.0
-0.00027461902098253427
-177.46826490379303
69.45012719494066
```
```
<PAMDataset>
<SRS dataAxisToSRSAxisMapping="2,1">GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]</SRS>
<GeoTransform> -1.7746840223692652e+02,  2.7466626696634580e-04,  0.0000000000000000e+00,  6.9450264504451155e+01,  0.0000000000000000e+00, …
```

add UAT service config for asf/opera-rtc-s1-browse

---

services/harmony/app/models/label.ts
services/harmony/test/helpers/db.ts
services/harmony/test/labels/label_crud.ts

HARMONY-1956
Fixes a bug where duplicate labels were showing up in the dropdown filter list when using the admin route.
* Create a job with labels
* Use dbViz to get the id for one of the labels, e.g.,`foo`:
```
select id from raw_labels where value='foo'
```
* Use dbViz to add a row to the `users_labels` with a new username pointing to an existing label, e.g., `edltest` and `foo`
```
insert into users_labels values(<id from above select>, 'edltest', 'foo', now(), now());
```
`edltest` does not have to be a real user.
* Open http://localhost:3000/admin/workflow-ui and start typing `label` in the filter box. You should to see the duplicate label more than once.

HARMONY-1956: Remove duplicates from label list

---

.github/pull_request_template.md
services/harmony/app/frontends/capabilities.ts
services/harmony/app/frontends/docs/service-docs-markdown-it-plugin.ts
services/harmony/app/models/services/base-service.ts
services/harmony/test/collection-capabilities.ts

HARMONY-1947, HARMONY-1917
As a harmony service provider, I want temporal subsetting information included in the collection capabilities endpoint.
Also updated the PR Acceptance Checklist to include testing harmony in a box reminder.
Verify `temporalSubset` field is included in the latest collection capabilities response. e.g.
http://localhost:3000/capabilities?collectionId=C1242267295-EEDTEST
Verify `temporal` field is included in the service capabilities documentation under the `subsetting` section.
http://localhost:3000/docs#service-capabilities
The checklist change will work once this PR is merged.

HARMONY-1947, HARMONY-1917: As a harmony service provider, I want temporal subsetting information included in the collection capabilities endpoint.

---

scripts/service-comparison.ts
services/harmony/app/frontends/capabilities.ts
services/harmony/app/frontends/service-image-tags.ts
services/harmony/app/frontends/workflow-ui.ts
services/harmony/app/middleware/cmr-collection-reader.ts
services/harmony/app/middleware/cmr-granule-locator.ts
services/harmony/app/middleware/cmr-umm-collection-reader.ts
services/harmony/app/middleware/earthdata-login-token-authorizer.ts
services/harmony/app/middleware/permission-groups.ts
services/harmony/app/models/job.ts
services/harmony/app/util/cmr.ts
services/harmony/app/util/edl-api.ts
services/harmony/app/util/grids.ts
services/harmony/test/helpers/caching-hooks.ts
services/harmony/test/util/cmr.ts
services/harmony/test/util/edl-api.ts
services/harmony/test/workflow-ui/work-items-table.ts
services/query-cmr/app/query.ts
services/query-cmr/test/query-granules.ts

HARMONY-1850
Adds X-Request-Id header to CMR and EDL calls to support end-to-end tracking
1. Run job
2. Look in the CMR logs for the 'x-request-id' header. This can be seen in the CMR CloudWatch logs using the following filter:
```
{$.x-request-id = "<YOUR ID>"}
```
You should see several log lines. The one that is for umm_json is from the qeury-cmr.

Harmony 1950 - X-Request-Id header

---

services/harmony/app/frontends/jobs.ts
services/harmony/app/frontends/workflow-ui.ts

HARMONY-1971
This improves the slow query that was hampering endpoints that pull back jobs + their tags (specifically the workflow ui and /jobs) from roughly 5 seconds of page load time to ~2 seconds in my testing.
Old query explain analyze output:
> Limit  (cost=219030.78..219030.79 rows=5 width=689) (actual time=4543.265..4562.898 rows=5 loops=1)
>   ->  Sort  (cost=219030.78..220021.01 rows=396094 width=689) (actual time=4543.263..4562.894 rows=5 loops=1)
>         Sort Key: jobs."createdAt" DESC
>         Sort Method: top-N heapsort  Memory: 31kB
>         ->  GroupAggregate  (cost=159388.48..212451.80 rows=396094 width=689) (actual time=2527.451..4222.021 rows=396094 loops=1)
>               Group Key: jobs.id
>               ->  Gather Merge  (cost=159388.48..205520.15 rows=396094 …

Harmony 1971 - Improve slow query for jobs+labels in jobs and workflow ui admin endpoints

---

README.md
bin/port-forward
bin/start-all
bin/stop-harmony-and-services

HARMONY-1942
This PR adds support for using [krelay](https://github.com/knight42/krelay) to handle port-forwarding. The primary advantage to `krelay` is that port forwarding will survive pod restarts. Using `krelay` is optional (controlled by the USE_KRELAY env var), and defaults to not using it.
1. kill your locally running harmony
```
./bin/stop-harmony-and-services`
```
2.  Check out this branch
3. Enable `krelay`
```
export USE_KRELAY=true
```
4. Run Harmony in a Box (Harmony in k8s)
5. Verify that Harmony runs correctly (workflow-ui, etc.)
6. Use `kubectl` or `k9s` to kill off the harmony pod
7. Wait for the harmony pod to retart
8. Verify harmony is still accessible (workflow-ui, etc.)

HARMONY-1942: Add optional use of krelay for port forwarding

---

db/db.sql
db/migrations/20250122190038_add_empty_result_status_to_work_items.js
db/migrations/20250122190038_add_warning_status_and_sub_status_to_work_items.js
db/migrations/20250124155544_add_level_and_category_to_job_errors.js
packages/util/tsconfig.build.json
packages/util/tsconfig.json
services/harmony/app/backends/workflow-orchestration/work-item-updates.ts
services/harmony/app/backends/workflow-orchestration/workflow-orchestration.ts
services/harmony/app/models/work-item-interface.ts
services/harmony/app/models/work-item-update.ts
services/harmony/app/models/work-item.ts
services/harmony/package-lock.json
services/harmony/test/work-items/work-backends.ts
services/work-failer/tsconfig.base.json
services/work-reaper/tsconfig.base.json
services/work-scheduler/tsconfig.json
services/work-updater/tsconfig.json
tsconfig.base.json

HARMONY-1996
This PR adds a new status to WorkItem to represent when a service processed the work-item, but produced to data. This is to allow us to provide a better experience for users by not staging empty files.
1. Use dbViz to update a work-item's status to 'empty-result' and verify that this is allowed. (This change will not be visible anywhere until further tickets are worked)
2. Run a Harmony request and verify that it goes through okay.
3. Check the status page and workflow UI to make sure the behavior has not changed
* [ x] Harmony in a Box tested? (if changes made to microservices)

Harmony 1996: Add 'empty-result' status to WorkItem class and work-items table

---

config/services.yml
docs/guides/adapting-new-services.md
services/harmony/app/frontends/capabilities.ts
services/harmony/app/frontends/ogc-coverages/describe-collections.ts
services/harmony/app/frontends/ogc-coverages/get-coverage-rangeset.ts
services/harmony/app/frontends/ogc-coverages/index.ts
services/harmony/app/frontends/ogc-edr/get-data-common.ts
services/harmony/app/frontends/wms.ts
services/harmony/app/middleware/cmr-collection-reader.ts
services/harmony/app/middleware/cmr-granule-locator.ts
services/harmony/app/middleware/cmr-umm-collection-reader.ts
services/harmony/app/middleware/restricted-variables.ts
services/harmony/app/middleware/service-selection.ts
services/harmony/app/models/harmony-request.ts
services/harmony/app/models/request-context.ts
services/harmony/app/models/services/base-service.ts
services/harmony/app/models/services/index.ts
services/harmony/app/routers/router.ts
services/harmony/app/util/parameter-parsing-helpers.ts
services/harmony/app/util/variables.ts
services/harmony/test/collection-capabilities.ts
services/harmony/test/middleware/restricted-variables.ts
services/harmony/test/middleware/umm-var-validation.ts
services/harmony/test/models/services.ts

HARMONY-1958
Allows service chains to skip validating variables exist in the CMR. This was requested by the Giovanni team to support their future time and area averaging services.
Since no service chains are currently configured to skip validation you will need to manually modify one of the service chains.
First test without changing services.yml to make sure you get a validation error with something like:
http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/bad_var/coverage/rangeset?subset=lat(20%3A60)&subset=lon(-140%3A-50)&granuleId=G1233800343-EEDTEST&outputCrs=EPSG%3A31975&format=image%2Fpng&subset=time(%222002-09-15T00%3A00%3A00.000Z%22%3A%222022-09-25T00%3A00%3A00Z%22)
```
{
"code": "harmony.RequestValidationError",
"description": "Error: Coverages were not …
```

HARMONY-1958: Allow service chains to skip validating variables exist in the CMR

---

services/harmony/app/frontends/service-image-tags.ts
services/harmony/app/routers/router.ts
services/harmony/test/service-image-tags.ts

HARMONY-1824
Save the deployment log when service deployment fails.
Add route to allow authorized users to view the log through Harmony frontend.
Provide link to the service deployment log in the message of failed service deployment status page.
Tested in my Sandbox with a modified `deploy-service` script that will fail with a message. 
Verified that the service deployment status page provide a link to the deployment logs. See below:
Follow the link, I can see the logs of service deployment.

HARMONY-1824: Add route for viewing service deployment error logs.

---

config/services.yml
docs/guides/adapting-new-services.md
services/harmony/app/models/job.ts
services/harmony/app/models/services/index.ts
services/harmony/test/models/index.ts
services/harmony/test/resources/services_no_umm_s_prod.yml
services/harmony/test/resources/services_no_umm_s_uat.yml
services/harmony/test/resources/services_umm_s_not_string_prod.yml
services/harmony/test/resources/services_umm_s_not_string_uat.yml
services/harmony/test/resources/services_with_colls_prod.yml
services/harmony/test/resources/services_with_colls_uat.yml
services/harmony/test/resources/services_with_false_is_sequential_query_cmr_prod.yml
services/harmony/test/resources/services_with_false_is_sequential_query_cmr_uat.yml
services/harmony/test/resources/services_with_unset_is_sequential_query_cmr_prod.yml
services/harmony/test/resources/services_with_unset_is_sequential_query_cmr_uat.yml

Add is_sequential: true where missing for query-cmr in services.yml and validation for same
HARMONY-2007
This fixes a configuration error where some query-cmr steps did not have `sequential: true`. This was causing jobs to move from `RUNNING_WITH_ERRORS` to `COMPLETED_WITH_ERRORS` prematurely. It also adds a validation for this setting and tests for the validation.
1. Do a deployment configured to point to production CMR/EDL. Or use my sandbox deployment here https://internal-harmony-jn-frontend-13863418.us-west-2.elb.amazonaws.com
2. Run the following query
```
http://localhost:3000/OPERA_L2_RTC-S1_V1/ogc-api-coverages/1.0.0/collections/parameter_vars/coverage/rangeset?forceAsync=true&subset=time(%222025-01-01T00%3A00%3A00%22%3A%222025-01-02T00%3A00%3A00%22)&destinationUrl=s3%3A%2F%2Fcdd- …
```

HARMONY-2007: Add is_sequential: true where missing for query-cmr in services.yml and validations for same

---

config/services.yml
services/harmony/test/versions.ts

HARMONY-2018
Moves reformatting services to the bottom of services.yml to ensure they are matched last in tiebreaker scenarios. This fixes an issue where requests were being sent to `net2cog` when they should instead be sent to `sds/HOSS-projection-gridded`.
Verify that http://localhost:3000/C1240150677-EEDTEST/ogc-api-coverages/1.0.0/collections/parameter_vars/coverage/rangeset?forceAsync=true&granuleId=G1245558662-EEDTEST&variable=%2FGPP%2Fgpp_mean&skipPreview=true is sent to `sds/HOSS-projection-gridded` (by checking http://localhost:3000/workflow-ui).
You can verify that in SIT and UAT the same request is currently going to `net2cog` which is not desired - https://harmony.uat.earthdata.nasa.gov/C1240150677-EEDTEST/ogc-api-coverages/1.0.0/collections/parameter_vars/coverage/rangeset?for …

HARMONY-2018: Move reformatting services to the bottom of services.yml

---

services/cron-service/app/cronjobs/work-reaper.ts
services/cron-service/test/work-reaper.ts
services/harmony/app/models/work-item.ts
services/harmony/app/models/workflow-steps.ts

HARMONY-2016
I think the issue is caused by the race condition between old work items cleanup and old workflow steps cleanup. Currently, work reaper uses the current time minus the `reapableWorkAgeMinutes` configuration value to find and cleanup old work items and old workflow steps, but because it takes time to run old work items cleanup, by the time it gets to workflow steps cleanup, there might be more work items that are eligible for cleanup based on the current time, thus causes the error documented in this ticket. 
The fix is to pre-calculate the cutoff time before executing the work items cleanup and the workflow steps cleanup to avoid the race condition.
npm run test

HARMONY-2016: Fix race condition in work reaper.

---

docs/guides/managing-existing-services.md
services/harmony/app/frontends/service-image-tags.ts
services/harmony/test/service-image-tags.ts

HARMONY-2030
Make successful service deployment logs available via Harmony deployment logs endpoint.
Tested in Sandbox. Now, there is a deployment log link in the message field of a successful deployment status page which leads to the log of the service deployment. See:
https://internal-harmony-yliu10-frontend-569546241.us-west-2.elb.amazonaws.com/service-deployment/9fc2fec7-8a2d-43fc-90a5-9d209eafe6df

HARMONY-2030: Make successful service deployment logs available via Harmony deployment logs endpoint.

---

services/harmony/app/frontends/ogc-coverages/get-coverage-rangeset.ts
services/harmony/app/frontends/ogc-edr/get-data-common.ts
services/harmony/app/schemas/ogc-api-coverages/1.0.0/ogc-api-coverages-v1.0.0.yml
services/harmony/app/schemas/ogc-api-edr/1.1.0/ogc-api-edr-v1.1.0.yml
services/harmony/app/util/cmr.ts
services/harmony/app/util/parameter-parsers.ts
services/harmony/test/ignore-errors.ts
services/harmony/test/ogc-api-coverages/get-coverage-rangeset.ts
services/harmony/test/ogc-api-edr/get-data-for-area.ts
services/harmony/test/ogc-api-edr/get-data-for-cube.ts
services/harmony/test/ogc-api-edr/get-data-for-point.ts
services/harmony/test/ogc-api-edr/get-data-for-trajectory.ts
services/harmony/test/parameters/concatenation.ts
services/harmony/test/util/parameter-parser.ts
services/harmony/test/util/parameter-parsing-helpers.ts

HARMONY-2024
As a harmony client, I want boolean parameters on transformation routes be validated against true/false
Submit OGC rangeset and EDR requests with different values for boolean parameters, e.g. 
http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/parameter_vars/coverage/rangeset?forceAsync=true&subset=lat(20%3A60)&subset=lon(-140%3A-50)&label=harmony-py&outputcrs=EPSG%3A31975&granuleId=G1233800343-EEDTEST&format=image%2Fpng&variable=blue_var&pixelSubset=xyz
http://localhost:3000/ogc-api-edr/1.1.0/collections/C1233800302-EEDTEST/area?forceAsync=true&coords=POLYGON((-140%2020%2C%20-50%2020%2C%20-50%2060%2C%20-140%2060%2C%20-140%2020))&datetime=1980-01-01T00%3A00%3A00Z%2F2020-12-30T00%3A00%3A00Z&label=harmony-py&crs=EPSG%3A31975&granuleId=C1233800302-EEDTE …

HARMONY-2024: As a harmony client, I want boolean parameters on transformation routes be validated against true/false

---

services/harmony/app/frontends/health.ts
services/harmony/app/util/cmr.ts
services/harmony/app/util/edl-api.ts
services/harmony/test/health.ts
services/harmony/test/helpers/health.ts

HARMONY-1986
Add CMR and EDL dependencies to health check.
http://localhost:3000/health now shows the CMR and EDL status in addition to db status:
```
{
status: "up",
message: "Harmony is operating normally.",
dependencies: [
{
name: "db",
status: "up"
},
{
name: "cmr",
status: "up"
},
{
name: "edl",
status: "up"
}
]
}
```

HARMONY-1986: As a Harmony operator I want the Harmony health endpoint to provide more detailed and fine-grained information

---

services/cron-service/env-defaults
services/service-runner/env-defaults
services/work-failer/env-defaults
services/work-scheduler/env-defaults
services/work-updater/env-defaults

HARMONY-2042
Fixes the issue that during deployments where app ports and liveness checks were sometimes out of sync between ports 3000 and 5000.
Run harmony locally using `bin/start-dev-services` and verify that all of the applications start up correctly and listen on different ports.
Run harmony in a box and verify requests work as expected.
I also tested in sandbox and verified requests worked as expected during deployments and all of the services and health checks were using port 3000.
You can check the configuration maps to make sure they are always using port 3000 with:
`kubectl get configmaps -n harmony -o yaml | grep PORT | grep -v WORKER_PORT | grep -v BACKEND`

HARMONY-2042: Update all the default ports to 3000

---

services/harmony/app/models/services/base-service.ts
services/harmony/app/models/services/index.ts
services/harmony/test/models/index.ts
services/harmony/test/resources/services_with_invalid_exists_condition.yml
services/harmony/test/resources/services_with_invalid_format_condition.yml
services/harmony/test/resources/services_with_invalid_step_operations.yml
services/harmony/test/resources/services_with_unsupported_step_operation.yml

HARMONY-2044
Adds some extra validation for service configs in services.yml
1. Add and invalid operation to a step in a service chain in services.yml on line 1407
```
operations: ['foo']
```
2. start harmony and see the following
```
TypeError: Service harmony/service-example step with image harmonyservices/service-example:latest has invalid operation 'foo'.
```
3. Remove the change to services.yml then add an invalid `conditional/exists` operation on line 1407
```
conditional:
exists: ['reformat']
```
4. start harmony and see the following error:
```
TypeError: Service harmony/service-example step with image harmonyservices/service-example:latest has invalid exists conditional 'reformat'.
```
5. Remove the changes to services.yml then add an unsupported output format on line 1407
``` …
```

HARMONY-2044: Add validtion of exists conditions and operations for steps in services.yml

---

bin/start-dev-services
config/services.yml
db/db.sql
db/migrations/20250331143557_add_always_wait_for_prior_step_to_workflow_steps.js
docs/guides/adapting-new-services.md
services/harmony/app/models/services/base-service.ts
services/harmony/app/models/workflow-steps.ts
services/harmony/package-lock.json
services/harmony/test/models/services.ts

HARMONY-2049
Fixes a bug where multiple batchee items were created when concatenate is not requested. You should be able to reproduce the problem with:
https://harmony.uat.earthdata.nasa.gov/C1254854453-LARC_CLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?subset=lat(-70%3A30)&subset=lon(-157.5%3A-10)&extend=foo,bar&granuleId=G1261454424-LARC_CLOUD&granuleId=G1261454434-LARC_CLOUD&granuleId=G1261454423-LARC_CLOUD&granuleId=G1261454429-LARC_CLOUD&label=all-but-concise
I also fixed an issue with starting up dev services intermittently failing.
In order to test you will first need to be setup to run the services for the SAMBAH chain locally.
* Add `batchee,stitchee,podaac-l2-subsetter,podaac-concise` to your `LOCALLY_DEPLOYED_SERVICES` in .env
* Add the following to your .env: …

HARMONY-2049: Fix behavior of SAMBAH chain when concatenate is not requested

---

services/harmony/app/backends/workflow-orchestration/work-item-updates.ts
services/harmony/test/workflow-orchestration.ts

HARMONY-2051
We've started seeing an error in production and reproduced in sandbox where work items are returning a successful status but without any output results. I'm not sure of the root cause yet, but this PR will change the error to be retried and only considered as a work item error as opposed to immediately failing the job.
Since I've been unable to figure out the exact root cause I'm just testing in the sandbox environment with an updated work-item-updater image. I'm finding that during an initial scale up I'm seeing the problem occur for quite a few work items and then the issues stopped. In looking at the pods I found some errors like the following (though could be unrelated):
```
{"env_name":"harmony-cdd-sandbox","level":"debug","message":"SIDECAR STATUS: {\n  \"metadata\": …
```

HARMONY-2051: Do not fail a job immediately if a work item does not provide outputs

---

services/harmony/app/frontends/service-image-tags.ts
services/harmony/test/service-image-tags.ts

HARMONY-1969
This is the Harmony part of the change to add support to deploy service with cookie secret. There will be a separate PR in harmony-service-example that will use this feature to deploy harmony-serivce-example as part of the Bamboo deployment.
Tested in Sandbox: 
curl -XPUT --insecure --socks5 localhost:8080 -H "COOKIE-SECRET: $bamboo_COOKIE_SECRET" -H 'Content-type: application/json' https://internal-harmony-yliu10-frontend-2063572707.us-west-2.elb.amazonaws.com/service-image-tag/harmony-service-example -d '{"tag": "latest"}'

HARMONY-1969: Add support to deploy service with cookie secret.

---

services/harmony/app/middleware/service-selection.ts
services/harmony/app/schemas/ogc-api-coverages/1.0.0/ogc-api-coverages-v1.0.0.yml
services/harmony/app/schemas/ogc-api-edr/1.1.0/ogc-api-edr-v1.1.0.yml
services/harmony/app/util/env.ts
services/harmony/env-defaults
services/harmony/test/middleware/service-selection.ts

HARMONY-2048
Add a feature toggle to allow a user to specify the service chain to use in test environments.
Set `ALLOW_SERVICE_SELECTION=false` in your .env
Verify that http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/blue_var/coverage/rangeset?subset=lat(20%3A60)&subset=lon(-140%3A-50)&outputCrs=EPSG%3A31975&format=image%2Fpng&maxResults=1&subset=time(%222002-09-15T00%3A00%3A00.000Z%22%3A%222022-09-25T00%3A00%3A00Z%22)&serviceId=harmony%2Fdownload
returns a 400 validation error with the message "Requesting a service chain using serviceId is disabled in this environment."
For the remaining tests make sure to remove `ALLOW_SERVICE_SELECTION=false` from your .env and restart harmony.
http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/bl …

HARMONY-2048: Add a feature toggle to allow a user to specify the service chain to use in test environments.

---

bin/create-k8s-config-maps-and-secrets
bin/deploy-services
docs/guides/adapting-new-services.md
services/service-runner/config/service-template.yaml

HARMONY-2052
This PR moves service specific environment variables out of the `harmony_env` config map and into the yaml template file for the service, so that services can't see environment variables for other services.
* add s service specific variable, e.g.,` BATCHEE_FOO=bar`, to your `.env` file and another one to `services/harmony/env-defaults` for one of the services in your `LOCALLY_DEPLOYED_SERVICES`.
* run ./bin/deploy and make sure queries still work. 
* use `kubectl` or `k9s` to describe the pod for the service
* verify that the environment variables are defined
* (optional) ssh into the worker container for the pod and `echo` the variables to make sure they are correct

Harmony 2025 - Add support for custom environment variables for services

---

services/harmony/app/frontends/health.ts
services/harmony/app/frontends/service-image-tags.ts
services/harmony/app/middleware/earthdata-login-token-authorizer.ts
services/harmony/app/util/env.ts
services/harmony/env-defaults
services/harmony/test/helpers/stub-edl-token.ts

HARMONY-2070
Here is a new approach that abandons the reuse of MemoryCache and just use LRUCache directly. I think it is much cleaner than the previous implementation.
Add the following line to line 54 of services/harmony/app/util/edl-api.ts to facilitate the testing:
console.log(`calling getUserIdRequest with token: ${userToken}`);
Use the following curl to submit an example harmony request with EDL bearer token:
curl -i -H "Authorization: Bearer $HARMONY_UAT_TOKEN" "http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/blue_var/coverage/rangeset?subset=lat(20%3A60)&subset=lon(-140%3A-50)&granuleId=G1233800343-EEDTEST&outputCrs=EPSG%3A31975&format=image%2Fpng"
Verify the `getUserIdRequest` function is called for only the first request, not the subsequent ones. …

HARMONY-2070: As a harmony user, I want my EDL bearer token cached so that I can submit many simultaneous requests.

---

services/harmony/app/backends/workflow-orchestration/work-item-updates.ts
services/service-runner/app/server.ts
services/service-runner/app/service/service-runner.ts
services/service-runner/app/util/k8s.ts
services/service-runner/app/workers/pull-worker.ts
services/service-runner/test/pull-worker.ts
services/service-runner/test/service-runner.ts

HARMONY-2079
Fixes a bug where the service-runner was attempting to make a request to the worker container but an error was being returned indicating the worker container was not ready.
I made a few changes to get more logging information saved in the work item logs we push to S3 in addition to changing the service runner to first make a k8s call to check if the worker is in a running state. It seems like that change to check fixed the problem altogether despite not finding any evidence that the check failed. I also changed the service runner to not immediately return an error to harmony if there was a k8s issue with the exec call (not the worker container returning a non zero exit code which is still handled in the same way). If there is a k8s issue it will check to make sure the worker …

HARMONY-2079: Fix issue with worker container not being ready

---

services/harmony/app/util/edl-api.ts

HARMONY-2070
This only adds some logging messages to make monitoring possible.
Run:
```
for i in {1..10}; do curl -i -H "Authorization: Bearer $HARMONY_UAT_TOKEN" "http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/blue_var/coverage/rangeset?subset=lat(20%3A60)&subset=lon(-140%3A-50)&granuleId=G1233800343-EEDTEST&outputCrs=EPSG%3A31975&format=image%2Fpng&forceAsync=true"&; done
```
and verify the logging messages `Calling EDL to validate bearer token` and `Successfully validated bearer token for user: ......` only show up in log once.

HARMONY-2070: Add logging.

---

bin/create-k8s-config-maps-and-secrets

HARMONY-2090
While testing a new service image and chain locally with harmony in a box we found that the work item for the new service was populated with a blank string instead of the image name when submitting a request. The issue was the image environment variable is not being created in the harmony configmap. You will only see this issue when testing with harmony in a box which uses a configmap for the harmony environment variables.
Use harmony in a box. Add a new service chain and service image.
e.g. in `services/harmony/env-defaults`
```
FILTERING_IMAGE=harmony/filtering:latest
FILTERING_REQUESTS_MEMORY=128Mi
FILTERING_LIMITS_MEMORY=512Mi
FILTERING_INVOCATION_ARGS='python -m filtering'
FILTERING_SERVICE_QUEUE_URLS='["harmony/filtering:latest,http://sqs.us-west-2.localhost.localstack.c …
```

HARMONY-2090: Fix for images variables not being populated in the harmony-env configmap which are needed when creating workflow steps.

---

packages/util/env-defaults
services/harmony/app/middleware/earthdata-login-token-authorizer.ts
services/harmony/app/util/cmr.ts
services/harmony/app/util/edl-api.ts
services/harmony/app/util/env.ts
services/harmony/env-defaults
services/harmony/test/helpers/stub-edl-token.ts
services/harmony/test/util/cmr.ts
services/query-cmr/package-lock.json
services/query-cmr/package.json

HARMONY-2085
This PR adds caching for CMR collections/variables/services/grids and EDL queries such as EDL user group search, Eula verification.
Add the following configuration in `.env` to make testing easier:
```
TOKEN_CACHE_TTL=60000
EDL_CACHE_TTL=60000
CMR_CACHE_TTL=60000
```
Modify the `services-uat.yml` `harmony/service-example` service section to the following to test out the UMM collection caching:
```
- name: harmony/service-example
description: |
Reference service that can be used to perform most operations supported by Harmony.
Useful for testing new API features end-to-end on example data but not meant for production use.
data_operation_version: '0.21.0'
type:
<<: *default-turbo-config
params:
<<: *default-turbo-params
env:
<<: *default-turbo-env
STAGING_PATH: …
```

HARMONY-2085: Add caching for CMR collections/variables/services/grids and EDL queries.

---

config/services-prod.yml
config/services-uat.yml
services/harmony/app/models/data-operation.ts
services/query-cmr/app/query.ts
services/query-cmr/app/stac/cmr-catalog.ts
services/query-cmr/test/cmr-to-stac.ts
services/query-cmr/test/query-granules.ts

HARMONY-2054
When the harmony/download service is used we want the only outputs to be the granule download links. Previously it was including both the download links and OPeNDAP links as query-cmr was including both in its outputs since some service chains make use of both.
This change will allow query-cmr to provide both types of links when used as part of a service chain, but when the download service is used it will only provide the granule download links.
1. `npm run build` in the query-cmr directory
2. Make this request that will go to the trajectory-subsetter (don't worry if you don't have it deployed - we're only looking at the links provided by the query-cmr step). http://localhost:3000/C1242267295-EEDTEST/ogc-api-coverages/1.0.0/collections/%2FBEAM0000%2Fagbd/coverage/rangeset?for …

HARMONY-2054: Do not include OPeNDAP links as outputs when the harmony/download service chain is used.

---

config/services-uat.yml
packages/util/env-defaults
services/harmony/env-defaults
services/harmony/test/versions.ts

Updated services-uat/env-defaults,/versions.ts for the deployment of the Filtering Service on UAT
HARMONY-2067
This PR defines the filtering service chain for UAT.
The Test URL for this service:
/C1262899964-LARC_CLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?maxresults=1&forceasync=true

Set up Harmony Filtering Service for UAT

---

config/services-uat.yml
services/harmony/app/backends/service-invoker.ts
services/harmony/app/middleware/external-validation.ts
services/harmony/app/models/harmony-request.ts
services/harmony/app/routers/router.ts
services/harmony/test/middleware/external-validation.ts
services/harmony/test/versions.ts

HARMONY-2066
Configures the Giovanni averaging services to use PURE external endpoint for validation.
Test with http://localhost:3000/C1215802935-GES_DISC/ogc-api-coverages/1.0.0/collections/parameter_vars/coverage/rangeset?format=image%2Ftiff&subset=time(%222009-01-01T00%3A00%3A00%22%3A%222009-01-05T10%3A31%3A12%22)&variable=M2T1NXAER_5_12_4_BCCMASS&subset=lat(-50%3A-48)&subset=lon(-90%3A-87)&average=time
and verify from the logs that the external validation endpoint is called (search for `timing.external-validation.start` and `timing.external-validation.end`).
To simulate a failure change the code to make the bearer token authorization header invalid. Change the code in `external-validation.ts` line 40 to add a colon after Bearer which is not valid:
`'Authorization': `Bearer: …

HARMONY-2066: Configure Giovanni averaging services to use PURE endpoint for validation

---

services/query-cmr/app/query.ts
services/query-cmr/test/query.ts

HARMONY-2098
We were running into issues for many of the NSIDC datasets where the query-cmr task was not providing a size and so the work item updates would take several minutes when a job had more than a few hundred granules often resulting in timeouts and retries being triggered and blocking other updates from other jobs. The root cause is that the UMM granule metadata has "NA" for the SizeUnit. We found the CMR JSON endpoint treats the value as MB in this case which is the correct behavior for all of the NSIDC datasets and makes since because historically granule metadata was ingested in ECHO10 format which treated all sizes as MB.
The change in this PR causes the work item update to take seconds now instead of many minutes.
Build the query-cmr docker image.
I'm not sure if there are …

HARMONY-2098: Treat NA SizeUnits as MB 

---

services/harmony/app/frontends/service-results.ts
services/harmony/app/middleware/error-handler.ts
services/harmony/app/models/job.ts
services/harmony/app/routers/router.ts
services/harmony/app/util/env.ts
services/harmony/env-defaults
services/harmony/test/helpers/job-status.ts
services/harmony/test/jobs/job-sharing.ts
services/harmony/test/jobs/jobs-status.ts
services/harmony/test/service-results.ts
services/harmony/test/stac/stac-item.ts

HARMONY-2023
Added two more parameters for tracking S3 access from pre-signed S3 URLs: A-provider and A-api-request-uuid.
Figuring out the provider for an output required parsing the URL for the job ID and then querying for the provider for that job. A common use case will be to download all of the outputs for a job, so I added a cache to only look up the provider id once for the output for a single job.
1. Submit a request locally which completes successfully - e.g. http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/blue_var/coverage/rangeset?subset=lat(20%3A60)&subset=lon(-140%3A-50)&outputCrs=EPSG%3A31975&format=image%2Fpng&maxResults=1&subset=time(%222002-09-15T00%3A00%3A00.000Z%22%3A%222022-09-25T00%3A00%3A00Z%22)
2. Once it completes get the download link …

HARMONY-2023: Include parameters for tracking S3 access - added both A-provider and A-api-request-uuid

---

services/harmony/app/util/cmr.ts

HARMONY-2094
Add umm version to cmr grid requests
Make sure queries that specify a grid still work, e.g.
```
curl -i -H "Authorization: Bearer $MY_UAT_TOKEN" "http://localhost:3000/C1233860183-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?granuleId=G1233860486-EEDTEST&grid=LambertDurbin"
```

HARMONY-2094: Add umm version to cmr grid requests

---

services/service-runner/app/service/service-runner.ts

HARMONY-2093
Add exponential backoff to service-runner retries to help with errors connecting to the worker. Previously we were checking the container status to see if it was ready before retrying, but possibly due to this bug (https://github.com/kubernetes/kubernetes/issues/106896) the container status was reporting `ready` very quickly and subsequent retries would fail quickly. This change simply waits an increasing amount before retrying. 
There is no easy way to force an error like the ones we were seeing in production. We were unable to reproduce it in the sandbox. To test, build the service-runner image then restart your local deployment. Then run some queries of various sizes and make sure they complete.
* [?] Acceptance criteria met

HARMONY-2093: Add exponential backoff on servie-runner retries

---

services/harmony/app/frontends/service-results.ts
services/harmony/app/models/job.ts
services/harmony/app/routers/router.ts
services/harmony/test/service-results.ts

HARMONY-2023
Fix the /service-results route so that it can continue to serve test data from buckets in the harmony UAT account.
You can continue to sanity check that the /service-results endpoint for accessing work outputs includes all 3 fields - A-userid, A-api-request-uuid, and A-provider:
```
{"A-userid":"cdurbin","A-api-request-uuid":"f45c4a3b-0978-4e37-b33f-5fa787b76f48","A-provider":"EEDTEST"}
```
We cannot test that the harmony test buckets continue to serve results until we've deployed this change to UAT. We do verify the behavior in the tests (prior to this change the test would fail with a 404 when trying that bucket route).

HARMONY-2023: Fix the /service-results route so that it can continue to serve test data from buckets in the harmony UAT account.

---

services/harmony/app/frontends/workflow-ui.ts
services/harmony/test/workflow-ui/work-items-table.ts

HARMONY-2103
Add links to service logs for warning work items on workflow-ui.
Follow the following steps to submit a harmony request with work items with warning messages and verify there are links to the service logs of the warning work items now on workflow-ui.
Modify harmony-service-example to create nodata warnings for specific granules to facilitate with the testing. e.g. add `from harmony_service_lib.exceptions import NoDataException` at the top and the following to around line 98 of `transform.py` in harmony-service-example:
```
if asset.href == 'https://harmony.uat.earthdata.nasa.gov/service-results/harmony-uat-eedtest-data/C1233800302-EEDTEST/nc/001_00_7f00ff_global.nc' or asset.href == 'https://harmony.uat.earthdata.nasa.gov/service-results/harmony-uat-eedtest-data/C1233800302-EE …
```

HARMONY-2103: Add links to service logs for warning work items on workflow-ui.

---

services/service-runner/app/util/axios-clients.ts
services/work-scheduler/app/util/env.ts
services/work-scheduler/app/workers/scheduler.ts
services/work-scheduler/env-defaults

HARMONY-2115
Add FAST_SERVICE_QUEUE_BATCH_SIZE_COEFFICIENT configuration to make work scheduling better for query-cmr service.
Test in a sandbox environment:
1. Build and push work-scheduler image to ECR.
2. Configure harmony-ci-cd to use the built image and run `bin/deploy` to deploy Harmony in Sandbox.
3. On the EC2 instance in the environment install vegeta
```
curl -LO https://github.com/tsenart/vegeta/releases/download/v12.12.0/vegeta_12.12.0_linux_amd64.tar.gz
tar -xzf vegeta_12.12.0_linux_amd64.tar.gz
sudo mv vegeta /usr/local/bin/
```
Verify it is working
`vegeta -version`
4. Set your EDL Token for the UAT environment
export EDL_TOKEN=<>
Kick off 1000 requests - in this case, 50 per second for 520seconds (change the URL to your LB URL)
```
echo "GET https://internal-harmony-...<LB …
```

HARMONY-2115: Add FAST_SERVICE_QUEUE_BATCH_SIZE_COEFFICIENT configuration to make work scheduling better for query-cmr service.

---

config/services-uat.yml
services/harmony/test/versions.ts

[DAS-2346](https://bugs.earthdata.nasa.gov/browse/DAS-2346)
[DAS-2352](https://bugs.earthdata.nasa.gov/browse/DAS-2352)
This PR makes two updates:
1.  Renames `sds/HOSS-HRS-GeoTIFF` to `sds/HOSS-regridder-reformatter`
2. Makes HOSS conditional so that HOSS is not called when there is regridding/reformatting requested without subsetting
The MMT record has been updated to reflect the new service name:
https://mmt.uat.earthdata.nasa.gov/services/S1273752002-EEDTEST
1. Pull down this branch and restart harmony-in-a-box.
2. Run the following requests and verify the correct services in the `sds/HOSS-regridder-reformatter` chain were called.
**Note: net2cog is expected to fail on these requests but the service failure is outside the scope of this PR**
- Test 1: subset: none, reformatting: yes …

DAS-2346-DAS-2352-fix: Rename sds/HOSS-HRS-GeoTIFF and make HOSS conditional

---

services/harmony/app/backends/workflow-orchestration/work-item-updates.ts
services/harmony/app/middleware/cmr-granule-locator.ts
services/harmony/app/middleware/external-validation.ts

HARMONY-2157
Fixes a bug that was causing OPeNDAP links to be included in results from the harmony/download service which should only be returning data links. The bug happened when `forceAsync=true` was passed in which caused the extra query-cmr granuleValidation step processing to occur. 
I tested by pointing to CMR and EDL production and issuing the same request Andrey made:
http://localhost:3000/C2930725014-LARC_CLOUD/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=true&granuleId=G3598508234-LARC_CLOUD&concatenate=false&skipPreview=true&label=eed-edsc-prod%2Cedsc-id%3D4434906266
I believe you can also test with UAT configuration with this request I found from my prior PR for HARMONY-2054 that initially added this functionality to not include OPeNDAP links: …

HARMONY-2157: Fix bugs where extraArgs were not being added correctly

---

package-lock.json
services/cron-service/package-lock.json
services/service-runner/package-lock.json
services/work-failer/package-lock.json
services/work-scheduler/package-lock.json
services/work-updater/package-lock.json

HARMONY-2160
There were two package-lock files not updated that are causing docker builds to fail when running `npm ci`. This is causing deployments to fail on main right now.
`npm run build-all` - make sure all the docker images build.

HARMONY-2160: Update package-lock.json files to fix building images

---

services/harmony/app/backends/workflow-orchestration/work-item-updates.ts
services/harmony/test/work-items/retries.ts

HARMONY-2159
Add support in Harmony to handle non-retriable errors from services.
This PR is to be tested together with [this harmony-service-lib-py PR](https://github.com/nasa/harmony-service-lib-py/pull/65) with the NoRetryException change.
Change harmony-service-example to create a non-retryable error for specific granules to facilitate with the testing. e.g. 
add `from harmony_service_lib.exceptions import NoRetryException` at the top of transform.py in harmony-service-example and the following to around line 96:
```
if asset.href == 'https://harmony.uat.earthdata.nasa.gov/service-results/harmony-uat-eedtest-data/C1233800302-EEDTEST/nc/001_00_7f00ff_global.nc' or asset.href == 'https://harmony.uat.earthdata.nasa.gov/service-results/harmony-uat-eedtest-data/C1233800302-EEDTEST/nc/001_07 …
```

HARMONY-2159: Add support in Harmony to handle non-retriable errors from services

---

config/services-prod.yml

TRT-620
This PR adds the asdc/imagenator_l2 & asdc/imagenator_l3 service chains to services-prod.yml. The new service chains configuration mimics the existing asdc/imagenator_l2 & asdc/imagenator_l3 service chain in services-uat.yml.
The umm-s records we point to in the prod service chains are:
asdc/imagenator_l2: [S3616918926-LARC_CLOUD](https://mmt.earthdata.nasa.gov/services/S3616918458-LARC_CLOUD)
asdc/imagenator_l3: [S3616918458-LARC_CLOUD](https://mmt.earthdata.nasa.gov/services/S3616918926-LARC_CLOUD)
The TEMPO collections are associated with them at this time. 
**Test URL for IMAGENATOR L3:** 
https://harmony.earthdata.nasa.gov/C2930763263-LARC_CLOUD/ogc-api-coverages/1.0.0/collections/parameter_vars/coverage/rangeset?maxresults=1&granuleid=G3620400572-LARC_CLOUD&format=image/png&f …

Add IMAGENATOR to production configuration

---

config/services-prod.yml

Add Giovanni averaging services to production services yaml file. This is intended to be deployed on Tuesday 9/23 production deployment.

Add Giovanni averaging services to prod
